### ISSUE TITLE
Ensure all files have correct family-style metadata

### ISSUE THREAD

**Issue by davelab6** [google/fonts#106]
- [ ] Filename matches the standard
- [ ] PostScript Name matches filename
- [ ] OS/2 usWeightClass value is correct
- [ ] OS/2 fsSelection value is correct
- [ ] head macStyle value is correct
- [ ] NAME table is set up correctly for use of the font family in Windows GDI applications (like Word)

Known families with problems:
- [ ] Muli
- [ ] Oswald

**Comment by hertzmann** [comment]
Looking for fonts with duplicate PS names, I've found a few fonts with wrong PS names in their metadata:

* ofl/josefinsans/JosefinSans-Italic metadata (in the font file itself, not the METADATA.json) gives the PS name as JosefinSans-Regular

* ofl/josefinsans/JosefinSans-ThinItalic metadata gives the ps name as Thin, not ThinItalic

* ofl/suwannaphum/Suwannaphum.ttf reports PS name as battambang.

There are a lot of examples where the filename doesn't match the PS name, e.g., Aclonica, Arimo, Cousine, Crushed, etc.

There are also some duplicates fonts; I assume this is intentional (e.g., MrsSaintDelafield and MissSaintDelafield, Dosis and TerminalDosis, MrBedford and MrBedfort; Alef and AlefHebrew; Siamreap and Siemreap).

**Comment by davelab6** [comment]
> Josefin

That has had a big update pending for a while. 

> Suwannaphum

I'll contact the designer about this, as the NAME table has fields in Khmer that I can't easily create correctly.

> There are a lot of examples where the filename doesn't match the PS name, e.g., Aclonica, Arimo, Cousine, Crushed, etc.

Yes, and I'll update them with a script that checks :) 

> There are also some duplicates fonts

Yes, please see https://github.com/google/fonts/blob/master/TRIVIA.md#duplicated-fonts for details :)

**Comment by olivierberten** [comment]
#106

**Comment by mprewitt** [comment]
In addition to the **Josefin Sans italic** (regular italic) and **Josefin Sans Thin italic** that were previously reported as missing the correct "Italic" style designation in the PostScript meta, the weight **Josefin Sans SemiBold italic** also has the same issue.
