### ISSUE TITLE
GF Latin Pro: Remove /firsttonechinese

### ISSUE THREAD

**Issue by madig** [google/fonts#1088]
Pinyin is generated using /macroncomb in Glyphs.app. If /firsttonechinese should be used instead, what about the other tones?

**Comment by davelab6** [comment]
@alexeiva do you know? :)

**Comment by alexeiva** [comment]
Pinyin isn't supported by GF Latin Pro. Firstonechinese was meant for Sanscrit transliterations, but macroncomb is more common for this. @kalapi should know better.

**Comment by kalapi** [comment]
@madig @davelab6 @alexeiva 

Hello! I've been trying to remember why this was added to the set but I can't seem to remember. It may have been for transliteration but I remember using 'fileformat.info' to double check character descriptions and this one screams Mandarin. I guess it's safe to remove this from the list, it is a component of the `Macron` anyway.

**Comment by davelab6** [comment]
@alexeiva please remove this :)

**Comment by alexeiva** [comment]
In Latin Pro we have
```
U+02CA ˊ secondtonechinese
U+02CB ˋ fourthtonechinese
```
Perhaps we should move U+02C9 ‘firsttonechinese’ to Pro.

**Comment by alexeiva** [comment]
I have seen websites use precomposed Latin glyphs for Pinyin. This seems to be the general practice:

ō `‎014D  LATIN SMALL LETTER O WITH MACRON` instead of `o` + `U+02C9` 
ā `‎0101  LATIN SMALL LETTER A WITH MACRON` instead of `a` + `U+02C9`
etc.

Pinyin sample: māma mà mǎde má ma

According to GlyphData.xml, there are 3 Chinese tones
```
	<glyph unicode="02C9" name="firsttonechinese" category="Mark" subCategory="Modifier" production="uni02C9" description="MODIFIER LETTER MACRON" />
	<glyph unicode="02CA" name="secondtonechinese" category="Mark" subCategory="Modifier" production="uni02CA" description="MODIFIER LETTER ACUTE ACCENT" />
	<glyph unicode="02CB" name="fourthtonechinese" category="Mark" subCategory="Modifier" production="uni02CB" description="MODIFIER LETTER GRAVE ACCENT" />

```

And `caron` is used for the third tone.  (ǎ)

```
<glyph unicode="02C7" name="caron" decompose="caroncomb" category="Mark" subCategory="Spacing" description="CARON" />
```

I think having the three tones together in Pro is logical. They may be helpful when people start using proper Pinyin. 

```
0x02C9 ˉ MODIFIER LETTER MACRON
0x02CA ˊ MODIFIER LETTER ACUTE ACCENT
0x02CB ˋ MODIFIER LETTER GRAVE ACCENT
```
