### ISSUE TITLE
Issue loading the site in Firefox Nightly (57)

### ISSUE THREAD

**Issue by scheinercc** [google/fonts#1135]
Hi there,

For a week or so the site is not loading in Nightly with `gfx.downloadable_fonts.otl_validation` set to `true` (default on Nightly) at all anymore.
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1387315
<img width="1241" alt="screen shot 2017-08-10 at 23 01 11" src="https://user-images.githubusercontent.com/817856/29171413-e6cb6cc8-7e1f-11e7-8976-063fb6631182.png">

**Comment by m4rc1e** [comment]
Thank you, we're aware of this :-).

From the thread you linked:
> The default behavior will still be as now -- such fonts will load on Beta/Release, so we don't annoy too many users, but Nightly/DevEd will block them and issue console error messages to **encourage people to report and fix out-of-spec fonts and font-deployment workflows.**

**Comment by scheinercc** [comment]
Thanks Marc. Is there any estimation on when this might be fixed? Is it currently being worked on?

**Comment by m4rc1e** [comment]
The issue is being reported by [ots](https://github.com/khaledhosny/ots) which is used in FF. It checks that fonts conform to the [OT spec](https://www.microsoft.com/en-us/Typography/OpenTypeSpecification.aspx). The issue is in the fonts, not the site.

The spec has been recently updated. I remember this particular issue was mentioned. I still need to see if this is an on going issue or the spec relaxed it.

**Comment by m4rc1e** [comment]
Here's a relevant issue for you, https://github.com/google/fonts/issues/738

**Comment by scheinercc** [comment]
Thanks Marc! When the Robot failed and squares where displayed instead most of the site was still working. 
Does this comment help at all? https://bugzilla.mozilla.org/show_bug.cgi?id=1331797#c29

**Comment by scheinercc** [comment]
Closing as per https://github.com/google/fonts/issues/738#issuecomment-321930961
