### ISSUE TITLE
News Cycle has no Mac name fields

### ISSUE THREAD

**Issue by laerm0** [google/fonts#1147]
Fontbook throws some errors when installing these files: regular & bold have no Mac name fields.

https://code.google.com/archive/p/googlefontdirectory/issues/170

**Comment by m4rc1e** [comment]
You've also modified existing name records and added name records which belong to MonoType.

<img width="1440" alt="Screenshot 2019-07-02 at 12 18 28" src="https://user-images.githubusercontent.com/7525512/60508899-90003800-9cc3-11e9-9957-067c6676de1d.png">

I'm guessing you've done this hotfix  by using a proprietary MonoType tool. Use fontTools instead please.

Closing since the fonts on GF work in Fontbook 9.0 (330), OS X 10.14.3.
