### ISSUE TITLE
AmaticSC-Regular uses a wrong glyph for the Euro character (Unicode U+20AC)

### ISSUE THREAD

**Issue by Ziriax** [google/fonts#116]
It contains an "O" glyph instead, so no fallback character is used either.

Strangely the bold face does contain a Euro character

**Comment by davelab6** [comment]
Other Amatic issues: https://github.com/google/fonts/issues/95 https://github.com/google/fonts/issues/96

**Comment by graphicore** [comment]
Fixed in https://github.com/graphicore/MaticFonts

![screen shot 2016-09-05 at 03 02 17](https://cloud.githubusercontent.com/assets/393132/18244504/406e12ce-7315-11e6-97d2-e73a97da18a8.png)


![screen shot 2016-09-05 at 03 01 29](https://cloud.githubusercontent.com/assets/393132/18244481/1d95a456-7315-11e6-9fa6-36d2ba6faca0.png)

**Comment by laerm0** [comment]
This is no longer an issue so I am closing.

![screen region 2017-09-11 at 15 45 42](https://user-images.githubusercontent.com/10780161/30293649-4dc7709c-9708-11e7-8692-0c1e0d290324.png)
