### ISSUE TITLE
Unlist Droid fonts

### ISSUE THREAD

**Issue by davelab6** [google/fonts#1223]
Droid fonts are in the main directory and https://fonts.google.com/earlyaccess but they are deprecated by Noto, so we should unlist them all.

**Comment by Siyfion** [comment]
@davelab6 This caused us a major headache in our application as some of our customers were using this font. Is there a way to either:

- Filter out Early Access Fonts from the Developer API until such point that they are "fully" supported?
- Get notifications, ideally via a webhook, of removed Google Fonts?

**Comment by davelab6** [comment]
@Siyfion I am confused on both points :)

> Filter out Early Access Fonts from the Developer API until such point that they are "fully" supported?

None of the Early Access fonts are ever listed in the Developer API.

> Get notifications, ideally via a webhook, of removed Google Fonts?

http://fonts.googleapis.com/earlyaccess/droidarabickufi.css works for me; while it is de-listed from the https://fonts.google.com/earlyaccess page, it should still work for everyone who already linked to it. 

When we graduate families from Early Access, we serve the main Google Fonts API's CSS to their previously listed CSS URL. Eg Amiri (https://fonts.google.com/specimen/Amiri) was graduated such that http://fonts.googleapis.com/earlyaccess/amiri.css now returns the same fonts as https://fonts.googleapis.com/css?family=Amiri:400,400i,700,700i&amp;subset=arabic,latin-ext 

Please could you be more specific about what your customers experienced?

**Comment by davelab6** [comment]
Oh! I think you mean that you were using Droid Sans, itself, which was listed in the main directory, and while fonts.googleapis.com/css?family=Droid+Sans continues to be served, it is no longer listed in the Developer API. 

I've field to https://github.com/google/fonts/issues/1314 to discuss this; I expect more families to be de-listed in the future.

**Comment by jexler** [comment]
> Droid fonts are in the main directory and https://fonts.google.com/earlyaccess but they are deprecated by Noto, so we should unlist them all.

I guess the reason behind that is that e.g. Droid Sans (which can still be downloaded e.g. via https://fonts.googleapis.com/css?family=Droid+Sans or places like 1001fonts.com, and for Latex via at http://www.tug.dk/FontCatalogue/droidsans/ resp. https://ctan.org/tex-archive/fonts/droid/) lacks many Unicode characters, which are, in turn, supported in the commercial font "Droid Sans Pro" by "Ascender Corporation" and, I presume, Google chose not to add more characters to the "Droid Sans" font under the Apache 2.0 license essentially in order to avoid potential legal issues with the commercial version. So Google eventually simply "rebooted", including lately with Noto fonts at https://en.wikipedia.org/wiki/Noto_fonts, I would presume.

Anyways, so it is safe to assume that the original "Droid Sans" ist still free / Open Source under the Apache 2.0 licencse, right?

**Comment by davelab6** [comment]
Yes, if you obtain the files under the Apache license, you can continue to use them under that license.
