### ISSUE TITLE
Strange font issue in iPhone5 using Playfair Display

### ISSUE THREAD

**Issue by mprovojr** [google/fonts#1227]
**Strange issue with Playfair Display**

Many characters in the "Playfair Display" font are showing in a way that looks like they are an outline font or that the font is doubled (look at the "F" in the second screen shot).

Screen shots below are taken from an **iPhone 5S on iOS 10.3.3, Safari and Chrome 61.0.3163.73.**

Changing **-webkit-font-smoothing** values didn't address it (I thought it was maybe a webkit issue). Using a different font eliminates the issue, and it's not happening in IE or Firefox, so it appears to be a bug with the Playfair Display font and webkit browsers specifically.

![playfair-display-1](https://user-images.githubusercontent.com/715349/30888498-d4a347f2-a2ee-11e7-8cb2-356f05e0bf83.png)

![playfair-display-2](https://user-images.githubusercontent.com/715349/30888499-d4a57f0e-a2ee-11e7-8870-0329625fd9e4.png)

**Comment by davelab6** [comment]
@clauseggers please take a look

**Comment by clauseggers** [comment]
Classic faux-bold.

**Comment by alexjohnson505** [comment]
A quick note for anyone (like myself) that found this issue via Google... and didn't know what faux-bold meant:

> **Faux-bold**: If text is styled as bold or italic and the typeface family does not include a bold or italic font, browsers will compensate by trying to create bold and italic styles themselves.

Source: https://alistapart.com/article/say-no-to-faux-bold

The solution for me was to ensure I was importing the correct font weights that I was using in the document. I'd missed this issue previously since iOS/Safari handled the "faux-bold" rendering differently than chrome/firefox.
