### ISSUE TITLE
Google fonts not displaying correctly in different browsers

### ISSUE THREAD

**Issue by SORIdent** [google/fonts#126]
Hello. I'm having an issue on my website with two different google fonts (Comfortaa & Hind Vadodara). They display very smooth and good looking on Chrome but on every other browser (IE, Firefox, Safari) they look very unsmooth and buggy. I use Chrome so that's not a problem for me, but I'm afraid not everybody uses Chrome, so for other users the experience might be pretty ugly.
I've loaded the fonts through css using " @import url(https://fonts.googleapis.com/css?family=Comfortaa|Hind+Vadodara:400,500&subset=latin,latin-ext) " in the style.css that the webpage loads. I tested on 2 different computers, both using Windows 7 x64 and with different browsers and I have this problem.
I can also give the link if you guys care to tell me if you also have this problem using other browser than Chrome and what should I do to fix it: https://www.sorident.ro (If links are not allowed I'll remove it)
I've tried everything I could think of, but the problem is still there.
If you guys know the answer, I would appreciate it a lot. Thank you very much.

**Comment by davelab6** [comment]
Hi @SORIdent - apologies for not answering this sooner. I'm surprised they would be jagged on Safari (assuming you tested on Mac OS X) or any other OS X browser. The way you load the fonts also won't effect this. The issue is that the fonts don't have good hinting for Windows at the moment, and in the future this will be improved :) However I can't give a specific date for that just yet.
