### ISSUE TITLE
Nunito Sans long vowels issue

### ISSUE THREAD

**Issue by MSKTRS** [google/fonts#1297]
Hi!

The accents of capital letter **'Ő'** (unicode: 0150) and **'Ű'** (unicode: 0170) seem like would be too close to each other in case of styles Regular / Semi-Bold / Bold. This makes 'Ő' and 'Ű' look like 'Ó' and 'Ú' in certain cases.
Could you please fix the issue? Approximately how much time will it take to process this request?

Thank You in Advance!
![nunito-sans-font](https://user-images.githubusercontent.com/33322031/32330538-b12ddfb2-bfe0-11e7-9df3-d43a6f81e8a4.png)

**Comment by Fonthausen** [comment]
@davelab6 Do you know when this might be solved ? Some designers have reached me through Facebook and asked me about it.

**Comment by davelab6** [comment]
@alexeiva could you fix this as part of the current Cyrillic work? :)

**Comment by alexeiva** [comment]
it looks like @m4rc1e has fixed the issue in `2.002 in
 `https://github.com/m4rc1e/NunitoSans/commit/1f035bd0ec3cf0314875d0ccdc327a066647277b
but the update has not yet been pushed. 

![webp net-gifmaker](https://user-images.githubusercontent.com/16634089/33181598-38861470-d08a-11e7-8c34-be34fddb77e5.gif)

**Comment by davelab6** [comment]
Great! So we'll push this with the Cyrillic next week

**Comment by MSKTRS** [comment]
Could you guys please check if is it updated also on Google Fonts? @davelab6 @Fonthausen 
Just taken this screenshot on Google Font:
![image](https://user-images.githubusercontent.com/33322031/33487775-aa3af444-d6ae-11e7-9b75-1cac247365ed.png)

Thanks in advance!

**Comment by alexeiva** [comment]
This will be pushed as part a combined update that affects Nunito Sans and
Nunito. At the moment the Nunito part is being worked on (Cyrillic
expansion). After that cross-family hinting issues would be addressed and
then pushed. Thus a longer wait.

1 дек. 2017 г. 6:46 ПП пользователь "MSKTRS" <notifications@github.com>
написал:

Could you guys please check if is it updated also on Google Fonts? @davelab6
<https://github.com/davelab6> @Fonthausen <https://github.com/fonthausen>
Just taken this screenshot on Google Font:
[image: image]
<https://user-images.githubusercontent.com/33322031/33487775-aa3af444-d6ae-11e7-9b75-1cac247365ed.png>

Thanks in advance!

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/google/fonts/issues/1297#issuecomment-348512689>, or mute
the thread

**Comment by MSKTRS** [comment]
Hi guys! 
Unfortunately we still don't see the update on Google fonts and our product using Nunito Sans will be launched very shortly (within 2 weeks). Can you please check the current status and give us an update? Is it possible to only address this issue now and the Cyrillic expansion later?
Thank you very much in advance!

**Comment by alexeiva** [comment]
Cyrillic development is complete now in which this issue has also been addressed.

@MSKTRS Don't wait for the update to roll in, use the latest version and self-host:
https://github.com/m4rc1e/NunitoSans/tree/master/fonts

**Comment by MSKTRS** [comment]
Thank you for your response! We can use this, until the update is pushed on Google Fonts. Thanks again for your help!

**Comment by fitojb** [comment]
Just to remind you all, it’s now 2019 and the update that was ready in 2017 hasn’t been pushed yet, so duplicates like #1866 happen.

**Comment by davelab6** [comment]
Looks fixed :)

<img width="640" alt="Screen Shot 2020-06-16 at 12 51 24 PM" src="https://user-images.githubusercontent.com/261579/84803514-1b0b3880-afd0-11ea-82b9-93e71fbfd98a.png">

**Comment by istvanjkb** [comment]
`Semi-bold`, `bold` and `Regular` are still unfixed.

**Comment by markszenteTB** [comment]
Hi @davelab6, shouldn't this issue be reopened? As @istvanjkb said, `semi-bold`, `bold` and, perhaps most importantly, `regular` are still not fixed.
