### ISSUE TITLE
Montserrat "G"

### ISSUE THREAD

**Issue by nodnarb1129** [google/fonts#1402]
I like everything with the Montserrat font except the capital G. Am I able to change just the G and use it? Would that infringe upon... something..? Or, what's the best way to go about doing that? Haha. I just want a better looking G :)

**Comment by EwonRael** [comment]
Hey!
Because Montserrat is licensed under the SIL open font license you can modify it without infringing upon anything. Some of the older fonts around here still prohibit making a font with the same name so if you have any intention of redistribution choose a different name.

Just for reference https://github.com/JulietaUla/Montserrat is the official repository for this font. Which might be a better place for this kind of question. You may even recommend them add an alternative glyph. 

Best way to go about modifying it is really up to you. I would use http://fontforge.github.io personally.

**Comment by nodnarb1129** [comment]
You are awesome. Thank you! Everything I needed right there. Clear and concise.
