### ISSUE TITLE
Directory > Show full glyph set

### ISSUE THREAD

**Issue by DanielRuf** [google/fonts#1411]
It seems there are also french glyphs but they are not shown on https://fonts.google.com/specimen/Rubik

**Comment by fitojb** [comment]
I don’t think a _preview_ is intended to show absolutely every single glyph—it’s a sample, not a full specimen. Besides, strictly speaking, there is no such thing as “French glyphs”: the characters used in the French alphabet are also shared by other Latin-based alphabets. Every font that complies with the [Google Latin Core character set](https://github.com/googlefonts/tools/blob/master/encodings/GF%20Glyph%20Sets/GF-latin-core_unique-glyphs.nam) will support French. And there’s a text box below where you can input any text you like to preview the characters you want.

**Comment by DanielRuf** [comment]
So far the specimen only show what is described. Latin, Hebrew, Cyrillic. But there is no mention of French. But when inspected in Photoshop there are clearly the French letters / specimen included.

The Google fonts website is unclear.

**Comment by DanielRuf** [comment]
> it’s a sample, not a full specimen

That was not quite clear as there is no mention or info about. Also the country overview does not make clear that French is supported.

**Comment by sladen** [comment]
@DanielRuf, there's certainly a couple of ideas here, lets try to refine them input implementable suggestions:
> Latin, Hebrew, Cyrillic. But there is no mention of French. … Also the country overview does not make clear that French is supported.

Yes, there is perhaps a possibility to present which languages, or region-specific variants are covered.  Perhaps along with additional hints about the number of speakers/readers of that language as an additional guide.

*(An important detail also highlighted from the two sentences quoted here are *(French) as a language*, vs. a region-/country-overview.  ie. `fr` vs. `fr_FR`)*.

> it’s a sample, not a full specimen

Could could also be highlighted in a different way, perhaps `showing $X% of characters in font [Show more]`, so make it more clear that it is a partial sample, and the user has a clear journey to discover (display) more of what is available.

**Comment by DanielRuf** [comment]
> Could could also be highlighted in a different way, perhaps showing $X% of characters in font [Show more], so make it more clear that it is a partial sample, and the user has a clear journey to discover (display) more of what is available.

Definitely. It makes more sense to make clear that it is just an excerpt and not the full table of glyphs and there should be link to all glyphs if possible.

**Comment by DanielRuf** [comment]
`Characters` like a colleague says is misinterpreted here and reads like it means that these are all available characters.

**Comment by sladen** [comment]
@DanielRuf, would like to fully understand; Could you clarify and expand, with some additional context?  (ie. this about the present wording, or a proposed change—if so what would be a better wording?)

**Comment by sladen** [comment]
Ideally this presentation of coverage/usefullness needs to remain user-centric and meaningful.
* `*Good match*.  This font will work for 97% of web pages being marked as being `French`

Where the presentation of the number comes simply and mechanically from cross matching a corpus and codepoints/sequences used against the coverage deduced from the font.

**Comment by DanielRuf** [comment]
Here is the answer from my designer:

*  Due to the current Headline `Characters` the paragraph appears like "Hey look - here you can see all the available Characters.

Solution: 

1. Either *change Headline* into something that clarifies that it is only an excerpt like e.g. `main characters`. 
2. Or as already written above *add a link* which allows you to show really the whole glyph collection. 

Additional there is a pie chat, which *shows the countries where the font is used the most*. But *I can't find a paragraph which shows the supported languages* anywhere. So maybe it is possible to just add this new paragraph…

**Comment by davelab6** [comment]
This is an issue with the directory; currently there is no way to see the full glyph set of a font, and ideally that should convey how to access them all with OpenType features.

**Comment by kokoshneta** [comment]
Has anything changed with this over the past two years? I still can’t find any way to see full glyph sets for Google Fonts (short of downloading them and inspecting them in a font management application), which is – generally speaking – by far the largest drawback for me. Requiring the user to select and use a font in a test case scenario in order to see whether it even supports the language you’re working in is… somewhat less than user-friendly.

There is a rough guide in the “Customize” tab of the “Your selection” pop-up, which tells you broadly which ranges are supported by a font (Latin, Latin Extended, Cyrillic, Cyrillic Extended, Vietnamese, etc.), but that’s still rather limited and doesn’t tell you anything about OpenType features like small-caps, OSF and so on, so it’s not really a substitute.

**Comment by davelab6** [comment]
> Has anything changed with this over the past two years?

No. The catalog was updated in March 2020, but the Glyph Set section of the Specimen page template was not changed. We are aware that this can be improved. 

> I still can’t find any way to see full glyph sets for Google Fonts (short of downloading them and inspecting them in a font management application), which is – generally speaking – by far the largest drawback for me. Requiring the user to select and use a font in a test case scenario in order to see whether it even supports the language you’re working in is… somewhat less than user-friendly.

Understood. We found in our user experience research that seeing the full glyph set was something more sophisticated/advanced users (like yourself) wanted, and more casual users (the majority for us) preferred something very simple. 

> There is a rough guide in the “Customize” tab of the “Your selection” pop-up, which tells you broadly which ranges are supported by a font (Latin, Latin Extended, Cyrillic, Cyrillic Extended, Vietnamese, etc.), but that’s still rather limited and doesn’t tell you anything about OpenType features like small-caps, OSF and so on, so it’s not really a substitute.

Currently OpenType features are not supported in the GF API, but if they were included in the font by the designer, we keep them in the copy of the fonts included in the download ZIP.

Closing this issue is fine, we are are tracking Catalog UI feature requests internally.
