### ISSUE TITLE
Contribute to Google font

### ISSUE THREAD

**Issue by KrisKostova** [google/fonts#1535]
I'm designer of [Adys font](http://adysfont.com/about/), specially created for dyslexic reader in two weight - Regular and Bold, I would like to add this font to Google font library. 
About Adys: http://adysfont.com/about/
I remain open to design assistance, if there is need of any. 

All the best!

**Comment by davelab6** [comment]
Thanks for proposing this. I am curious if you have done any scientific studies to prove that this is effective. 

However, since the design is pleasing, I think it would be useful for simple graphic design, so I would be happy to add it! :)

But there are some requirements - detailed in https://github.com/google/fonts/blob/master/CONTRIBUTING.md - and the first is that your current license is not possible for me to accept. 

> This work is licensed under the Creative Commons Attribution-NoDerivatives 4.0 International License. To view a copy of this license, visit creativecommons.org/

Would you consider using the SIL Open Font License, with no Reserved Font Name?

**Comment by AliceWonderMiscreations** [comment]
First off, I really like the font.

With respect to science, I did some research a few years back when I needed to but I have forgotten much of what I found. But what I do remember -

A) Sans serif fonts are often preferred.
B) Comic Sans MS is a font many dyslexic choose on their own - but it is only available in one variant, upright roman.
C) The most important things seem to be easy to distinguish rm from m, and that things like q and p are not just mirrors, that l1 and 0O are easy to distinguish, etc.

It's been awhile since I researched good fonts for dyslexia and it frustrating when I did because fonts that had testing were extremely expensive because of the testing and also often had very restrictive licenses - yet dyslexic people I personally knew did not see a huge benefit to those overpriced fonts over many other sans-serif fonts (including comic sans ms) - the testing in their opinion was just marketing spin so they could charge more for it.

For the WebVTT captioning project I did, I ended up going with Cyntho Pro which was actually created for Crylic needs and not dyslexia - but it was liked by dyslexic people I did ask.

I would actually like to try this font though and see if it is even better, it seems to have some of the irregular character characteristics that comic sans ms has that apparently make it a favorite of many dyslexics.

But while I have forgotten many of the important font characteristics that I was suppose to look for when I did research it, one thing I do remember is that like autism, dyslexia is a broad spectrum and what is effective for some may not be for others. Thus there really isn't a scientific consensus, as there are many different types of dyslexia and different things help different people.

**Comment by laerm0** [comment]
BTW, [all research on fonts for dyslexia](http://bigelowandholmes.typepad.com/bigelow-holmes/dyslexia-typography/) is still pretty inconclusive.

**Comment by AliceWonderMiscreations** [comment]
I have a lot of respect for Bigelow and Holmes, thank you for the link. Interestingly, a dyslexic friend told me that a font familiar to her makes the biggest difference, so she ignores specified fonts whenever she can. I suspect dyslexia is a spectrum without any one solution that is best for all.

**Comment by Santosh-Gupta** [comment]
The font is very effective for me.

**Comment by tphinney** [comment]
@KrisKostova it's been almost five years! Any interest in offering it under the Open Font License so Google can take it? See the post from Dave Crossland (davelab6) above.

You can still ALSO offer it under another license, but Google needs OFL.

**Comment by RosaWagner** [comment]
Closing this request until license issue resolved.
