### ISSUE TITLE
Add Boring Boring cursive font

### ISSUE THREAD

**Issue by benmully** [google/fonts#1536]
We really really need this font added, as we are a new G Suite for Education user, and we use this cursive font to teach all our Early Years students how to form the cursive writing - https://www.urbanfonts.com/fonts/Boring_Boring.htm

Considering G Suite for Education is supposed used by thousands of schools, I'm very surprised that no one has added one up to now!!

[BORING.zip](https://github.com/google/fonts/files/1919221/BORING.zip)

**Comment by fitojb** [comment]
@benmully This repository only contains freely-licensed, open-source typefaces. What is the license for the "Boring Boring" font?

**Comment by m4rc1e** [comment]
It may appear free but I can't find any license info.

Slightly off topic. Do thousands of schools really use this as a hand writing reference? it looks incredibly inefficient. I remember being taught the Palmer Method in SA, then Ball and Stick in the UK.

**Comment by benmully** [comment]
I'm an IT guy, but I have been told this is how they form letters in Early Years

**Comment by benmully** [comment]
Am I in the right place to get it added? Everywhere I find the font its listed as free eg. https://www.wfonts.com/font/boring-boring & http://www.fontpalace.com/font-details/Boring+Boring/

Even on the creators website they say free - http://www.gwydir.demon.co.uk/giles/

**Comment by sladen** [comment]
@edkins, would you be willing to make a clearer statement on licensing for the Blahfonts?  (Ideally under an existing widely-used font licence?).

At the moment the web page contains a number of statements "You cannot sell them, but you can copy them and use them as much as you want." rather than a definite licence.  For Libre fonts usage and shipping via Google Fonts, they need to be modifiable (fixable) not just distributable as-is.

**Comment by benmully** [comment]
Any help please?! We really need this font!

**Comment by davelab6** [comment]
This need will be met by the upcoming Playwrite fonts, see https://primarium.info/ to learn more
