### ISSUE TITLE
[Variable Fonts] More than 9 instances

### ISSUE THREAD

**Issue by mjlagattuta** [google/fonts#1609]
For families with more than 9 weights they would typically ship as multiple families in the case of static fonts. How does this translate to a variable font?

Should there be a stripped down version of the variable font for serving the canonical Thin–Black on fonts.google.com, and a full version (with extra styles like Hairline or Ultra) available on Github?

**Comment by davelab6** [comment]
Good question! 

https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_wght says

> Valid numeric range: Values must be in the range 1 to 1000.

So, I believe that if the Named Instances that correspond to the legacy non-variable fonts are in the font on the registered `Weight` (`WGHT`) axis as 100, 200, ... 900, then because the axis can be 1 to 1000, you can have the legacy sibling family fonts also as Named Instances on that axis too, and there's no need for a stripped down version, as long as they can fall on that axis at appropriate values. 

@rsheeter @garretrieger @nyshadhr9

**Comment by rsheeter** [comment]
Thanks for reaching out. I do not expect we will limit the range of axes like this. Closing, but feel free to ping if you have further questions.
