### ISSUE TITLE
how do i create my own freakin font

### ISSUE THREAD

**Issue by McShirtz** [google/fonts#1686]
gimme an answer now i got some stuff ready to download

**Comment by AeolienFS** [comment]
I suppose I work the points that Marc mentioned above, just in a strange sequence? I've been making fonts for a few years, as a hobby, and when Marc says "sketch a lot" and "practice": he's not joking. Those are steps one takes again and again, possibly for every font because every font will be new and require discovery, development, research, to get the best form possible.

I tend to sketch first, then look at the flow of what I designed to get the feel of the visual texture, what the lines convey, if there are glyphs that have a different feel from the others. I might think of historic or art styles or aspects of the environment that somehow echo the shapes I designed; I try to imagine which one(s) my font might complement were I to use it for adding a poignant description to a suitable image. 
I sometimes photocopy the glyphs I sketched, cutting them out to lay over an image I think suits the font. For art fonts I find the latter process ideal to 'polish' outlines, find discrepancies within lines, sizes, shapes etc. and to see a font's limitations/usefulness.
Only then will I use an editor to see if my idea will make a font I'd buy if I needed it for a project. I think the long preparation time is necessary on occasion : I use time, energy, thought to create a font and it has to be a valid 'entity' by taking shape and life in a font editor. Like Marc says "rinse and repeat", that's necessary for every font, until "something sticks" and your font performs how you envisaged it.  

Only after completing much of the first Latin set do I look at typography books, font collections, designer biographies, catalogues, read books that use 'special' fonts etc : close to finishing the inital glyph band I wouldn't want to be influenced by ideas others published earlier as I might be tempted to change that which I wanted to make (that's one rabbit hole I fear ) But I do want to be guided into adjusting the logic of lines and glyphs and how the words present on a page of text.

Another rabbit hole for me is thinking that I've finished a basic font for the languages I have to cover. Yes, even after a few interesting fonts over a few years of learning and working I still see that rabbit hole for every font.
Because using a font shows areas that are less expressive than the rest or glyphs that make a text stumble or even when a glyph's line doesn't fit the overall look of the glyph shape and the flow of the font. Those problems mean that the font isn't finished regarding the various shapes, individual edges, it hasn't found independence.

My system can take up quite some time but I tend to be happy with my creations when I publish them  -- and I know that despite niggles which might take a while to emerge I have developed a solid thought structure for each font to allow me to correct any problematic aspects without losing my passion, confidence and goal.

Sorry this was a long post, I wanted to explain one of the techniques that can help when designing fonts. I'm sure everybody has their own system but the steps Marc mentioned are the basics from which you can quite easily develop the approach that helps you.
