### ISSUE TITLE
Stroke width irregularity for Poppins

### ISSUE THREAD

**Issue by majtom2grndctrl** [google/fonts#1774]
I’ve noticed some stroke widths rendering less evenly on Poppins over the Google Fonts API than when served over Adobe Fonts, or when rendered with a locally installed copy. The most noticeable issue is the horizontal stroke on the lowercase 'e' glyph is thinner than the rest of the glyph. However, it also appears that the round strokes on b, d, p, and q appear to have stronger optical corrections to their widths than when served elsewhere.

Sample from Google Fonts:
<img width="344" alt="screen shot 2018-12-04 at 10 09 38 am" src="https://user-images.githubusercontent.com/447769/49465970-baccf100-f7b3-11e8-91ac-244a37ca19b9.png">

Sample from Adobe Fonts:
<img width="493" alt="screen shot 2018-12-04 at 10 10 05 am" src="https://user-images.githubusercontent.com/447769/49466226-5c544280-f7b4-11e8-975b-ff6bd22fe9b9.png">

**Comment by laerm0** [comment]
Hmm, looks like hinting, but I'll have to confirm. Thanks @majtom2grndctrl .

**Comment by laerm0** [comment]
Hi @majtom2grndctrl. The solution here is that we need to update our files from the source as they have been changed. I'm afraid I can't offer a timeframe on that, but thanks for pointing it out.

**Comment by aaronang** [comment]
This issue is still happening for me. When I use Figma to collaborate with other people, their Poppins is rendering the crossbar of the "e" character very thinly. When I click on the text object, it renders to a thicker crossbar for the "e" character. What is causing this issue? How can we solve this problem?

I can work on this problem if someone can provide some guidance.

**Comment by m4rc1e** [comment]
I've never used Figma so I don't know how font loading works in their app.

I'd first check if you/other members have an older version installed locally. If you all have the latest installed, perhaps Figma has cached the older version?

**Comment by davelab6** [comment]
The next update to Poppins will fix this

**Comment by aaronang** [comment]
@davelab6 Could you explain the problem to me? I would love to know what is causing this.

Thank you all for your work 🙏

**Comment by rahulgajjar** [comment]
> This issue is still happening for me. When I use Figma to collaborate with other people, their Poppins is rendering the crossbar of the "e" character very thinly. When I click on the text object, it renders to a thicker crossbar for the "e" character. What is causing this issue? How can we solve this problem?
> 
> I can work on this problem if someone can provide some guidance.
> 
> @lianghai @rahulgajjar Do you have any idea how to solve this problem?

Hi Aaron Ang,

The issue with the letters like 'e' has been solved by ITF since a long time ago. It had been requested to google fonts to update the fonts to the latest version. But, somehow the google fonts never updated the Poppins font. I request you to download the latest font from the Indian Type Foundry repository. There is also a variable font version as well if you wish to experiment with it. 

OTF and TTF: https://github.com/itfoundry/Poppins/tree/master/products
Variable font: https://github.com/itfoundry/Poppins/tree/master/variable

**Comment by m4rc1e** [comment]
> The next update to Poppins will fix this

This was solved when we pushed the hotfix a few weeks back

<img width="408" alt="Screenshot 2020-07-28 at 11 47 45" src="https://user-images.githubusercontent.com/7525512/88656416-2cb02780-d0c8-11ea-87e5-7e87de34bfc8.png">

Problem is the user is either using an older version or Figma has cached the older version.

**Comment by majtom2grndctrl** [comment]
Any reason not to mark this issue as closed? I am satisfied that the issue has been resolved.
