### ISSUE TITLE
Add Blinker

### ISSUE THREAD

**Issue by supertype-de** [google/fonts#1831]
We'd like to add Blinker to google fonts. Sources and TTFs can be found here:
https://github.com/supertype-de/Blinker

Blinker is a low contrast sans serif typeface with a *squircle* as its basic shape, think squarish curves, or Eurostyle’s flamboyant cousin. It’s best used for medium to large text, rather than a long copy. To do its claim justice Blinker also comes with a headline weight with an extra large x-height, tight spacing, and glyphs drawn more narrowly. Blink!
The original 9 weights with a latin extended glyph set were designed by supertype’s Jürgen Huber in 2019.

**Comment by thundernixon** [comment]
Nice work on this! This font has a great style to it, and at first glance, looks like it might work well as a weight variable font.

It seems like the UFOs in the repo might be compiled, rather than the true sourcefiles – just based on the fact that no overlaps are present, and that there is a UFO for every weight here. In order to onboard fonts to the GF directory (and especially to build a variable font from them), it's necessary to have source files.

If you did have a few master sources (either master UFOs or a Glyphs file), would it be possible to add that to the repo? Alternatively, was this family drawn without interpolation?

**Comment by supertype-de** [comment]
@thundernixon , thanks.
Yes, the family is interpolated using 4 Masters (Thin, Regular, Bold, Black). The Headline is a separate stand-alone weight. 
The original UFOs contain PS outlines (of course). When convert to TT outlines during font generation we get very poor conversion results on many curves. We have therefore converted the PS outlines to TT curves prior to font generation. This gives us more control i.e. better quality results but it also leaves us with certain incompatibilities for we can not keep the same number of nodes in all masters. It would be a considerable effort to make all TT outlines compatible again. Would you want to help with that?

**Comment by supertype-de** [comment]
The curves are not the issue (we’ve been designing typefaces for more than 25 years) but the conversion, at least when you want to keep the PS point structure intact. We can go back a step and turn the PS into TT without decomposing and/or removing overlap then checking outline compatibility, making them variable-ready this way.

**Comment by supertype-de** [comment]
Hi @thundernixon , thanks for your encouragement. We’ve uploaded the PS source files as `.ufo`, the `.designspace` file and some specimen images. If this would help to get things off the ground that would be super.

**Comment by thundernixon** [comment]
Great! I can't say anything about timelines, but the source files being
there are one necessary qualification for a family being on the registry.
I've labeled it to show that it has weight VF potential, and that might
help out. Thanks for sharing your work!
-- 
——

Stephen Nixon

www.thundernixon.com

**Comment by supertype-de** [comment]
We too have noticed that working with quadtratics is not uncomfortabel in RoboFont. Multiple extensions still expect PS outlines, the curve type I grew up with :)
I just tried fontmake (´fontmake -o variable -m sources_ps/Blinker_15.designspace´) but it tripped over an alleged incompatibility (in the glyph ae) though the PS outlines interpolate without a problem.

**Comment by davelab6** [comment]
I get what you mean about "the curve you grow up with", there are many
subtleties in the act of drawing, that probably can't even be explained in
words. It seems that some aspects of any different curve may need to time
and practice to rediscover, and not everyone has the luxury of enough free
relaxed time to play with learning another way to get a very similar end
result. But, it seems there are some things quadratic curves can do when
interpolated that cubics can't do, or not as easily, and since our users
and readers will be experiencing non-hand-corrected interpolates curves, it
may be commercially beneficial to invest in moving away from cubics as the
default curve format; they might always have a place as a design time
option, like Spiro curves.

Anyway! :) If you just delete the incompatible glyphs to inspect the
quadratic output, is it still with an unacceptable quality?

**Comment by supertype-de** [comment]
@thundernixon , we got fontmake to generate a variable font from our ufo + designspace, both available in sources_ps. The directory fonts_ttf contains this variable font, the instances as separate ttf, as well as the stand-alone weight Blinker Headline.

**Comment by thundernixon** [comment]
@supertype-de Awesome! This one really shines as a variable font – the weight range is super nice.

![blinker-vf](https://user-images.githubusercontent.com/7355414/52742968-f7cd1500-2fa6-11e9-8010-1b66958c6a6b.gif)

I still have other work to get through, so I can't say when I (or someone else) could get to onboarding this, but I'll keep it on my radar as a good project once I've knocked out a few urgent things.

**Comment by supertype-de** [comment]
Newfishtacoburg would have also made a nice font name!
Next time!

Best 
Juergen

**Comment by supertype-de** [comment]
Hi @thundernixon , is there any news regarding the submission of our typeface Blinker?

**Comment by thundernixon** [comment]
Unfortunately, not on my end. I have been moved to a separate project, however, so I won't be able to help with this in the near term.

I've asked on a backchannel whether others might be able to help onboard it, as I think it'll make a really great addition to the library, and should be a pretty quick one to onboard. There is a pretty sizable backlog, though, and I'm not sure how far ahead this can skip.

**Comment by supertype-de** [comment]
Is there any further news?

**Comment by m4rc1e** [comment]
I'll try and take a look in the next two weeks. We now have the backlog ordered so we aim to tackle some of them. We may need your assistance in fixing any metadata.

**Comment by supertype-de** [comment]
@m4rc1e thanks for you feedback, much appreciated. Give us a sign, if you need any assistance.

**Comment by m4rc1e** [comment]
It's arrived https://fonts.google.com/specimen/Blinker

**Comment by supertype-de** [comment]
Hi Marc,

thanks for the info! Super awesome!

Just one more question: Will the Blinker Headline
weight also be released soon?

Best
Jürgen

**Comment by supertype-de** [comment]
Hi Marc,

did you get our last email? 

Thanks
J

**Comment by thundernixon** [comment]
Marc is on vacation, so he probably isn't checking email right now. I think he'll be back soon.

Overall, I think that because blinker headline is not in the same variable font (correct me if that's wrong), it will need to be shared PRed, and will show as a separate family in the directory.
