### ISSUE TITLE
Add Bodoni by Indestructible Type

### ISSUE THREAD

**Issue by m4rc1e** [google/fonts#1848]
https://github.com/indestructible-type/Bodoni

Production notes from Rosa:
- [x] Contact designer about this
- [x] Correct sources (upright)
- [x] Correct sources (italic)
- [x] Re-make build system
- [x] Package

**Comment by EwonRael** [comment]
Hi!

The [Bodoni Moda](https://github.com/indestructible-type/Bodoni/tree/google) branch of Bodoni* is currently passing all fontbakery checks for the static builds of the font. However it still throws up an error for the variable font version.

This is due to naming conventions. Right now the typeface has different versions for various point sizes. These are considered different font families in the static builds, but should all be incorporated as one for the variable. As it stands they are stylename mapped to "11 Regular", "72 Bold" etc., with the point size appearing as a number before the weight.

This causes fontbakery to have an issue as "72 Bold" isn't an expected stylename. Understandable, but I can't think of a suitable solution.

What should we do about this?

**Comment by m4rc1e** [comment]
@EwonRael we've recently changed our instance naming policy, https://github.com/googlefonts/gf-docs/tree/master/Spec#fvar-instances.

We don't allow any particles other than weight and italic to be included in instance names. However, we expect these styles should be included in a STAT table.

Read the docs and if it still remains unclear, open an issue and we'll improve the docs.

**Comment by davelab6** [comment]
The family name can't just be Bodoni, it needs to be Bodoni Moda

**Comment by EwonRael** [comment]
okay so the Bodoni Moda branch now static+variable fonts that pass all fontbakery tests and should conform to the instance naming/STAT policy.

Don't worry @davelab6 as long as we're pulling from the [google branch](https://github.com/indestructible-type/Bodoni/tree/google) or using the build-GF.sh script the family name is "Bodoni Moda"

Let me know how things look

**Comment by EwonRael** [comment]
I'm thinking everything is good on my end to push to GF? Let me know if I'm mistaken about this or if there's something more I should be doing?

**Comment by davelab6** [comment]
> Don't worry @davelab6 as long as we're pulling from the google branch or using the build-GF.sh script the family name is "Bodoni Moda"

Why isn't the full project called Bodoni Moda?

**Comment by EwonRael** [comment]
should I make a separate repo for Bodoni Moda naming convention?
