### ISSUE TITLE
Add RetroTV

### ISSUE THREAD

**Issue by Bry10022** [google/fonts#1874]
…

**Comment by m4rc1e** [comment]
Please create a github repository for this family. The repo should also contain the source files.

**Comment by felipesanches** [comment]
@bmeyerholt1, the repo should ideally have the plain files instead of a ZIP. Also, I opened the zip and noticed that it only has got the OFL license and the TTF binaries. Please also publish the original project files. This would likely be `*.glyphs` files if you created the font project on GlyphsApp. But it can have some other filename/extension if you used other font editors. That's what @m4rc1e was referring to when he said "source files".

**Comment by bmeyerholt1** [comment]
The source files should now be there…

**Comment by felipesanches** [comment]
It is nice that you unzipped the files, but we still only have TTFs there, but no corresponding sources.

Which program did you use to create the fonts?

**Comment by bmeyerholt1** [comment]
@felipesanches FontForge, the free and open source font editor.

**Comment by laerm0** [comment]
@bmeyerholt1 ping, we will still need sources :)

**Comment by cheznewa** [comment]
EN ::: I Am Really Disappointed With @Bry10022 Why Did He Delete The RetroTV Font? Disappointed With Google Fonts For Its Refusal Or An X/Y Reason? This Font Is Well Done, Designed For Old TV With Teletext (Replacing EuropeanTeletext), Not In The Know Who To Provide The Source Code To

FR ::: Je Suis Vraiment Décu De @Bry10022 Pourquoi A T'il Supprimé La Police D'ecriture RetroTV ? Deçu De Google Fonts Ou Une Raison X/Y ? Ca Police D'ecriture Est Bien Faite, COncu Pour Les Ancienne Télé Avec Son Télétexte (En Remplacent EuropeanTeletext), Apèrs Pas Au Courant Qui Faut Fournir Le Code Source
