### ISSUE TITLE
Correct vietnamese subset

### ISSUE THREAD

**Issue by davelab6** [google/fonts#189]
Related to #135, per https://bugs.launchpad.net/ubuntu-font-family/+bug/656690 it seems our Vietnamese subset - https://github.com/google/fonts/blob/master/tools/encodings/vietnamese_unique-glyphs.nam - excludes `Ỳ ỳ Ỵ ỵ Ỷ ỷ Ỹ ỹ` which are needed. 

The old `googlefontdirectory/tools/subset/subset.py` had

    range(0x1ea0, 0x1ef2) + [0x20ab]

@sladen noted that this cuts off at U+1EF1 inclusive ('ự') but should be U+1EF9 ('ỹ') or in in Python N-1 range notation: `

    range(0x1ea0, 0x1efa) + [0x20ab]`

**Comment by rsheeter** [comment]
How severe is the problem? - specifically wondering how soon we'd want to recut existing fonts that publish vietnamese.

**Comment by davelab6** [comment]
I think in Q1 would be good, since its part of improving support for the next billion users' languages

**Comment by jameswilson** [comment]
Unfortunately, this didn't get done in time for TripAdvisor.  We ended up having to self host a vietnamese subset, due to missing glyphs.  I incorrectly filed my bug on the Source Sans Pro issue queue, and you can see my notes in a few places on my investigations:

https://github.com/adobe-fonts/source-sans-pro/issues/90

http://stackoverflow.com/questions/37579692/unicode-range-for-vietnamese

http://codepen.io/jameswilson/pen/ZWgMaa

I narrowed the problem in most of the cases down to "composed" glyphs where a latin vowel character like "a" was getting composed with a ghost character, to form what visually looks like a single character on the page.  Using the glyph ranges I posted on my last comment on [this comment](https://github.com/adobe-fonts/source-sans-pro/issues/90#issuecomment-225993022), I created a custom webfont subset, that solved the issues for me.
