### ISSUE TITLE
Add Public Sans

### ISSUE THREAD

**Issue by davelab6** [google/fonts#1923]
https://github.com/uswds/public-sans

**Comment by eliheuer** [comment]
Both Roman and Italic build with fontmake, I might start a draft PR just to get things moving.

**Comment by thisisdano** [comment]
Thanks for getting this started. Let me know what you might need from our side. I'm unfamiliar with this process — can you point me to any relevant documentation?

**Comment by caiotarifa** [comment]
Extremely relevant, I'd like to use this font in a site AMP-based.

**Comment by eliheuer** [comment]
@thisisdano 

The fonts need to build with [fontmake](https://github.com/googlei18n/fontmake) (not exported from Glyphs) and then they need to pass the quality assurance tests suite known as [Font Bakery](https://github.com/googlefonts/fontbakery).

After that, there is a walkthrough for making a Pull Request to Google Fonts here: https://github.com/googlefonts/gf-docs/tree/master/MakingPullRequestsToGF

Font bakery produces a markdown report that can be submitted with the pull request. Since it seems like this is an active project, let's start making PRs to https://github.com/uswds/public-sans to fix whatever Font Bakery issues come up.

Thanks!

**Comment by eliheuer** [comment]
@thisisdano Here is the Font Bakery report for the Roman variable font:

## Fontbakery report

Fontbakery version: 0.7.2

<details>
<summary><b>[3] Family checks</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Check font has a license.</summary>

* [com.google.fonts/check/family/has_license](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/family/has_license)
* 🔥 **FAIL** No license file was found. Please add an OFL.txt or a LICENSE.txt file. If you are running fontbakery on a Google Fonts upstream repo, which is fine, just make sure there is a temporary license file in the same folder. [code: no-license]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Check that METADATA.pb family values are all the same.</summary>

* [com.google.fonts/check/metadata/familyname](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/metadata/familyname)
* 🔥 **FAIL** METADATA.pb: Family name is not the same in all metadata "fonts" items.

</details>
<details>
<summary>⚠ <b>WARN:</b> METADATA.pb: Fontfamily is listed on Google Fonts API?</summary>

* [com.google.fonts/check/metadata/listed_on_gfonts](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/metadata/listed_on_gfonts)
* ⚠ **WARN** Family not found via Google Fonts API.

</details>
<br>
</details>
<details>
<summary><b>[18] PublicSans.wght.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Checking file is named canonically.</summary>

* [com.google.fonts/check/canonical_filename](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/canonical_filename)
* 🔥 **FAIL** Please change the font filename to use one of the following valid suffixes for variable fonts: VF, Italic-VF, Roman-VF

</details>
<details>
<summary>🔥 <b>FAIL:</b> Is 'gasp' table set to optimize rendering?</summary>

* [com.google.fonts/check/gasp](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/gasp)
* 🔥 **FAIL** Font is missing the 'gasp' table. Try exporting the font with autohinting enabled.

</details>
<details>
<summary>🔥 <b>FAIL:</b> Checks METADATA.pb font.post_script_name matches postscript name declared on the name table.</summary>

* [com.google.fonts/check/metadata/nameid/post_script_name](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/metadata/nameid/post_script_name)
* 🔥 **FAIL** Unmatched postscript name in font: TTF has "PublicSans-Light" while METADATA.pb has "PublicSans-Regular". [code: mismatch]

</details>
<details>
<summary>🔥 <b>FAIL:</b> METADATA.pb font.full_name value matches fullname declared on the name table?</summary>

* [com.google.fonts/check/metadata/nameid/full_name](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/metadata/nameid/full_name)
* 🔥 **FAIL** Unmatched fullname in font: TTF has "Public Sans Light" while METADATA.pb has "Public Sans Regular". [code: mismatch]

</details>
<details>
<summary>🔥 <b>FAIL:</b> METADATA.pb font.post_script_name field contains font name in right format?</summary>

* [com.google.fonts/check/metadata/valid_post_script_name_values](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/metadata/valid_post_script_name_values)
* 🔥 **FAIL** METADATA.pb postScriptName ("PublicSans-Regular") does not match correct font name format ("Public Sans Light").

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in METADATA.pb</summary>

* [com.google.fonts/check/metadata/valid_copyright](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/metadata/valid_copyright)
* 🔥 **FAIL** METADATA.pb: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2019 The Public San Authors (https://github.com/uswds/public-sans)'

</details>
<details>
<summary>🔥 <b>FAIL:</b> METADATA.pb: Filename is set canonically?</summary>

* [com.google.fonts/check/metadata/canonical_filename](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/metadata/canonical_filename)
* 🔥 **FAIL** METADATA.pb: filename field ("PublicSans.wght.ttf") does not match canonical name "PublicSans-Roman-VF.ttf".

</details>
<details>
<summary>🔥 <b>FAIL:</b> METADATA.pb font.name and font.full_name fields match the values declared on the name table?</summary>

* [com.google.fonts/check/metadata/nameid/family_and_full_names](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/metadata/nameid/family_and_full_names)
* 🔥 **FAIL** METADATA.pb: Fullname ("Public Sans Regular") does not match name table entry "Public Sans Light" ! [code: fullname-mismatch]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Font enables smart dropout control in "prep" table instructions?</summary>

* [com.google.fonts/check/smart_dropout](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/smart_dropout)
* 🔥 **FAIL** 'prep' table does not contain TrueType  instructions enabling smart dropout control. To fix, export the font with autohinting enabled, or run ttfautohint on the font, or run the  `gftools fix-nonhinting` script.

</details>
<details>
<summary>🔥 <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent.</summary>

* [com.google.fonts/check/family/win_ascent_and_descent](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/family/win_ascent_and_descent)
* 🔥 **FAIL** OS/2.usWinDescent value should be equal or greater than 230, but got 220 instead [code: descent]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Checking OS/2 Metrics match hhea Metrics.</summary>

* [com.google.fonts/check/os2_metrics_match_hhea](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/os2_metrics_match_hhea)
* 🔥 **FAIL** OS/2 sTypoAscender and hhea ascent must be equal. [code: ascender]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Does the font have a DSIG table?</summary>

* [com.google.fonts/check/dsig](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/dsig)
* 🔥 **FAIL** This font lacks a digital signature (DSIG table). Some applications may require one (even if only a dummy placeholder) in order to work properly.

</details>
<details>
<summary>🔥 <b>FAIL:</b> Whitespace and non-breaking space have the same width?</summary>

* [com.google.fonts/check/whitespace_widths](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/whitespace_widths)
* 🔥 **FAIL** Whitespace and non-breaking space have differing width: Whitespace (space) is 254 font units wide, non-breaking space (uni00A0) is 223 font units wide. Both should be positive and the same.

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking OS/2 achVendID.</summary>

* [com.google.fonts/check/vendor_id](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/vendor_id)
* ⚠ **WARN** OS/2 VendorID value 'IMPA' is not a known registered id. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: unknown]

</details>
<details>
<summary>⚠ <b>WARN:</b> Stricter unitsPerEm criteria for Google Fonts. </summary>

* [com.google.fonts/check/unitsperem_strict](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/unitsperem_strict)
* ⚠ **WARN** Even though unitsPerEm (1000) in this font is reasonable. It is strongly advised to consider changing it to 2000, since it will likely improve the quality of Variable Fonts by avoiding excessive rounding of coordinates on interpolations.

</details>
<details>
<summary>⚠ <b>WARN:</b> Are there caret positions declared for every ligature?</summary>

* [com.google.fonts/check/ligature_carets](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/ligature_carets)
* ⚠ **WARN** This font lacks caret position values for ligature glyphs on its GDEF table. [code: lacks-caret-pos]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/kerning_for_non_ligated_sequences)
* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + f
	- f + i
	- i + l
	- colon + f
	- f + l
	- l + a
	- a + g
	- g + two
	- two + colon
	- g + colon
	- colon + one
	- one + eight
	- eight + F
	- F + colon

   [code: lacks-kern-info]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check for points out of bounds.</summary>

* [com.google.fonts/check/points_out_of_bounds](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/points_out_of_bounds)
* ⚠ **WARN** The following glyphs have coordinates which are out of bounds:
[('zero.subs', 163.668, 291.057), ('zero.subs', 208.327, 291.057), ('zero.subs', 230.342, -176.29), ('zero.subs', 163.039, -176.29), ('zero.subs', 96.365, -176.29), ('zero.subs', 14.594999999999999, -62.441), ('zero.subs', 14.594999999999999, 55.18199999999999), ('zero.subs', 14.594999999999999, 135.065), ('zero.subs', 119.638, 291.057), ('one.subs', -1.2109999999999985, 221.83499999999998), ('one.subs', -1.2109999999999985, 242.59199999999998), ('one.subs', 120.186, 289.767), ('one.subs', 120.186, -165.0), ('two.subs', 13.934000000000001, 224.351), ('two.subs', 127.154, 296.057), ('two.subs', 155.459, 296.057), ('two.subs', 191.312, 296.057), ('two.subs', 289.436, -139.211), ('two.subs', 289.436, -165.0), ('three.subs', 138.412, 293.057), ('three.subs', 176.152, 293.057), ('three.subs', 220.182, 293.057), ('four.subs', 21.708, -33.53899999999999), ('four.subs', 21.708, -2.7179999999999893), ('five.subs', 344.498, 30.13499999999999), ('five.subs', 344.498, -18.926999999999992), ('five.subs', 344.498, -65.473), ('five.subs', 236.939, -174.29), ('five.subs', 191.022, -174.29), ('five.subs', 151.395, -174.29), ('six.subs', 189.086, 296.089), ('six.subs', 221.794, 296.089), ('six.subs', 318.031, 191.675), ('six.subs', 216.762, -171.258), ('six.subs', 170.845, -171.258), ('six.subs', 123.66999999999999, -171.258), ('six.subs', 12.966000000000001, -15.89500000000001), ('six.subs', 12.966000000000001, 57.69800000000001), ('six.subs', 12.966000000000001, 129.404), ('six.subs', 133.734, 296.089), ('seven.subs', 27.789, 289.767), ('seven.subs', 328.451, 289.767), ('seven.subs', 328.451, 264.607), ('seven.subs', 27.789, 264.607), ('nine.subs', 152.83, -171.258), ('nine.subs', 120.12200000000001, -171.258), ('nine.subs', 116.977, 296.089), ('nine.subs', 162.26500000000001, 296.089), ('nine.subs', 210.069, 296.089), ('nine.subs', 320.144, 140.726), ('nine.subs', 320.144, 67.13300000000001), ('nine.subs', 320.144, -3.9439999999999884), ('nine.subs', 208.182, -171.258), ('zero.dnom', 163.668, 456.057), ('zero.dnom', 208.327, 456.057), ('zero.dnom', 230.342, -11.29), ('zero.dnom', 163.039, -11.29), ('zero.dnom', 96.365, -11.29), ('zero.dnom', 14.594999999999999, 102.559), ('zero.dnom', 14.594999999999999, 220.182), ('zero.dnom', 14.594999999999999, 300.065), ('zero.dnom', 119.638, 456.057), ('one.dnom', -1.2109999999999985, 386.835), ('one.dnom', -1.2109999999999985, 407.592), ('one.dnom', 120.186, 454.767), ('one.dnom', 120.186, 0.0), ('two.dnom', 13.934000000000001, 389.351), ('two.dnom', 127.154, 461.057), ('two.dnom', 155.459, 461.057), ('two.dnom', 191.312, 461.057), ('two.dnom', 289.436, 25.789), ('two.dnom', 289.436, 0.0), ('three.dnom', 138.412, 458.057), ('three.dnom', 176.152, 458.057), ('three.dnom', 220.182, 458.057), ('four.dnom', 21.708, 131.461), ('four.dnom', 21.708, 162.282), ('five.dnom', 344.498, 195.135), ('five.dnom', 344.498, 146.073), ('five.dnom', 344.498, 99.527), ('five.dnom', 236.939, -9.29), ('five.dnom', 191.022, -9.29), ('five.dnom', 151.395, -9.29), ('six.dnom', 189.086, 461.089), ('six.dnom', 221.794, 461.089), ('six.dnom', 318.031, 356.675), ('six.dnom', 216.762, -6.258), ('six.dnom', 170.845, -6.258), ('six.dnom', 123.66999999999999, -6.258), ('six.dnom', 12.966000000000001, 149.105), ('six.dnom', 12.966000000000001, 222.698), ('six.dnom', 12.966000000000001, 294.404), ('six.dnom', 133.734, 461.089), ('seven.dnom', 27.789, 454.767), ('seven.dnom', 328.451, 454.767), ('seven.dnom', 328.451, 429.607), ('seven.dnom', 27.789, 429.607), ('nine.dnom', 152.83, -6.258), ('nine.dnom', 120.12200000000001, -6.258), ('nine.dnom', 116.977, 461.089), ('nine.dnom', 162.26500000000001, 461.089), ('nine.dnom', 210.069, 461.089), ('nine.dnom', 320.144, 305.726), ('nine.dnom', 320.144, 232.133), ('nine.dnom', 320.144, 161.056), ('nine.dnom', 208.182, -6.258), ('zero.numr', 163.668, 740.057), ('zero.numr', 208.327, 740.057), ('zero.numr', 230.342, 272.71), ('zero.numr', 163.039, 272.71), ('zero.numr', 96.365, 272.71), ('zero.numr', 14.594999999999999, 386.55899999999997), ('zero.numr', 14.594999999999999, 504.182), ('zero.numr', 14.594999999999999, 584.065), ('zero.numr', 119.638, 740.057), ('one.numr', -1.2109999999999985, 662.835), ('one.numr', -1.2109999999999985, 683.592), ('one.numr', 120.186, 730.767), ('one.numr', 120.186, 276.0), ('two.numr', 13.934000000000001, 668.351), ('two.numr', 127.154, 740.057), ('two.numr', 155.459, 740.057), ('two.numr', 191.312, 740.057), ('two.numr', 289.436, 304.789), ('two.numr', 289.436, 279.0), ('three.numr', 138.412, 740.057), ('three.numr', 176.152, 740.057), ('three.numr', 220.182, 740.057), ('four.numr', 21.708, 407.461), ('four.numr', 21.708, 438.28200000000004), ('five.numr', 344.498, 474.135), ('five.numr', 344.498, 425.073), ('five.numr', 344.498, 378.527), ('five.numr', 236.939, 269.71), ('five.numr', 191.022, 269.71), ('five.numr', 151.395, 269.71), ('six.numr', 189.086, 746.0889999999999), ('six.numr', 221.794, 746.0889999999999), ('six.numr', 318.031, 641.675), ('six.numr', 216.762, 278.742), ('six.numr', 170.845, 278.742), ('six.numr', 123.66999999999999, 278.742), ('six.numr', 12.966000000000001, 434.105), ('six.numr', 12.966000000000001, 507.698), ('six.numr', 12.966000000000001, 579.404), ('six.numr', 133.734, 746.0889999999999), ('seven.numr', 27.789, 729.767), ('seven.numr', 328.451, 729.767), ('seven.numr', 328.451, 704.607), ('seven.numr', 27.789, 704.607), ('nine.numr', 152.83, 278.742), ('nine.numr', 120.12200000000001, 278.742), ('nine.numr', 116.977, 746.0889999999999), ('nine.numr', 162.26500000000001, 746.0889999999999), ('nine.numr', 210.069, 746.0889999999999), ('nine.numr', 320.144, 590.726), ('nine.numr', 320.144, 517.133), ('nine.numr', 320.144, 446.05600000000004), ('nine.numr', 208.182, 278.742), ('uni2070', 163.668, 844.057), ('uni2070', 208.327, 844.057), ('uni2070', 230.342, 376.71), ('uni2070', 163.039, 376.71), ('uni2070', 96.365, 376.71), ('uni2070', 14.594999999999999, 490.55899999999997), ('uni2070', 14.594999999999999, 608.182), ('uni2070', 14.594999999999999, 688.065), ('uni2070', 119.638, 844.057), ('uni00B9', -1.2109999999999985, 766.835), ('uni00B9', -1.2109999999999985, 787.592), ('uni00B9', 120.186, 834.767), ('uni00B9', 120.186, 380.0), ('uni00B2', 13.934000000000001, 773.351), ('uni00B2', 127.154, 845.057), ('uni00B2', 155.459, 845.057), ('uni00B2', 191.312, 845.057), ('uni00B2', 289.436, 409.789), ('uni00B2', 289.436, 384.0), ('uni00B3', 138.412, 845.057), ('uni00B3', 176.152, 845.057), ('uni00B3', 220.182, 845.057), ('uni2074', 21.708, 511.461), ('uni2074', 21.708, 542.282), ('uni2075', 344.498, 578.135), ('uni2075', 344.498, 529.073), ('uni2075', 344.498, 482.527), ('uni2075', 236.939, 373.71), ('uni2075', 191.022, 373.71), ('uni2075', 151.395, 373.71), ('uni2076', 189.086, 851.0889999999999), ('uni2076', 221.794, 851.0889999999999), ('uni2076', 318.031, 746.675), ('uni2076', 216.762, 383.742), ('uni2076', 170.845, 383.742), ('uni2076', 123.66999999999999, 383.742), ('uni2076', 12.966000000000001, 539.105), ('uni2076', 12.966000000000001, 612.698), ('uni2076', 12.966000000000001, 684.404), ('uni2076', 133.734, 851.0889999999999), ('uni2077', 27.789, 834.767), ('uni2077', 328.451, 834.767), ('uni2077', 328.451, 809.607), ('uni2077', 27.789, 809.607), ('uni2079', 152.83, 383.742), ('uni2079', 120.12200000000001, 383.742), ('uni2079', 116.977, 851.0889999999999), ('uni2079', 162.26500000000001, 851.0889999999999), ('uni2079', 210.069, 851.0889999999999), ('uni2079', 320.144, 695.726), ('uni2079', 320.144, 622.133), ('uni2079', 320.144, 551.056), ('uni2079', 208.182, 383.742), ('onehalf', -1.2109999999999985, 662.835), ('onehalf', -1.2109999999999985, 683.592), ('onehalf', 818.4359999999999, 25.789), ('onehalf', 818.4359999999999, 0.0), ('uni2153', -1.2109999999999985, 662.835), ('uni2153', -1.2109999999999985, 683.592), ('uni2154', 13.934000000000001, 668.351), ('uni2154', 127.154, 740.057), ('uni2154', 155.459, 740.057), ('uni2154', 191.312, 740.057), ('onequarter', -1.2109999999999985, 662.835), ('onequarter', -1.2109999999999985, 683.592), ('threequarters', 138.412, 740.057), ('threequarters', 176.152, 740.057), ('threequarters', 220.182, 740.057), ('oneeighth', -1.2109999999999985, 662.835), ('oneeighth', -1.2109999999999985, 683.592), ('threeeighths', 138.412, 740.057), ('threeeighths', 176.152, 740.057), ('threeeighths', 220.182, 740.057), ('seveneighths', 27.789, 729.767), ('seveneighths', 27.789, 704.607), ('trademark', 3.75, 426.875), ('trademark', 3.75, 451.875), ('uni2120', 206.25, -6.25), ('uni2120', 175.625, -6.25), ('uni2120', 260.0, -6.25)]
This happens a lot when points are not extremes, which is usually bad. However, fixing this alert by adding points on extremes may do more harm than good, especially with italics, calligraphic-script, handwriting, rounded and other fonts. So it is common to ignore this message

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 15 | 6 | 41 | 6 | 85 |
| 0% | 10% | 4% | 27% | 4% | 56% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**

**Comment by eliheuer** [comment]
And I made a draft pull request here: https://github.com/google/fonts/pull/1932

**Comment by gyvrjoe** [comment]
I predict this typeface is going to see fairly widespread adoption as it fails nicely to system fonts (Roboto, San Francisco, Source) I'd dearly love for it to be available in Google apps.

**Comment by joe12south** [comment]
🦗🦗🦗

**Comment by franvelasco** [comment]
Is there any update? Can I help with anything?

**Comment by wouterds** [comment]
What's the status on this? Can't wait to start using this in my projects!

**Comment by m4rc1e** [comment]
Family is now in production https://fonts.google.com/specimen/Public+Sans. Enjoy,

**Comment by joe12south** [comment]
Woot!

**Comment by samlinville** [comment]
Hi! Is there any estimation of when this will appear in Google Apps?

**Comment by m4rc1e** [comment]
I'll see if we can get this into Sheets and Docs.

**Comment by stbojan** [comment]
Any update on adding it into Docs?

**Comment by maya** [comment]
@m4rc1e any update on getting it into Sheets and Docs?

**Comment by m4rc1e** [comment]
Hopefully next week.

**Comment by maya** [comment]
@m4rc1e noticed it wasn't added last week. Do you have an updated timeframe?

**Comment by m4rc1e** [comment]
https://fonts.google.com/specimen/Public+Sans

**Comment by maya** [comment]
@m4rc1e yes, am aware it's published to fonts.google.com (looks great!), though you [previously mentioned](https://github.com/google/fonts/issues/1923#issuecomment-554276020) planning to add it into Google Sheets and Google Docs apps and that's what my question was referring to. Can you clarify?

**Comment by stbojan** [comment]
@maya @m4rc1e High hopes for that feature over here too! :)

**Comment by m4rc1e** [comment]
I'll ask for the family to be pushed to docs today.

**Comment by m4rc1e** [comment]
Ok Public Sans should be available in Google Docs.
