### ISSUE TITLE
Open Sans font has wrong 'locl' for Romanian

### ISSUE THREAD

**Issue by davelab6** [google/fonts#213]
See https://groups.google.com/forum/#!topic/early-access-fonts/S6C6e8AweSk

**Comment by adipop** [comment]
The GSUB table must be eliminated or the substitutions should be reversed!
(all things here https://bugzilla.mozilla.org/show_bug.cgi?id=907793)
The glyphs S, s, T, t with cedillaaccent (Ş,ş,Ţ,ţ) must be substituted with S, s, T, t with commaaccent (Ș,ș, Ț, ț) for the Romanian language!
This affects all Romanian sites using Open Sans as well all the WordPress romanian sites on the Dashboard Admin side in any Romanian installation. It must be quickly fixed!

All the best!

**Comment by cristianadam** [comment]
It seems now Google Chrome also uses the 'locl' feature.  A screenshot of Google Chrome 31, where it worked fine, can be found here https://bugzilla.mozilla.org/show_bug.cgi?id=951141

The test page looks as bad on Google Chrome as it does on Mozilla Firefox:

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd"> 
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/> 
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300,400italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
<style type="text/css">
h1 {
	font-family: "Open Sans";
	font-size: 36px;
	font-weight: normal;	
	margin: 10px 0 20px 0;
}
</style>
</head>

<h1 lang="ro">&#354;&#355; &#350;&#351; (cedilla)</h1>
<h1 lang="ro">&#538;&#539; &#536;&#537; (comma) </h1>

</html>
```

**Comment by m4rc1e** [comment]
Issue still exists

**top: Roboto, bottom: Open Sans**
![screen shot 2017-06-08 at 15 53 47](https://user-images.githubusercontent.com/7525512/26934987-b7e3d95c-4c62-11e7-96e0-bfac334583de.png)

**Comment by buiestru** [comment]
Hello, the issue is extant and continues to spoil an otherwise excellent type family (for this particular localisation, of course).

Currently, the GSUB/'locl' lookup table looks like this:

Base Glyph Name | Replacement Glyph Name
------|-------
Scommaaccent (Ș) | Scedilla (Ş)
scommaaccent (ș) | scedilla (ş)
Tcommaaccent (Ț) | Tcedilla (Ţ)
tcommaaccent (ț) | tcedilla (ţ)

where comma variants are replaced with cedilla variants.

However, substitutions should be performed exactly the other way around:

Base Glyph Name | Replacement Glyph Name
------|-------
Scedilla (Ş) | Scommaaccent (Ș)
scedilla (ş) | scommaaccent (ș)
Tcedilla (Ţ) | Tcommaaccent (Ț)
tcedilla (ţ) | tcommaaccent (ț)

where non-Romanian lookalikes are replaced by proper Romanian glyphs.

It is especially frustrating that the 'locl' feature is active only in the presence of the HTML lang="ro" attribute. In other words, only standards compliant websites that care for SEO, accessibility (screen readers) etc. get the wrong glyphs.

I would argue for the removal of the 'locl' GSUB table, more precisely, for an empty 'locl' GSUB table. Given that glyph substitutions are, essentially, manipulating font rendering, what you see is not what you get.

**Comment by Jobava** [comment]
This bug has kept appearing in popular font suites and this has been plaguing Romanian for a long time (10+ years). Is there a chance to see a resolution to this soon?

**Comment by laerm0** [comment]
Hi all –

I've just done a thorough revitalization of Open Sans and fixed this. New files are not live yet but soon! Thanks for your patience.

<img width="275" alt="screen region 2017-12-12 at 11 46 18" src="https://user-images.githubusercontent.com/10780161/33897001-4e19ce9c-df32-11e7-963e-60dc8671a129.png">

**Comment by adipop** [comment]
Great news for romanians! Can't wait to go back to this font :)

All the best and Merry Christmas!
Adrian
​

**Comment by dale-cooper** [comment]
> Hi all –
> 
> I've just done a thorough revitalization of Open Sans and fixed this. New files are not live yet but soon! Thanks for your patience.
> 
> <img alt="screen region 2017-12-12 at 11 46 18" width="275" src="https://user-images.githubusercontent.com/10780161/33897001-4e19ce9c-df32-11e7-963e-60dc8671a129.png">

Hey, any new on that? I know it's been a long time but the issue is still open. Thanks!

**Comment by davelab6** [comment]
@m4rc1e has the latest VF made by @moyogo fixed this?

**Comment by moyogo** [comment]
The VF version and its static fonts have the fix, see https://github.com/googlefonts/opensans/tree/main/fonts, but the version of Google Fonts hasn't been updated yet.

```
$ hb-view --output-format=png --text=ŞşŢţ fonts/ttf/OpenSans-Regular.ttf
```
<img width="263" alt="image" src="https://user-images.githubusercontent.com/1923747/114889517-1850be00-9e02-11eb-8834-e366459ac55d.png">

```
$ hb-view --output-format=png --text=ŞşŢţ --language=ro fonts/ttf/OpenSans-Regular.ttf
```
<img width="263" alt="image" src="https://user-images.githubusercontent.com/1923747/114889414-053dee00-9e02-11eb-863b-ad8aa5fb2a93.png">

**Comment by davelab6** [comment]
👍

Should be soon

**Comment by davelab6** [comment]
Open Sans Condensed is frozen and will never be updated; we just pulled the https://fonts.google.com/specimen/Open+Sans+Condensed page, although the API will continue to serve existing users.

Instead, use Open Sans with the Width axis to obtain the styles you want.

**Comment by fitojb** [comment]
> use Open Sans with the Width axis

Which is difficult to select since the Axes section on Google Fonts pages are never displayed to users of Microsoft Edge and Firefox. Why is that?
