### ISSUE TITLE
Lora en-dashes and em-dashes are too similar

### ISSUE THREAD

**Issue by benjaminwil** [google/fonts#217]
[Lora](https://www.google.com/fonts/specimen/Lora)'s en-dashes and em-dashes are similar in length. The em-dashes are much shorter than in other typefaces, and jarringly short when using pairs of em-dashes. [I made an example on CodePen](http://codepen.io/benjaminwil/full/pgXPrW/) to highlight this.

**Comment by davelab6** [comment]
Thanks for the report and example!

**Comment by kaplanoah** [comment]
Would be awesome to get longer em dashes. We love Lora but sometimes the em dashes don't effectively break up a sentence because they read like hyphens.

**Comment by davelab6** [comment]
cc @alexeiva

**Comment by alexeiva** [comment]
The em dash has been fixed in the v1.015 release on Cyreal's github:
https://github.com/cyrealtype/Lora-Cyrillic

![screen shot 2016-05-25 at 19 58 09](https://cloud.githubusercontent.com/assets/16634089/15549651/400be9b4-22b6-11e6-9269-dbb9c9b78ce1.png)
![screen shot 2016-05-25 at 19 56 20](https://cloud.githubusercontent.com/assets/16634089/15549659/438e7264-22b6-11e6-838f-a8d507100c7a.png)

**Comment by m4rc1e** [comment]
Can confirm its fixed, closing.

![screen shot 2017-06-16 at 11 54 02](https://user-images.githubusercontent.com/7525512/27223926-846bf8a6-528a-11e7-9f24-59cf515bb677.png)
http://jsbin.com/yacogiheme/edit?html,output

**Comment by m4rc1e** [comment]
My example included just the en dash and hyphen.

Here's em, en and hyphen.

![screen shot 2017-06-16 at 17 04 48](https://user-images.githubusercontent.com/7525512/27234733-ef20facc-52b5-11e7-91a8-cf28b7a5e800.png)

**Comment by benjaminwil** [comment]
Thanks for the additional image.

It's hard to compare without seeing the em-dash being in text, but it looks slightly longer than [in the original example](https://codepen.io/benjaminwil/full/pgXPrW).
