### ISSUE TITLE
Fonts have wrong name and are not installed

### ISSUE THREAD

**Issue by Stadly** [google/fonts#219]
Roboto Regular is shown as "Roboto Black", and Roboto Italic as "Roboto Black Italic" when previewing the fonts in Windows.

When installing all the 12 Roboto fonts, only 10 fonts are shown in `C:\Windows\Fonts\Roboto`. Regular and Italic are missing. Maybe they are overwritten by the Roboto Black fonts?

![image](https://cloud.githubusercontent.com/assets/7263579/13526580/0ad9844c-e209-11e5-94c9-c5d24eb0026a.png)

**Comment by davelab6** [comment]
@m4rc1e will https://github.com/google/roboto/issues/236 fix this?

**Comment by m4rc1e** [comment]
@davelab6 I looked at this earlier. It works perfectly on my Win 7 system, using [Roboto v2.136](https://github.com/google/roboto/releases)

![screen shot 2017-03-08 at 16 32 59](https://cloud.githubusercontent.com/assets/7525512/23713162/ecde7cd6-041c-11e7-8c71-a6dee1a3ba63.png)

Keep this open because it may relate to the v2.000 release.

**Comment by codeman38** [comment]
One telltale thing in the screenshot: "Version 1.200310; 2013". This is even older than the version that's present in the google/fonts repo.
