### ISSUE TITLE
fonts.googleapis.com returns 403 error when referrer is present

### ISSUE THREAD

**Issue by anuragphadke** [google/fonts#2214]
Hi,
https://amp.stewartmovingandstorage.com/amp/pensacola-things-to-know-when-moving-to-pensacola-florida.1.html

fonts.googleapis.com returns a 403 while loading fonts on this page. Equivalent curl:
`
curl 'https://fonts.googleapis.com/css?family=Open+Sans:700|Open+Sans:400|Montserrat:400|Helvetica:400|Montserrat:700' -H 'Sec-Fetch-Mode: no-cors' -H 'Referer: https://amp.stewartmovingandstorage.com/amp/pensacola-things-to-know-when-moving-to-pensacola-florida.1.html' -H 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1' --compressed`

However, removing the referrer returns 200. 

Any reason why fonts.googleapis.com would return a 403?

**Comment by garretrieger** [comment]
Helvetica is not part of  the google fonts collection and cannot be used through the API. Please remove it from your request and it should work.

**Comment by anuragphadke** [comment]
@garretrieger : what's the best way to get list of fonts that are part of Google Fonts collection? https://fonts.googleapis.com/css?family=Helvetica:400 returns a 200. 
I can generate a list off https://github.com/google/fonts if you can guide me on a way to build that list.

**Comment by garretrieger** [comment]
The most up to date listing of which families are available on the API can be found in our catalog (https://fonts.google.com/) or through our developer API ( https://developers.google.com/fonts/docs/developer_api)

**Comment by anuragphadke** [comment]
thank you!

**Comment by msr8** [comment]
> The most up to date listing of which families are available on the API can be found in our catalog (https://fonts.google.com/) or through our developer API ( https://developers.google.com/fonts/docs/developer_api)

Hey so i dont know if this issue is related, but whenever I am loading the Inconsolata font on my local machine, it is working, but when the request is sent using github pages, it returns a 404

On my local machine:

![Screenshot 2023-06-25 at 1 46 32 AM](https://github.com/google/fonts/assets/79649185/7c2957ed-bacc-4529-8712-105f7d6c97f6)

<br>

On github pages (https://msr8.github.io/cats/stats):

![Screenshot 2023-06-25 at 1 47 30 AM](https://github.com/google/fonts/assets/79649185/d84d1cc8-965a-49d0-b835-760e7f327457)
