### ISSUE TITLE
Maven Pro - Bold 'i' incorrect

### ISSUE THREAD

**Issue by DM2489** [google/fonts#2295]
Hi,

When using Maven Pro, a font size of 16, and bold, the lower case 'i' is not rendered correctly. The 'i' appears to be more like an 'I', because the superscipt dot is joined to the rest of the character.

![image](https://user-images.githubusercontent.com/40390596/71189668-1cef7b80-227b-11ea-8af6-e7f4c7799df1.png)

Here is a codesandbox showing the issue:

https://codesandbox.io/s/google-font-example-beq7g

**Comment by m4rc1e** [comment]
On Browserstack Win 10 Chrome 79.

<img width="795" alt="Screenshot 2019-12-19 at 16 31 44" src="https://user-images.githubusercontent.com/7525512/71190853-35f92c00-227d-11ea-8e0c-9ff7b8092e8f.png">

I agree, it's definitely too tight. 

We recently upgraded the family to a variable font. The outlines haven't changed when compared to the previous static fonts. I'm pretty sure this issue is being caused by either the font's hinting or how FreeType is interpreting the outline.

Which OS and browser are you using?

cc @davelab6

**Comment by DM2489** [comment]
I'm using Win10 1903, chrome 79. A colleague is using win10 1903 and FireFox 71.0. We both see the same issue.

**Comment by m4rc1e** [comment]
Thanks.

I've confirmed the hinting is at fault.

Here's a [test case](http://35.238.63.0/compare/564f9245-6bf7-4a5e-a573-daa5b3161b38) which has the fonts we currently serve in the before positioned and an unhinted font in the after position. The unhinted font doesn't suffer with this issue.

![maven](https://user-images.githubusercontent.com/7525512/71192959-2c71c300-2281-11ea-99b1-ab4fad794f30.gif)

**Comment by DM2489** [comment]
So the issue affects many other characters too, looking at the image switching above.

**Comment by Daymarius** [comment]
I don't have this problem
![Screenshot_61](https://user-images.githubusercontent.com/18142611/71195159-086cac80-2296-11ea-9135-ab70ccc23a73.png)

**Comment by m4rc1e** [comment]
@DM2489 can you check if this [jsbin](https://jsbin.com/wiwaxecoca/1/edit?html,output) solves your issue please? also do . ctrl+- and ctrl++ to change text sizes

**Comment by DM2489** [comment]
@m4rc1e Looks perfect to me across all text sizes. Thanks for this!

**Comment by madig** [comment]
This looks like a typical FreeType autohinter issue to me. Happens frequently when the stars misalign on a certain typeface, as in, design and size dependant.

**Comment by m4rc1e** [comment]
@DM2489 update should now be live. Can you confirm issue is fixed? thanks.
