### ISSUE TITLE
Add all "Source Serif Pro" weights

### ISSUE THREAD

**Issue by yosefw** [google/fonts#23]
The full family has 6 weights: 200, 300, 400, 600, 700, 900 ([see Source Serif on Typekit](https://typekit.com/fonts/source-serif-pro))

On Google Fonts, there's only 400, 600, 700.

Please add the missing weights: **200**, **300** and **900**;

**Comment by davelab6** [comment]
https://blog.typekit.com/2017/01/10/introducing-source-serif-2-0/ has a major new update

**Comment by davelab6** [comment]
https://v-fonts.com/fonts/source-serif-variable relates to this

**Comment by HM100** [comment]
Any ETA on this?

**Comment by doersino** [comment]
👀

It'd be *really* neat to have italics!

**Comment by thlinard** [comment]
[Version 3 released](https://github.com/adobe-fonts/source-serif-pro/releases):

- Same charset coverage in Roman and Italic (AL-4, AC-2, AG-1)
- VF version (not new, but good point to emphasize)

**Comment by thlinard** [comment]
Adobe provides the 12 styles here:
https://fonts.google.com/specimen/Source+Serif+Pro

**Comment by davelab6** [comment]
> [Version 3 released](https://github.com/adobe-fonts/source-serif-pro/releases):
> 
> * Same charset coverage in Roman and Italic (AL-4, AC-2, AG-1)
> * VF version (not new, but good point to emphasize)

The glyphset difference between Roman and Italic was blocking this issue since 2015.

Since the v3 release last summer we've been focused on VF onboarding, and there's a major VF update to this family coming with an optical size axis, so I'd left this family for that. 

Not that's nearly ready, I rethought this and we should prioritize shipping the static v3 fonts now, then look at how to do the VF upgrade. Probably a few steps, V4 static, then v4 weight only, then v4 opsz.

**Comment by thlinard** [comment]
Hi @davelab6 

Glyphset difference or charset difference? I was under the impression that it was the charset difference that counted. Anyway, for the charset difference, the problem is solved with the version 3 (for Source Sans too, by the way).

**Comment by davelab6** [comment]
Yep, good point, I did mean char set in this case :)

**Comment by m4rc1e** [comment]
Latest fonts are now in production, https://fonts.google.com/specimen/Source+Serif+Pro
Enjoy

**Comment by frankrolf** [comment]
Thank you!
