### ISSUE TITLE
Poppins vertical alignment

### ISSUE THREAD

**Issue by asadkn** [google/fonts#241]
There's a problem with not just one but with many fonts from the ITFoundry on Google Web Fonts. The vertical-alignment is off by a couple of pixels. It's normal for vertical alignment to be off a pixel or two but this is way off. I have only tested it in WebKit browsers (Chrome and Safari) and Firefox on Mac. 

You can observe the issue here: https://jsfiddle.net/yxjpjw3s/

<img width="352" alt="uajqdu753l" src="https://user-images.githubusercontent.com/261579/29528316-9e16e488-8669-11e7-921a-6009ef821711.png">

Screenshot: https://cloudup.com/cs4Gw3imPJ4 (zoomed in, not to scale)

**Comment by saadibrahim** [comment]
Can confirm this issue.

**Comment by MohsinNaqi** [comment]
Yes same on Windows Chrome.

**Comment by m4rc1e** [comment]
Hello,

Firstly, thank you for the nice test! it made my life easier.

Poppins is a Devanagari font which means it may need to have larger vertical metrics than ordinary Latin fonts, due to stacking conjuncts and mark positioning. 

![screen shot 2016-08-31 at 11 25 33](https://cloud.githubusercontent.com/assets/7525512/18123322/aac4c7b8-6f6d-11e6-9e49-a1ce330b39e8.png)
**Double conjunct with below mark**

Fonts like Zapfino & Baghdad also suffer a similar fate:
[https://jsfiddle.net/yxjpjw3s/3/](https://jsfiddle.net/yxjpjw3s/3/)

If you don't have a Mac, here's a screenshot.
![screen shot 2016-08-31 at 11 28 02](https://cloud.githubusercontent.com/assets/7525512/18123421/05fd870a-6f6e-11e6-9780-9023c652583a.png)

I'm assuming that fonts from different vendors will have the same problem. Open Sans's vertical metrics were probably set to match those of system fonts.

My recommendation is not to fiddle with the metrics, since this may lead to clipping or other unforeseen consequences on Poppins. Also, If you remove the line-height property, you get this:
[https://jsfiddle.net/yxjpjw3s/4/](https://jsfiddle.net/yxjpjw3s/4/).

To solve your issue, why not use a geometric Sans Serif which doesn't include a non-Latin? The metrics would then be closer to a system font.

I hope this is clearer

**Comment by laerm0** [comment]
Nicely explained by @m4rc1e so I am closing.

**Comment by huykon** [comment]
I also have this problem. I think Poppins font have problem with design. Can anyone fix that?

**Comment by mikecreuzer** [comment]
Agreed

**Comment by bugeats** [comment]
Can we get a **latin only version**? The vertical spacing makes this font very difficult to work with for latin type using any kind of consistent rhythm.

**Comment by acicali** [comment]
@bugeats 
I noticed that only my self-hosted Google fonts were having this problem. Looking Google's CSS, they specify a range of characters. You should be able to do the same to resolve your issue:
``` css
@font-face {
    /* latin */
    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}

Additionally, you can grab the source font file (e.g. ttf) from Google's font repo and run it through FontSquirrel for Latin-only subsetting... probably a better solution that would result in a smaller font file.

Hope this helps.

**Comment by acicali** [comment]
Also, Google does provide Latin only (and other subsets) of the webfont files... just reference their CSS file directly:
https://fonts.googleapis.com/css?family=Poppins&display=swap

Note: they use user-agent detection to decide which format to serve (woff, woff2, etc) so you may need to visit this in multiple browsers to get all of the formats you need.

**Comment by erickmonteiro** [comment]
> 
> 
> Also, Google does provide Latin only (and other subsets) of the webfont files... just reference their CSS file directly:
> https://fonts.googleapis.com/css?family=Poppins&display=swap
> 
> Note: they use user-agent detection to decide which format to serve (woff, woff2, etc) so you may need to visit this in multiple browsers to get all of the formats you need.

can also be downloaded in various formats via "google webfonts helper"
https://google-webfonts-helper.herokuapp.com/fonts/poppins?subsets=latin
