### ISSUE TITLE
Normalize the file naming pattern of Open Sans

### ISSUE THREAD

**Issue by vivid-inc** [google/fonts#256]
The file names of all weights of Open Sans are normalized with the pattern "OpenSans-WEIGHT" and the corresponding italicized variant as "OpenSans-WEIGHTItalic", with the exception of the Regular weight.

I propose renaming the font files for "OpenSans-Italic" to "OpenSans-RegularItalic", thus unifying the file naming pattern.

Yes, this change may have down-stream implications for i.e. existing @font-face declarations, but this change will eliminate the need to second-guess and also eliminate need for special casing when machine processing the filenames.

**Comment by laerm0** [comment]
I've never seen an italic weight labeled as "-RegularItalic." Is this actually a bug?

**Comment by vivid-inc** [comment]
Agreed, an italic weight labeled as "RegularItalic" would indeed be nonsense.

Fortunately, I'm referring only to the name of the file as it sits on the filesystem or within an archive file. Squinting hard at a directory full of fonts I have on hand here, two clear naming patterns emerge:

(A) being that Open Sans currently follows, there the regular-weighted file is named "-Regular" and the italicized variant of the regular weight named "-It" or "-Italic", without reference to its weight. This is a special casing.

Next, there are (B) files with regular weights are not named regular, they simply have no suffix. For Open Sans, instead the "OpenSans-Regular" would be renamed to "OpenSans" (note that ''-Regular'' is dropped).

The principle behind (B) that guides the choice of filename is therefore "[FAMILY]-[WEIGHT][ITALIC].[FORMAT]", where WEIGHT is not mentioned if it is regular, and ITALIC is optionally present, giving all font files a predictable file naming scheme suitable for both people and for machine-processing.

**Comment by laerm0** [comment]
Right, I mean I've never seen a filename that was "-RegularItalic." I understand your complaint, but I don't think it's a problem that needs fixing. I'm not one to stick with tradition just because, but this is the industry standard. Maybe it's because I know what I am looking for when I look at a directory full of fonts, that the regular and its italic weight aren't going to be sitting next to each other.

(Personally, the industry had its chance to make things better but few foundries/designers have adopted [Frutiger's system](https://en.wikipedia.org/wiki/Univers#The_Frutiger_numbering_system).)

**Comment by davelab6** [comment]
Thanks for proposing this to us, @vivid-inc , but we won't do this. 

However, we have some logic in https://github.com/googlefonts/fontbakery/ that you can use as a reference for handling this.
