### ISSUE TITLE
Embed styles: Variable font used or not?

### ISSUE THREAD

**Issue by strarsis** [google/fonts#2579]
When embedding multiple Raleway styles from Google Fonts API, https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;600;700&display=swap, in the delivered styles it appears no font variation specific CSS is used (like `font-variation-settings`).
Or is this automatically embedded and I can use `font-weight` and `font-style` as usual?

**Comment by davelab6** [comment]
Please do read https://developers.google.com/fonts/docs/css2 carefully.

You've requested only the 4 static/discrete styles (400, 500, 600, 700) with that URL:

/css2?family=Raleway:<b>wght@400;500;600;700</b></tt>

The API is only guaranteed to return what you request, and it may return more than what you request, or not what you expect, because it is more efficient to 'overstuff' a cache, for example - but you should not rely on that. 

To request a range from 400 to 700, do this:

/css2?family=Raleway:<b>wght@400..700</b>

**Comment by strarsis** [comment]
Thanks. Also the `css` part of the URL has to be replaced with `css2` (like `v2` in an API).
