### ISSUE TITLE
API: Download ZIP ttfs have inaccurate date filesystem metadata

### ISSUE THREAD

**Issue by davelab6** [google/fonts#2619]
In https://github.com/google/fonts/pull/2533#issuecomment-674120741 @lornaSIL pointed out that downloaded fonts have modified/created file system metadata set to the METADATA `date-added` value. 

But it would be better to use a more accurate date, as that value can now be 10 years ago :D

- the file system date metadata found on the files in this repo
- the [TTF `head` table](https://docs.microsoft.com/en-us/typography/opentype/spec/head) values. Eg `Harmattan-Bold.ttf` downloaded from http://fonts.google.com/download?family=Harmattan has

```xml
    <created value="Fri Jun 12 23:40:51 2020"/>
    <modified value="Fri Jul  3 09:13:14 2020"/>
```

**Comment by LornaSIL** [comment]
I would like to see a resolution to this. Harmattan was updated 19-Jun-2020 by SIL and it was added to Google Fonts not too long after. When I download the package it still gives the file dates of 2016-06-15 which is disconcerting to users.

Also, when I look at Arabic script fonts:
https://fonts.google.com/?subset=arabic

Harmattan, and a few other fonts are not displaying the lam/alef ligature properly. It may be how the lam/alef ligature is implemented in the font, but it would be nice to have the rendering on Google Fonts work better.

**Comment by alerque** [comment]
> * the file system date metadata found on the files in this repo

Files in Git repositories do not have timestamps in filesystem metadata that is usable for this. The time usually reflects activity on the Git repository (such as `clone` or `checkout`), often unrelated to the file contents.

> * the [TTF `head` table](https://docs.microsoft.com/en-us/typography/opentype/spec/head) values. Eg `Harmattan-Bold.ttf` downloaded from http://fonts.google.com/download?family=Harmattan has

The TTF head table values often reflect built times. Given that fonts can and often are rebuilt at a time unrelated to the contents of the font I don't think that value should be used either.

Use the Git commit timestamp of the last commit to change the file:

    git log -n1 --pretty=format:%cI -- path/to/file/in/repo

Sometimes it's useful to be able to use filesystem last modified timestamps. If you want to reset a working directory that is a fresh clone or recently switched branches so that all files have their last *commit* time as the timestamp you can iterate a repository like this:


    git ls-files |
      while read file; do
        ts=$(git log -n1 --pretty=format:%cI -- "$file")
        git diff-files --quiet -- "$file" || continue
        touch -d "$ts" -- "$file"
      done

**Comment by davelab6** [comment]
@LornaSIL fixed in https://github.com/google/fonts/commit/7614e5d30d821bdd037f3718bf7eb8123d60ea32 and should be fixed in production before end of year, if not sooner
