### ISSUE TITLE
Rubik's font-weight is not reflected while printing

### ISSUE THREAD

**Issue by scarigor** [google/fonts#2652]
Couple days ago I noticed, that Rubik's font-weight is broken while I'm trying to print my page. It's reproducible on [google fonts website](https://fonts.google.com/specimen/Rubik) also.

Environment:

- Chrome Version 85.0.4183.83 (Official Build) (64-bit)
- Windows 10

![image](https://user-images.githubusercontent.com/15365823/91412519-91d77400-e852-11ea-9db6-09e0be382722.png)

**Comment by thlinard** [comment]
I can't reproduce on Chrome 85.0.4183.83, macOS 10.15.6.

**Comment by scarigor** [comment]
> I can't reproduce on Chrome 85.0.4183.83, macOS 10.15.6.

Just updated my Chrome to latest version (Version 85.0.4183.83 (Official Build) (64-bit)) - still reproducible on google fonts page.
![image](https://user-images.githubusercontent.com/15365823/91416153-ac601c00-e857-11ea-96b9-efe18cb3c840.png)

![image](https://user-images.githubusercontent.com/15365823/91416198-baae3800-e857-11ea-9a08-bf34f84509e7.png)

**Comment by thlinard** [comment]
Are you on Windows? macOS? Linux?

**Comment by scarigor** [comment]
> Are you on Windows? macOS? Linux?

Windows 10, added environment description to issue.

**Comment by ChewbaccaCookie** [comment]
It seems to be an issue with Chromium on Windows because on Mac I can't reproduce this error.
On Windows, both Edge(85.0.564.68) and Chrome (85.0.4183.121) have a problem with printing some fonts (e.g. Raleway or Rubik). Some fonts like Roboto behave as desired.

__Chrome:__

![chrome-issue](https://user-images.githubusercontent.com/15861250/95074747-5a8c9a80-070f-11eb-8157-754dacefd5a5.png)

__Edge:__

![edge-issue](https://user-images.githubusercontent.com/15861250/95074598-18635900-070f-11eb-8078-8f0b66b35e36.png)
