### ISSUE TITLE
Inverted question mark reversed in Cantarell font

### ISSUE THREAD

**Issue by stevenickels** [google/fonts#269]
The inverted question mark character appears to be reversed horizontally in the Cantarell font.

Demo: https://jsfiddle.net/j1uyob17/1/

**Comment by fitojb** [comment]
This issue was fixed in Cantarell a long, long time ago… back in 2011, to be specific. See https://bugzilla.gnome.org/show_bug.cgi?id=639773

**Comment by stevenickels** [comment]
Interesting. It appears that fix never made it to the online fonts repository, because the problem currently exists when using fonts via Google's CDN, as evidenced by the above jsfiddle link.

**Comment by codeman38** [comment]
According to #112, Google decided not to use Gnome's version of Cantarell because the italic and bold italic styles were dropped, and the style had changed enough that the newer roman and older italic did not harmonize well.

Maybe this should be reconsidered again, now that there's an official oblique variant being automatically generated upstream?

**Comment by davelab6** [comment]
Yeah, I'm open to that, and there's also Camby.

**Comment by davelab6** [comment]
Will be fixed as part of https://github.com/google/fonts/issues/112 so closing
