### ISSUE TITLE
Latest font additions are not yet in Git repository

### ISSUE THREAD

**Issue by codeman38** [google/fonts#271]
Most of the recently added fonts from the new Google Fonts site at http://fonts.google.com/ are still not available in the Git repository, such as:
- Athiti
- Bungee
- The expanded set of styles for Changa
- Cormorant
- Libre Franklin
- Proza Libre
- Kumar One

Is there a planned Git push to bring the repo up to parity with the web interface?

**Comment by rsheeter** [comment]
Soon :)

**Comment by ajck** [comment]
@rsheeter @davelab6 Thanks. Probably stating the obvious, but the webfonts.json list at https://www.googleapis.com/webfonts/v1/webfonts?key=...
is also missing all the new fonts. Interestingly some that are on fonts.google.com are in the full archive download master.zip (such as baloo) but not in the JSON, but some not in either (such as Cairo).

Many thanks

**Comment by mray** [comment]
Add at least "Maitree" and "Taviraj" to that list.

**Comment by davelab6** [comment]
There are about 100 on the list. They should all have upstream on github
that are easy to search for

**Comment by mray** [comment]
The benefit of the binary repo for me was:  download once and have them all.

**Comment by davelab6** [comment]
> The benefit of the binary repo for me was: download once and have them all.

I will soon see that everything in the API is added to this repo, and otherwise make sure the github repo matches what is available from the API 1:1. 

There's already a script to do this (https://github.com/googlefonts/fontbakery/blob/master/fontbakery-metadata-vs-api.py) but it hasn't been put to use yet. 

That script offers a workaround until then - it demonstrates how to throw a few lines of Python at https://developers.google.com/fonts/docs/developer_api and fetch everything.

**Comment by sternenseemann** [comment]
As mentioned in #723 Shrikhand is also missing as well.

**Comment by davelab6** [comment]
@codeman38 @sternenseemann @mray @ajck this should now be all fixed. Please let me know if you find anything else missing :)

**Comment by jlsync** [comment]
"Kumar One Outline" is not in the repository ( but "Kumar One" is ).
