### ISSUE TITLE
Revaluation of grade, GRAD

### ISSUE THREAD

**Issue by dberlow** [google/fonts#2710]
I propose the values for Grade (`GRAD`) be changed, from min/default/max of -1/0/1, to 1/400/1000, so as to match the value system of the weight (`wght`) axis. The current solution was proposed with no clear alternatives at the time, so to match the UI value range common to all axes, was decided.

Now it’s clear, from questions surrounding implementation issues for dark mode automation in a mobile OS, that having relative and absolute values, for both weight and grade, is required long term. So:

* wght = relative weights 1..1000
* GRAD = relative +/- from 400 at same scale as wght
* XOPQ = weight in 1/1000 of em, measure of typical feature.
* PGRD = grade in 1/1000 of em, measured on same feature as XOPQ

The advantages I can see of a duo of relative axes include:

1. Knowing, from the `GRAD` axis range, whether it’s a narrow ranging axis, e.g. `350..400..450` for tuning, or a broad grad axis range, e.g. `100..400..700` for tuning and weight changes, which is programmatically useful, as well as providing more specific information linking Weight and Grade.
2. A `wght`-relative `GRAD` value enables synthetic `GRAD` axes to be automatically conjured at the same scale as `wght` in monospaced fonts, where `wght` and `grad` share the same variation and programs might not “know” that.
3. A future `avar2` implementation, where values of `wght` shift along `wdth` and `opsz` axes, could maintain accurate `wght`-relative values as the `GRAD` axis needs to be tailored and trimmed around a design space.
4. Being able to communicate and specify the `wght` with a grade change, e.g. saying “400 over 380”, allows for more complex fallback solutions, when solving dark mode issues between font families, and when mixing use of scripts between families.
5. Specifying type with size/leading, e.g. saying “10 over 16 points”, to communicate both size and line spacing, or ordering type “10 point with 12 point bodies”, to communicate type with additional letter spacing applied, are traditional in metal typesetting practice. This addition, of a nominal weight adjusted for particular conditions, without changing other conditions, fits that model.

**Comment by davelab6** [comment]
@m4rc1e can you include this in the review of Roboto Serif

**Comment by davelab6** [comment]
I'm still pondering this; @m4rc1e looking forward to hearing your thoughts

**Comment by m4rc1e** [comment]
Apologies for my late reply.

I have no real strong feelings about this tbh.

My only concern is that if we match the weight values, inexperienced users may think they need to set the GRAD axis so its value matches the weight value. Imo the GRAD should be set independently based the medium e.g print stock, screen dpi etc.

**Comment by davelab6** [comment]
https://v-fonts.com/fonts/san-francisco-rounded has `400..1000`

**Comment by davelab6** [comment]
I suppose I'll need to PR an update to https://github.com/TypeNetwork/Opentype-1.8-Axis-Proposal/blob/gh-pages/proposal/Grade/ProposalSummary.md before #2761 can be merged

**Comment by tiroj** [comment]
> GRAD = relative +/- from 400 at same scale as wght

Hi David, just want to see if I understand correctly:

You’re proposing that GRAD be on the same unit scale as wght, but that the actual steps on that scale in GRAD implementation would be relative to the wght instance? So, a GRAD adjustment of -5 units to the Regular wght (400) would be the same, in terms of stem weight, as 395 wght, but obviously without any change of advance width such as would be the case in a wght change.

It implies, though, that GRAD is always specified relative to the wght value, no? Or, at least at a lower level directly referencing the GRAD axis scale: a tool could express GRAD adjustment to the user as a +/- control. So if text were set in a variable wght instance of 570, and a GRAD adjustment of +4 were wanted for some purpose, that would need to be specified as 574 units on the proposed GRAD scale. That seems to me potentially problematic because if the wght instance is changed, that implies that the GRAD instance also needs to be changed to maintain the relative relationship. So shouldn't the GRAD axis be defined in a way that makes it always relative to the other axes, such that it could be set to e.g. +4 and it would remain +4 regardless of what changes are applied to other axis positions?

Internally, in the font design space, it makes a lot of sense to me that wght and GRAD axes should used the same units and in a coordinated way, but I’m not sure that implies they should have the same axis scale in terms of the way instances are expressed for each.

**Comment by dberlow** [comment]
Thanks for your interest in grades. Absolute units have been rejected by you and others, with the “what’s being measured?” virus  conjoined to the spec owner’s infertility. If relative units are a problem, (to do something about registering grade after 35 years), it’s probably better forget it until “avar2”.  Perhaps that mythical future can be controlled by those with more typographic fecundity in mind.

Until then, Font Bureau will make custom grade axes for each client according to their requested values. 

Kindest regards,
David Berlow

On Oct 21, 2020, at 12:46 AM, John Hudson <notifications@github.com> wrote:

﻿
GRAD = relative +/- from 400 at same scale as wght

Hi David, just want to see if I understand correctly:

You’re proposing that GRAD be on the same unit scale as wght, but that the actual steps on that scale in GRAD implementation would be relative to the wght instance? So, a GRAD adjustment of -5 units to the Regular wght (400) would be the same, in terms of stem weight, as 395 wght, but obviously without any change of advance width such as would be the case in a wght change.

It implies, though, that GRAD is always specified relative to the wght value, no? Or, at least at a lower level directly referencing the GRAD axis scale: a tool could express GRAD adjustment to the user as a +/- control. So if text were set in a variable wght instance of 570, and a GRAD adjustment of +4 were wanted for some purpose, that would need to be specified as 574 units on the proposed GRAD scale. That seems to me potentially problematic because if the wght instance is changed, that implies that the GRAD instance also needs to be changed to maintain the relative relationship. So shouldn't the GRAD axis be defined in a way that makes it always relative to the other axes, such that it could be set to e.g. +4 and it would remain +4 regardless of what changes are applied to other axis positions?

Internally, in the font design space, it makes a lot of sense to me that wght and GRAD axes should used the same units and in a coordinated way, but I’m not sure that implies they should have the same axis scale in terms of the way instances are expressed for each.

**Comment by davelab6** [comment]
> You’re proposing that GRAD be on the same unit scale as wght, but that the actual steps on that scale in GRAD implementation would be relative to the wght instance?

That isn't possible with the 1.8 format, and isn't what David proposed above, although as he says we can all imagine an `avar` v2 table which would make it possible.

What I understood David proposed is (a) that `GRAD` be on the same unit scale as `wght`, and (b) that the actual steps on that scale in `GRAD` implementation would be relative to the default `400` `wght` instance. 

(a) means that you can tell the difference between family with a Grade axis that is very subtle and has a limited range, and a family with a wide Grade axis that is more dramatic; or between a family that has a Grade axis that has an even range in both positive and negative directions, with a family that has a lot more positive range than negative. 

With the current `GRAD` axis definition, I expect we'd see all 4 families with a range of `-1..1` and thus the differences would not be clear. Of course they could be `-0.2..0.2`, `-1..1`, `-0.5..0.5`, `-0.25..0.75` - but these are not related to the Weight axis. 

(b) means that if text were set in a variable `wght` instance of `400`, and a `GRAD` adjustment of `+4` were wanted for some purpose, under the limits of the 1.8 format, that would need to be specified as `404` units on the proposed `GRAD` scale; but, if `wght` is `570`, the `GRAD` value will still be `404`. I think this is more trouble than it's worth.

So, I agree that the `GRAD` axis in 1.8 fonts should be defined in a way that makes it always relative to the other axes, such that it could be set to e.g. `+4` and it would remain `+4` regardless of what changes are applied to other axis positions; and therefore the `GRAD` default should be `0`, not `400`; but then be on the same unit scale as `wght` (a).

That means to me the theoretical min/max and therefore a new definition of min/max/default could be `-999,0,999`, for fonts with a OS/2 weight class value of `1000` or `1`; while `400` is the axis default, it seems allowed by the spec to have fonts that do not span that value (eg `500..700`) or even just have a single non-`400` value.

However, I expect the typical ranges implemented will be something like `-50..50` (half way to the next Weight axis named instance position) or `-100..200` (to reach the next one negatively, or 2 upwards) 

Its possible with an `avar` v1 table, or "corner masters" for `wght+GRAD`, to control the actual effect to be non-linear, so that eg a `GRAD` value of `+50` will have more effect at a `wght` value of `800` than at `400`; and indeed this may be required to have **the same** effect, since a linear effect expanding stems by 20 UPM units will be proportionally less on the 400 and more on the 800.

**Comment by tiroj** [comment]
Thanks, Dave. That makes more sense to me now.

> ...indeed this may be required to have the same effect, since a linear effect expanding stems by 20 UPM units will be proportionally less on the 400 and more on the 800.

Proportionally _more_, I think, i.e. the effect of increasing the Regular stem weight by 20 UPM is proportionally greater than that of adding 20 UPM to the Extra Bold stems.

But depending on the purpose for using a grade variation, non-proportional gain might be exactly what you want. If grade is compensating for ink distribution in a particular press setup or for backlit lettering, you probably don't want an grade adjustment that is proportional to the starting stem weight, but perhaps something that is closer to a linear adjustment and very probably inversely proportional, reducing as weight increases, i.e. you'll want to add more to a Light font than to a Black font.

This is one of the concerns I have with implementing grade as a single axis: grade variations are used for different purposes, and maybe multiple axes for specific purposes make more sense that presuming that just because we had grades of type in the past this means we need a grade axis.

**Comment by davelab6** [comment]
> Proportionally more, I think

Sorry yes, that was a mistake on my part

> This is one of the concerns I have with implementing grade as a single axis: grade variations are used for different purposes, and maybe multiple axes for specific purposes make more sense that presuming that just because we had grades of type in the past this means we need a grade axis.

I don't get that, at all. If the grade axis has a broad range, it can be used in different ways, as needed. There's no need to have a set of grade axes with different ranges and scales that all do the same thing to a greater or lesser extent.
