### ISSUE TITLE
Upgrade Lexend

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#2724]
upstream repo : https://github.com/ThomasJockin/lexend/
update: charset exp. (arabic) + bug fixes

**Comment by RosaWagner** [comment]
@davelab6 about this project : 
Right now the VF is not on GF, so I guess I will add it at the same time as the updated statics (it needs a reviewed build script to add a proper stat table + new family directory). 

Lexend is using a custom axis named "LXND" which is a mix of width and spacing. As you know, fallbacks names are the units prefix (deca, exa, giga, mega, peta, tera, zetta). It makes sense but it makes it hard for other projects to use it. Should we try to find an axis name which would be more self explanatory (also according to the fallback names), and/or less specific to this project, so other font project could use it — or maybe this axis already exist? 

https://typedrawers.com/discussion/2088/otvar-spacing-axis is not quite that, but kind of linked.

cc @ThomasJockin, please give us your opinion.

**Comment by ThomasJockin** [comment]
Hi @RosaWagner it's a pleasure to speak with you. Thank you for taking the time to get the VF of Lexend onto GF. 
The axis pair of `spac` with `wdth` would be ideal to decompose what the custom axis `LXND` does. A shame `spac` isn't supported yet. The only other the axis pair I can think of would be `opsz` and `wdth`. But, if we go in the `opsz` direction, there is an issue of mapping values. `opsz` has a scale interpretation that values are text size, in points. To me, that would mean as the font increases in size the opsz is matching in value, as in 9 point is "deca", 12 pt is "giga", 40 pt is "zetta". [The San Francisco VF demo applies the `opsz` axis in such a manner](https://developer.apple.com/videos/play/wwdc2020/10175/). 

That is not our intention with Lexend because font size and spacing are independent of each other. For a robust reader to read comfortably a text set in 6pt, a more intense spacing setting like Giga might required. Meanwhile for a struggling reader to be read comfortably, the font size might need to be 24pt with that same Giga intensity setting.

While I understand the concern to have transparent axis naming and properties, unless `spac` is supported I do not see a good solution other than keeping the custom axis name.

**Comment by RosaWagner** [comment]
Thanks for your answer! You are right, optical size wouldn't be relevant. I think we could register the spacing axis as a custom axis (so `SPAC` instead of `spac`) in google's axis registry, so we wouldn't have to wait for the opentype format to support it. Although, the interdependency of 2 different axis would make it difficult on our side to generate the correct number of instances with the correct naming from the VF. Unless Dave thinks otherwise, I would rather go with one custom axis (like LXND), but with a name that could be used in other projects. Like… "wideness" if this word even exists, or "extension". "Stretching" would actually be perfect but it would also be confusing because the css property `font-stretch`. Wideness?

**Comment by ThomasJockin** [comment]
If we are nixing the two axis pairing solution for the one axis, I recommend we just stay with `LXND`. Wideness, Extension, and Stretch all have ambitious meanings that do not capture what the `LXND` axis does.

If we do choose the two axis pairing solution, `SPAC` with `wdth` works for me. This option allows for transparent intra-font application of the axes.

**Comment by RosaWagner** [comment]
@ThomasJockin To keep you updated, we are having discussions about the custom axes and how GF fonts should be generated according to that. So I would like hold the VF for now (until a decision is made) and upgrade in priority the statics.

**Comment by davelab6** [comment]
Thanks Rosalie, please only include the Latin and not the Arabic just yet,
as statics, so this is a more simple bug fixing update
