### ISSUE TITLE
Rubik cyrillic issue

### ISSUE THREAD

**Issue by davelab6** [google/fonts#2836]
> Hello. Rubik at Google Fonts used to look like this: https://t.co/1n9F4umYFt . But now it looks like this https://t.co/dYIWbP6vgH . I used on my website "older" version from Google Fonts which is closer to original https://t.co/RVJQNQOpMv , but now it changed.

@m4rc1e is this a change introduced by the tn weight axis update?

**Comment by thlinard** [comment]
It's the 2016 revision: https://groups.google.com/g/googlefonts-discuss/c/ZD0mTQQVJSc/m/4Hd_CjO1EgAJ

**Comment by m4rc1e** [comment]
Thomas is correct. Previously, we were serving an older version because we tried to update the family in 2017 which included these changes but we broke the internet (remember the VTT issue). Only now has Alexei's modifications (he did them in 2016 in nyc with us) been pushed. TN just made VFs from his work.


cc @alexeiva

**Comment by davelab6** [comment]
Okay, since this wasn't a VF upgrade regression, it was an intended design update.
