### ISSUE TITLE
Update Crimson Text to latest release + add Crimson

### ISSUE THREAD

**Issue by KyleAMathews** [google/fonts#284]
https://github.com/skosch/Crimson

**Comment by davelab6** [comment]
Thanks Kyle!

**Comment by davelab6** [comment]
There are lots of issues in https://github.com/skosch/Crimson/issues so finding a good release candidate will be important :)

**Comment by thlinard** [comment]
"While you are looking at the new, improved version, Google Fonts continues to offer the clumsy-looking original via and has not heeded the repeated pleas for an upgrade. If you want to stick with Google Fonts, I recommend you switch to Amiri in the meantime – it uses the new Crimson for its Roman characters."

**Comment by davelab6** [comment]
@thlinard yes, I know... ;p

**Comment by khaledhosny** [comment]
My version in Amiri is not identical to upstream either, it has many fixes that I committed upstream years ago but got accidentally overwritten after that and the fonts diverged since then.

**Comment by skosch** [comment]
@khaledhosny I do remember you had sorted out most of the OpenType stuff, and probably other things, and then other people's (equally important but evidently corrupted) PRs wiped out much of that effort. With too much on my plate I kind of threw in the towel after that, and I never did apologize for wasting your contributions like that :bowing_man:  (and then over time more and more issues piled up ...)

I'm glad I saw your comment though, because your work on Amiri may be valuable to @m4rc1e and @Fonthausen (in case you missed it, they're improving Crimson for the very purpose of this here issue). I just wanted to point out the potential for re-use of Khaled's fixes and maybe an eventual re-merge.

**Comment by arthurattwell** [comment]
As a regular user of both Crimson Text and Crimson, I'd love to see both versions of the font available on Google Fonts as separate fonts, because they are so very different. We often choose between them for web projects. If Crimson Text were to be updated with the latest Crimson, this would have a significant impact on the design of sites that use it – a breaking change to a designer's eye.

**Comment by davelab6** [comment]
Thanks for that context, I've updated the issue title to reflect that

**Comment by emmamarichal** [comment]
Fixes #4416
