### ISSUE TITLE
How to manage new custom Axes in Variable fonts?

### ISSUE THREAD

**Issue by vv-monsalve** [google/fonts#2846]
I'm working now on a new project which includes a new custom axis ['Sharp'](https://github.com/vv-monsalve/geologisk/blob/QA-Geologisk/fonts/variable/sharp.textproto). My first and short term question would be: are we still including new custom axes in the registry? Or should we freeze all the projects with new custom Axis until it's define how they are going to be handle?

The above leads to a bigger question regarding how custom Axis are going to be managed in the long term as their number is starting to rise.

A quick draft of the current workflow for this subject, including the possible situations along with it, would be:

– **Input:** A source file with design-space information (standard and custom axes plus values)

– **Production process:** Validate the incoming custom axes against the Axis Registry. 

Options:

**a). The incoming axis doesn't match any of the currently registered.**
- Should the new axis be registered?
- If every new axis registered is intended to cover multiple further cases, how should the fallback names and values be determined?
- Can more than one custom Axis share an identical fallback name? E.g., the fallback name `Sharp` is already used by the "[SOFT](https://github.com/google/fonts/blob/master/axisregistry/softness.textproto)" axis.
- How many axes can be registered? Should it be a limit?
- Integration into FB-checks?

**b). There is a registered Axis that matches the function but not the name of the incoming Axis.**

- Change the name of the custom axes in the new source file to match with one of the already registered axes.
- Revision with the designer

**c). There is a registered Axis that matches the function (and name) but not the values or ranges of the incoming Axis.**

- Modify the already registered custom axis according to the new font?
- Force the incoming font to match the current values?

---

There are many factors to take into consideration in every new case, which at the moment makes it a bit time consuming process. There have been some issues and debates on some of these topics.

So the aim of this Issue would be not only to solve this particular `Sharp` axis case but also to discuss the better way to set up a workflow having in mind the new cases yet to come.

cc @m4rc1e @davelab6

**Comment by m4rc1e** [comment]
> are we still including new custom axes in the registry?

Yes but they need approval.

> Or should we freeze all the projects with new custom Axis until it's define how they are going to be handle?

We've frozen Fraunces since we haven't worked out its axis definitions yet so I guess we'd do the same with this project.

> A quick draft of the current workflow

I'd personally just submit a  pr which contains a textproto file for the new axis and cc rsheeter, davelab6 and myself. Even lazier than that, just start a new issue and discuss the axis (its range, fallbacks etc) and we'll collectively decide whether it is worthy.

I'm guessing you're polishing up a commissioned project? for future commissions which include custom axes, **I want us to finalise the axis definitions before the designer starts working on the project**. It's impossible and frustrating for them to work on these projects if we keep changing the definitions or in this case haven't even agreed that it should be included yet. I really don't want another Fraunces situation.

Btw, you can generate a textproto template by running `gftools add-axis`.

**Comment by vv-monsalve** [comment]
> just start a new issue and discuss the axis (its range, fallbacks etc) and we'll collectively decide whether it is worthy.

Done in https://github.com/google/fonts/issues/2849

> I'm guessing you're polishing up a commissioned project? for future commissions which include custom axes, I want us to finalise the axis definitions before the designer starts working on the project. It's impossible and frustrating for them to work on these projects if we keep changing the definitions or in this case haven't even agreed that it should be included yet. I really don't want another Fraunces situation.

Yes, I agree, this is the aim of this Issue. To discuss possible situations we may have in the future regarding custom axis, so that we draw a workflow that supports not only commissioned jobs but also new inclusion proposal to the Catalog, e.g. Issue # 2840

> Btw, you can generate a textproto template by running gftools add-axis.

Yes, thanks, it was included in the first link on the text, @RosaWagner told me about the axis ;-)

**Comment by vv-monsalve** [comment]
P.S. I have other WIP projects that will include new custom axis, and I understand Rosa and others also have other projects with new custom axes.

**Comment by davelab6** [comment]
On Wed, Dec 2, 2020, 12:44 AM Viviana Monsalve <notifications@github.com>
wrote:

> I'm working now on a new project which includes a new custom axis 'Sharp'
> <https://github.com/vv-monsalve/geologisk/blob/QA-Geologisk/fonts/variable/sharp.textproto>.
> My first and short term question would be: are we still including new
> custom axes in the registry?
>

Yes

> Or should we freeze all the projects with new custom Axis until it's
> define how they are going to be handle?
>
We are going to freeze merging their PRs until all the custom axes in all
the families we expect to onboard are in the GF registry.

**Comment by davelab6** [comment]
> I want us to finalise the axis definitions before the designer starts working on the project

The bad news is that we have a lot of families coming out which I commissioned many months or even years ago, and we are going to have to go through a fair amount of bike shedding on the registration process.

The worst news is that I expect it will continue to be the case that the axes **can't** be defined up front, because these kinds of commissions are exploratory, and the designers need to do design work before they even know themselves what the axes definitions and design space topology of their project will be exactly. 

The "good" news though is that currently I'm not expecting to commission any new projects for a few months, and even then, not many. However, that's the commissioned track, and I expect the donation track will continue to see more and more new axes, and the slower we are at engaging with these projects, the more entrenched their axis usage will become, disincentivizing changing or forking for registration.

**Comment by RosaWagner** [comment]
I resume here the process to make it easier. 

1. Submit PR with textproto file for the axis registry with a suggestion of named axis with fallback names and values. Cc Marc, Dave and Rod.
2. Merge the textproto when validated + process it as fonts (sandbox and production)
3. PR fonts with all axes in METADATA.pb

This is better to do before on boarding the font. Even better at the beginning of the project itself. Although, like Commissioner, it happens that the fonts it already in on boarding process. Then, the metadata.pb has to contain only the registered axes, but not the custom ones. It can be then updated with all axes when the textproto file has been pushed to sandbox.

To submit a textproto file, you can use `gftools add-axis` with the font in argument. Then you have to open it and modify the description. Careful though, STAT axis values format 2 is not supported. It means that the textproto file will have accurate fallback positions only if the STAT contains nominal values and no ranges.

Is everything correct ?

**Comment by davelab6** [comment]
Yes I believe so

**Comment by RosaWagner** [comment]
Good. Now the question is

1. do we wait for the textproto to have been pushed to prod to push the font to sandbox?
2. Do we check the font in sandbox with the custom axes before sending the textproto file to prod?
3. It doesn't matter.

**Comment by chrissimpkins** [comment]
> Good. Now the question is
> 
> 1. do we wait for the textproto to have been pushed to prod to push the font to sandbox?
> 2. Do we check the font in sandbox with the custom axes before sending the textproto file to prod?
> 3. It doesn't matter.

From Eng:

The textproto file should be pushed to sandbox, then to production first. There should be a production-ready VF project with the new axis ready to go before a textproto push to sandbox takes place.

The VF asset(s) with the new axis will be pushed approximately one week later and there will be communication with you about the timing of the font asset sandbox push.  A post-production push process must be completed in advance of moving VF's into sandbox.

**Comment by vv-monsalve** [comment]
We have created the [Axis Registry Protocol](https://googlefonts.github.io/gf-guide/axis-registry.html) now. So closing this issue here.
