### ISSUE TITLE
Update Mansalva font to a new version

### ISSUE THREAD

**Issue by carolinashort** [google/fonts#2952]
This update includes 2 sets of alternates, alternates for the numbers, fixes in kerning and additional language support, including Māori.

**Repo**
https://github.com/carolinashort/mansalva

**Font**

<img width="1060" alt="Capture d’écran 2022-05-13 à 11 30 24" src="https://user-images.githubusercontent.com/64773544/168256921-fa3d61f5-0222-4fe4-ba06-1b72633ecc56.png">

**Comment by carolinashort** [comment]
Hi, is there any issue I should address?

Mansalva has been updated again. Now has Latin Plus language support & Latin Plus
diacritics are included.

Font description update (typo): please it should say “Mansalva” instead of “Mansalve”

**Comment by emmamarichal** [comment]
Hello @carolinashort!
I'm Emma, I work with @RosaWagner to onboard font into the Google Fonts library.

I took a look to Mansalva, there are several elements that indicate that the source file is made from an old ttf format (glyph names, export parameters, etc.). This will create some problems for us to export it. 
<img width="745" alt="Capture d’écran 2022-05-19 à 15 16 39" src="https://user-images.githubusercontent.com/64773544/169303098-bb8c0cba-6d32-419f-abc1-278d57a8ae22.png">

So we would need a cleaned source file (especially the glyph names), so that we can proceed with the onboarding.

Thanks,
Cheers!

**Comment by emmamarichal** [comment]
Hello @carolinashort, 

In fact, it seems that the source .glyphs file, is actually a .ttf file that has been converted to glyphs, and this creates a lot of problems, which sometimes can be invisible (problems in the font metadata).

So what I advise you to do is to create a new glyphs file, and copy all the glyphs into it (keep a copy of the old .glyphs file in the repo just in case). Having a clean file will probably avoid bugs. For the parameters in the masters, keep only the vertical metrics:
<img width="474" alt="Capture d’écran 2022-05-26 à 11 28 16" src="https://user-images.githubusercontent.com/64773544/170460584-c6811e96-4b8d-46b3-beef-e33bda85f586.png">
(delete the old parameters: prep Table Assembly, fpgm Table Assembly, cvt Table).

Finally, where you have to be careful is on the names of the glyphs. For example, in the current source file we have "uni2206", but it should be named "increment".
You can already check that the "use custom naming" box is unchecked in font info < others, and then you can do Glyphs < update glyphs info. This will update some names automatically. 

I hope it can work with this technique,
Cheers!

**Comment by carolinashort** [comment]
Thanks @emmamarichal, I will try to work on it. It seems like a long process to recreate all from scratch without losing the work done on the alternates and the different language support, as it was done one by one. I have started but it is laborious. I could try to delete the old parameters and look into the wrong names of glyphs.

**Comment by emmamarichal** [comment]
@carolinashort, I just looked at the file again, and I see that the curves are quadratic curves (this is due to the old converted .ttf), and they should be Cubic curves. You can select all the glyphs and do path > other > convert to cubic.
I invite you to read this article: https://glyphsapp.com/learn/video-drawing-paths

About accents, they should all be made from components, which automatically attach to the letters thanks to the anchors. It will take much less time than doing it one by one. 
You just need to have all your accents ending with "comb", and have anchors on the base glyphs and on the accents.
You can read this, about accents: https://glyphsapp.com/learn/diacritics

Here you can find a video that show how each glyphs should be. As it's an automatic alignment, you should copy the last version in the background (cmd+J). 

https://user-images.githubusercontent.com/64773544/170940631-4e12fb90-ae5c-4b85-a65b-02ea0c8ea9cf.mov

**Comment by carolinashort** [comment]
Thanks again @emmamarichal 
I have fixed some of the issues. The accents were initially created from components but I found that some of the handwritten feel was broken if they were not adjusted manually. Likewise, sometimes I chose a different character as the base letter (a forth alternate for example). When I started Mansalva I was not using Glyphs 3, so I did it following other examples. Maybe it is a wrong approach, I can go back and redo them, from components. Again I truly appreciate your comments and help!

**Comment by emmamarichal** [comment]
Hi @carolinashort, 

Sorry for the late reply. 
I'm not forgetting about the project, I just got back into it. I think the anchor problem can be solved: we'll add anchors to the letters so that the user can use the accents.

I'll keep you posted and give you a PR when it's done. If possible, avoid updating your repo until I give you a PR, it will create conflicts otherwise :)

**Comment by carolinashort** [comment]
Hi @emmamarichal 
I understand what you were telling me. initially, I did all characters from components.  Then I decided to design each character without using components as a design decision because sometimes the accents or macrons end up being too high, or too big comparatively, so I started fixing them one by one. I understand this can be a problem, and I am happy to revert it. I am not touching my repo, although I've fixed the RD as I've missed this comment, sorry :|
