### ISSUE TITLE
Add Vazir

### ISSUE THREAD

**Issue by AlirezaIvaz** [google/fonts#2975]
https://github.com/rastikerdar/vazir-font
Vazir is a Persian/Arabic font.

**Comment by maziyaar** [comment]
best sans serif fonts in Pesrian / arabic fomnt , please add to google font.
thanks

**Comment by ahbanavi** [comment]
There's no good fonts for persian in google docs or google slides.  
We realy need somthing like [Vazir](https://github.com/rastikerdar/vazir-font) or [Estedad](https://github.com/aminabedi68/Estedad).

**Comment by AmiiirCom** [comment]
Add it

**Comment by shabane** [comment]
God will forgive you if you add it :)
I promise that ;)

**Comment by matinabbasi788** [comment]
Yeah

**Comment by Vahidpro** [comment]
Farsi community need this standard font, plese add it.

**Comment by davelab6** [comment]
We can't add it as-is due to licensing issues (the dejavu part isn't OFL and needs to be removed)

**Comment by ghaznavipc** [comment]
Also please add **Sahel** & **Shabnam**! They are awesome!
please please please please 🙏

**Comment by ghaznavipc** [comment]
> We can't add it as-is due to licensing issues (the dejavu part isn't OFL and needs to be removed)

### Author answer/information about this problem (mentioned in the issue part of his github page for this font):
Vazir font has no problem. Of course, they have rights to be strict and I appreciate this myself. The first version of Vazir started with the DejaVu font because at that time I needed a platform. The part where I used the DejaVu font was public domain. There is no longer any connection between Vazir Typeface and DejaVu, and they have all been rebuilt. The only thing left is a series of data tables about letters that are common to all fonts. Like the table in the picture. It was a small initial version of the DejaVu kernel that gradually got bigger and wider, and many more tables were added like the kernings. I don't know what to do with those initial records! maybe I should write exactly the same thing again from the first manually because those are the same in all fonts and I do not know if something that is the same everywhere includes a license or not! even though that DejaVu himself has just said that it is in public domain! For example, in this table it says which glyph is defined at the end of each letter.
![150329995-e101be3b-a8ae-4a10-8d68-52c167e478ad](https://user-images.githubusercontent.com/22493642/150754915-494ac8d1-c7c6-4f3f-8b4f-d616afd48ee4.png)


Anyway, the new version of the Vazir is going to be published with a new name, and in that version, I will explain all of this in detail so that it becomes clear that the Vazir has no problem with the license. I will also answer to that(this) issue later so that there will be no problem.
