### ISSUE TITLE
Latin Extended not supported in Edge and Maxthone

### ISSUE THREAD

**Issue by LuckyMax13** [google/fonts#300]
Hi!

I used Amatic SC from new Google Fonts and Embed it with new link `<link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&subset=latin-ext" rel="stylesheet">` With new link Edge and Maxthone can't display latin-extended characters and using comic-sans.
There is other 'subset' fragment. In new link its `subset=latin-ext` and doesn't work for Edge and Maxthone. When using link with old 'subset' fragment `subset=latin,latin-ext'` latin-extended characters works perfectly for both browsers.

**Comment by davelab6** [comment]
@LuckyMax13 thanks for reporting :) Do any other fonts work?

**Comment by m4rc1e** [comment]
Closing, LGTM in Win 10, Edge 15

![screen shot 2017-06-15 at 11 23 54](https://user-images.githubusercontent.com/7525512/27177102-2478c06e-51bd-11e7-9648-fb5078918bda.png)

Amatic SC was updated after this issue was submitted, #577. This has a new nametable which should rectify this issue.

http://jsbin.com/fejesajeva/edit?html,output
