### ISSUE TITLE
[2016 Encodings] oneinferior should be one.subs

### ISSUE THREAD

**Issue by impallari** [google/fonts#316]
oneinferior should be one.subs
twoinferior should be two.subs
etc....
As per https://www.glyphsapp.com/tutorials/superscript-and-subscript-figures

**Comment by alexeiva** [comment]
thank you, Pablo!

**Comment by alexeiva** [comment]
Hi @impallari , I have looked into this:
We need both oneinferior, and one.subs

* oneinferior >Glyphs autogenerates .subs feature
  * oneinferior will have a unicode value


<img width="188" alt="screen shot 2016-07-11 at 19 50 43" src="https://cloud.githubusercontent.com/assets/16634089/16750594/e20d9c3a-47a0-11e6-8341-c35b78395481.png">


* one.subs > Glyphs autogenerates .sinf feature
  * one.subs will **NOT** have a unicode value


<img width="162" alt="screen shot 2016-07-11 at 19 50 37" src="https://cloud.githubusercontent.com/assets/16634089/16750606/f74a39dc-47a0-11e6-997c-35792edfdd46.png">

Semantically these are two different glyphs, while visually the same.
So I will add additional nine .subs glyphs to GF Pro which can be easily generated via:

```
zeroinferior=zero.subs
oneinferior=one.subs
twoinferior=two.subs
threeinferior=three.subs
fourinferior=four.subs
fiveinferior=five.subs
sixinferior=six.subs
seveninferior=seven.subs
eightinferior=eight.subs
nineinferior=nine.subs
```

@kalapi does this look right to you?

**Comment by alexeiva** [comment]
This will be fixed in patch #319

**Comment by kalapi** [comment]
@alexeiva Here are the pros and cons:

### Adding unencoded variants

#### Pros

1) '.xxxx' (unencoded) variants makes sure that no character level change is possible in the original text (the change takes place when PDFs are generated from apps and browsers, which is why it's a significant concern).

In my opinion, the character level change in this particular case is warranted since it can be argued that the author's original intentions would be to use a semantic inferior numeral but due to the inability to access said character directly from the keyboard they employed the use of OpenType features.

My concern is that in the event where this (converted) text is then copy/pasted from the PDF back into a text editor, and if the font they use does not include an encoded inferior character, it will show up as 'tofu', or in the case of the web, fallback to a font not matching the one in use.

Atleast in the scenario where an unencoded glyph is substituted, the resulting text, after the round trip, falls back to the base character.


#### Cons

1) Adding `.subs` and `.sinf` variants means adding multiple copies of an already existing glyph ('oneinferior' == 'one.subs' == 'one.sinf') creating file size concerns for an already expanded character set.

---

### Postscript:

If we are to add the unencoded variant, we cannot go with your recommended method becuase it's a 'halfway house' in so far as the `subs` feature will continue to affect semantic meaning while the `sinf` feature will not.

We need to add `.sups`, `.subs`, and `.sinf` variants while leaving the encoded superior/inferior glyphs in the font for compatibility with text that contains these encoded characters in the first place.

**Comment by alexeiva** [comment]
@kalapi 

I added `.sups`, `.subs`, and `.sinf` to a font with existing GF Latin Plus:

<img width="382" alt="screen shot 2016-07-12 at 11 10 22" src="https://cloud.githubusercontent.com/assets/16634089/16772200/4cd591d2-4821-11e6-9ca7-fca7f596bf99.png">

Here is how Glyphs app auto-generates OT features:
.subs:
`sub one by oneinferior;
`

.sinf:
`sub one by one.sinf;
`

.sinf:
`sub one by onesuperior;
`
Which means your suggested approach would also require writing the features manually. 
Because of the added time-labour, I suggest we list this method as an `expert level`
in recommendations. 

For Glyphs to auto-generate the features the way we want, we would need to get rid of legacy encoded glyphs 'oneinferior', and 'onesuperior'.

Perhaps for general practice we can use the (compromise) easier method, that is recommend by Glyphsapp? Well, at least for fonts line Creepster Pro/Expert?

/cc @mekkablue any thoughs on this?

**Comment by alexeiva** [comment]
@kalapi, on a second thought, 

1. Default method: use legacy encoded glyphs
Add support for `.sinf` by manually adding this OT feature.

2. Expert Unencoded Method (will be described in the wiki section):
Add duplicate  `.sups`, `.subs`, and `.sinf`, and  then manually write OT code for their support

**Comment by davelab6** [comment]
@alexeiva @kalapi can this be closed?

**Comment by alexeiva** [comment]
@davelab6 I am okay with this. All updates are in my patch.

**Comment by davelab6** [comment]
Okay cool, @kalapi can close this out if he's happy :)
