### ISSUE TITLE
Update Google Fonts API to automatically create Hairline and ExtraBlack static weights?

### ISSUE THREAD

**Issue by cssobral2013** [google/fonts#3319]
So, it can create automatically Hairline and ExtraBlack weights, and allow for 11 weights, up from 9.

**Comment by davelab6** [comment]
@cssobral2013 just came across this while looking for any existing conversations about hairline and extrablack styles; the reason we don't do this is that these styles' OS/2 weightClass values aren't available in legacy systems, so we don't include them in the fvar named instances, nor in the static fonts in the download ZIPs, because we want legacy systems' named styles to match. However, these named styles should be supported in the STAT tables.
