### ISSUE TITLE
Add Homecomputer VF fonts

### ISSUE THREAD

**Issue by davelab6** [google/fonts#3425]
https://github.com/jenskutilek/homecomputer-fonts

Related to #254 by the same designer

**Production notes:**
- [x] Robot QA
- [x] Open issues about (stat, winAscent, license, repo structure, clean up)
- [ ] Designer has fixed the issues
- [ ] New robot QA
- [ ] Visual QA
- [ ] Package fonts
- [ ] Prepare tweet

**Comment by jenskutilek** [comment]
I've added separate issues for the custom axes: #3697 (BLED), #3699 (SCAN)

**Comment by RosaWagner** [comment]
@jenskutilek Do want us to have a call so we update each other on the process?

**Comment by jenskutilek** [comment]
I spent three hours last night trying to "dumb down" the fonts so they fit Google Fonts requirements, but for every reported problem I solve, I keep hitting a new roadblock. I'm slowly getting the feeling that it just isn't worth putting more work into this.

- I had to convert the outlines to cubic even though the original source was drawn with quadratic curves, because otherwise fontmake won't build the static fonts
- I invented new style names for the Bleed and Scan axes, only to have fontbakery complain that they don't fit the WWS requirements (width and weight names really don't apply here)
- Lots more [errors and warnings](https://jenskutilek.github.io/homecomputer-fonts/fontbakery-report.html), most of them for things I had a good reason to do this way (vertical metrics, gasp table).

Everything was fine as it was, now I have two repos with lots of duplicated code and still nothing works…

**Comment by RosaWagner** [comment]
@jenskutilek you don't have to go through this alone. Again, I am happy to have a call to explain the reasons of some requirements, how GF works and which process we apply in which case…

**Comment by davelab6** [comment]
@chrissimpkins noted @simoncozens fork/derivative COLRv1 name "Parallax" has been used by another developer and there are a number of EU trademarks https://namecheck.fontdata.com/?q=Parallax - @jenskutilek would you be willing to take that upstream and release as "Sixtyfour Parallax"?

**Comment by jenskutilek** [comment]
@davelab6 Sure! @simoncozens could you send a PR if you like?

**Comment by davelab6** [comment]
I circled back on this today with @vv-monsalve as we plan the next few months of her time. She will take a look at the issues on your repo that @RosaWagner opened a while back, and possibly PR some changes. @simoncozens is busy this month with an upcoming release but may be able to look in July :)

**Comment by jenskutilek** [comment]
I've updated my repo with current files from the [template repo](https://github.com/googlefonts/googlefonts-project-template), but there are some errors in the GH actions now due to the repo containing two different font families. Please advise whether this poses a problem ... do I have to split the repo again per family?

**Comment by davelab6** [comment]
Thanks @jenskutilek and @RosaWagner :) The gh action isn't immutable, maybe we can send a PR to make it work with 2 families in the one repo.... something for the next weeks :)

**Comment by simoncozens** [comment]
Noto implements multiple families in the same repo, I can working on upstreaming some of its goodness into the googlefonts-project-template.

**Comment by jenskutilek** [comment]
So should I still change the axes to weight and width so that we can go ahead?

**Comment by vv-monsalve** [comment]
Hi @jenskutilek, please take a look at [`BLEED`](https://github.com/googlefonts/axisregistry/issues/17) and [`SACN`](https://github.com/googlefonts/axisregistry/issues/18) axis proposal issues to inspect the latest decisions, plus added question to continue with the onboarding process.

**Comment by chrissimpkins** [comment]
@davelab6 OK to onboard with Latin kernel only?

**Comment by vv-monsalve** [comment]
Considering its historical concept, it was decided to onboard it with Latin Kernel only + Vertical Metrics exception

**Comment by jenskutilek** [comment]
Recent changes brought up some new issues:

- https://github.com/jenskutilek/homecomputer-fonts/issues/21
- https://github.com/jenskutilek/homecomputer-fonts/issues/22
- https://github.com/jenskutilek/homecomputer-fonts/issues/23

**Comment by vv-monsalve** [comment]
The above issues have been discussed and solved. A new one has emerged:

- https://github.com/jenskutilek/homecomputer-fonts/issues/30

**Comment by simoncozens** [comment]
I added another variant font but failed to tell anyone. Carrying on at #6980.

**Comment by vv-monsalve** [comment]
Hi @simoncozens, I'm aware of that font. As said in one of the meetings, we'll onboard the families referenced in this issue first, the "main" B/W fonts, as the colored version was only included recently, and to check the main version's performance before adding this one. 

The colored will still need the QA and font production job in preparation for a PR, which will include registering the new custom Axis + changing the "Color" bit in the name. 

cc @jenskutilek
