### ISSUE TITLE
Add Lexend step 4000: 7 families VF (wght)

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#3453]
https://github.com/ThomasJockin/lexend

- Upgrade Lexend 7 Families (deca to zetta) with a weight axis.
- Since the new Lexend has a different default weight from the 7 Families (regular has become medium), the weight axis mapping can't be the same.

**Production note**
- [x] weight range definition
- [x] export and build
- [ ] package

**Comment by RosaWagner** [comment]
Lexend(New) goes from Thin to ExtraBold. Knowing that in Lexend(7F), Medium is the normal style (therefore Regular), I suggest to reduce the range and have the actual ExtraBold as a Bold. Otherwise the distribution of weigth between Regular and ExtraBold is really different from the one between Thin and Regular.

It would progress like this in the 7 families:
![Capture d’écran 2021-05-28 à 15 41 52](https://user-images.githubusercontent.com/12222436/119992923-53323e00-bfcb-11eb-9f93-5a89d313ad00.png)


Note: this is how it progresses in Lexend(New):
![Capture d’écran 2021-05-28 à 15 40 03](https://user-images.githubusercontent.com/12222436/119992919-50cfe400-bfcb-11eb-8185-167343b6aa75.png)

cc @ThomasJockin @davelab6

**Comment by davelab6** [comment]
I'm not sure about making the weight max the 700, as that will be used a lot via the bold button. 

I'm more comfortable with a medium and semibold that are more similar, so the bold remains the same. 

In Lexend New, the 200 and 300 are very close, in this way, so I suggest to crumple the space there; merge them to allow the 500 to move down to 400.

**Comment by RosaWagner** [comment]
Like this (Thin to ExtraBold)

<img width="834" alt="Capture d’écran 2021-06-08 à 13 43 12" src="https://user-images.githubusercontent.com/12222436/121179072-8abca800-c85f-11eb-82b5-8c928ebf7def.png">

**Comment by davelab6** [comment]
Yes. In some ways I think this could be even better that the current New one... @sannorozco could you explain a bit more the thinking behind that?

**Comment by sannorozco** [comment]
Yes, with Lexend New we went beyond (up and down) to cover all future needs and to be able map stems as GF API needs, It can be calibrated and to match the old Regular (which in my and DB’s opinion is a bit to bold to be Regular)

Lexend New currently serving: 100, 300, 400, 500, 600, 700, 800. Not 200, so it can go? (it’s defined in the designspace but not serving in GF)

Yes, I believe as the latest Rosa’s suggestion works good so old can move to new 400.

**Comment by davelab6** [comment]
(I've assumed each step in all the images above is a +100 move, such that the most recent image is 100 to 800, the one before that is 100 to 700, and the first is again 100 to 800.)

The API requires all 100s within the range of a `wght` axis to exist as named instances, and will be provided as static fonts; Since you are missing 200 in the non-vf family, the API is going to create that, and fontbakery is going to FAIL your VF and require you to add it to the fvar and STAT named instances lists. 

This is the 2nd time this year that a type designer thinks its a good idea to skip the 200 in a static family, and then gets surprised the VF will include a 200 despite that. This suggests that we now need he FB check to be updated to require the same contiguous set of weights from min to max in static font families too, so that we don't see it a 3rd time :)

@rosawagner the Spec probably also needs updating regarding this, you can take anything I wrote in https://github.com/xotypeco/big_shoulders/issues/36#issuecomment-849072666 to help

**Comment by RosaWagner** [comment]
For the VF, the 200 is in the STAT table anyway, and will be in the fvar instances, but it has been forgotten for the static instances.

Also Fontbakery is not failing when an instance is missing in the fvar table, we don't have a check for that yet.

**Comment by RosaWagner** [comment]
<img width="682" alt="Capture d’écran 2021-06-09 à 22 03 42" src="https://user-images.githubusercontent.com/12222436/121421798-d3af5200-c96e-11eb-91fb-ef0ff04fcc51.png">

**Comment by davelab6** [comment]
@RosaWagner reviewed this with me, @dberlow, @sannorozco and Bonnie today and agreed the above schema for all 8 families. 

cc @thomasjockin

**Comment by davelab6** [comment]
And, after those 8 families are published, the next steps are 

* Add Lexend step 2 : VF (wgth, HEXP) #3203

and

* Add Lexend step 3 : Arabic set #3378

**Comment by davelab6** [comment]
> Also Fontbakery is not failing when an instance is missing in the fvar table, we don't have a check for that yet.

Thanks @RosaWagner, I'll file a FB issue about that.
