### ISSUE TITLE
Homenaje font "ç" character problem

### ISSUE THREAD

**Issue by 7Ds7** [google/fonts#348]
There is a problem with the Homenaje font 
https://fonts.google.com/specimen/Homenaje
https://github.com/google/fonts/tree/master/ofl/homenaje

In which the down cased 'ç' character does not render well on Windows, Android or Linux, although it renders fine in OSX, as far as i can tell it is not browser dependant and it is OS dependant.

Editing the font file one can see a duplicated position of the 'c' part

Watch this jsbin on a non OSX system to see the problem http://output.jsbin.com/zevaxoraki/

**Comment by m4rc1e** [comment]
Hey,
What version of Windows?

**Comment by davelab6** [comment]
I can confirm this does not appear on OS X Chrome and does appear on Ubuntu 16.04 Firefox:

<img width="1276" alt="screen shot 2016-08-10 at 1 37 41 pm" src="https://cloud.githubusercontent.com/assets/261579/17563967/b5001904-5eff-11e6-8d2f-c7e7c94f49e6.png">

**Comment by m4rc1e** [comment]
The problem was overlapping contours

![Before](https://cloud.githubusercontent.com/assets/7525512/17586169/3fce4694-5fc0-11e6-83d6-a0c04186db82.png)

I've removed the overlap
![After](https://cloud.githubusercontent.com/assets/7525512/17586174/514080b8-5fc0-11e6-81de-a66882b52fe1.png)

The update will be rolled out soon.

**Comment by 7Ds7** [comment]
Those are great news, thank you very much :)

**Comment by 7Ds7** [comment]
Any updates when this fix is live ?
