### ISSUE TITLE
Add Jetpack

### ISSUE THREAD

**Issue by abhyuday-tripathi** [google/fonts#3561]
https://github.com/abhyuday-tripathi/jetpack

**Comment by davelab6** [comment]
@abhyuday-tripathi lovely! Your repo wasn't updated since initial upload, and while I love your efforts to make the typeface you wanted to see in the world, I don't think this will be popular in Google Fonts. I recommend to submit it to http://fontlibrary.org/ and wish you a beautiful journey into the world of type design :)
