### ISSUE TITLE
Add a CI that checks to_sandbox/production are valid paths

### ISSUE THREAD

**Issue by rsheeter** [google/fonts#3564]
Every once in a while a bad path enters these files. Make it stop.

**Comment by m4rc1e** [comment]
Apologies for this. We already have a [ci](https://github.com/google/fonts/blob/main/.github/workflows/test_server_files.yaml) workflow for this issue. However, it hasn't run in months because we forgot to rename its branch from master to main. It's now fixed, https://github.com/google/fonts/commit/66885185d52ffac3402dc9ed6aa867e3eebd4340
