### ISSUE TITLE
Questions about glyph sets

### ISSUE THREAD

**Issue by davelab6** [google/fonts#366]
@alexeiva and @kalapi, I have some questions about the glyph sets:
- [x] Latin Pro set: There are two sets of numbers for the same function, `.subs` and `.inferior` - should one be dropped from the definition?
- [x] Expert set: Glyphs suggests the name `schwa-cy.sc` instead of `schwa.sc` - and the Glyphs name allows for auto-generation of the `smcp` feature, so perhaps `schwa.sc` should be renamed in the definition?
- [x] Expert set: The glyph `germandbls.sc` is common, but there is also `germandbls.alt.sc` - what is this? Any fonts with this as examples? :)

**Comment by impallari** [comment]
About the .sub .inferiors etc... I have asked something similar in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/googlefonts-discuss/oD-XGBnxnhc/lpCFV_d0DQAJ

Copy/pasted here for quick reference:
- Superiors and Numerators:
  Option 1) one.numr & onesuperior
  Option 2) one.numr & one.sups
  The difference is how Glyph will assign Unicode values.
  We are including all three options in our encoding (one.numr + onesuperior + one.sups).
  We should pick option1 or option2, and remove either onesuperior or one.sups.
  It makes no sense to include them all.
  My vote goes for using Option1, thus removing .sups from “LatinPro Case”
  More info here https://www.glyphsapp.com/tutorials/superscript-and-subscript-figures

- Subscript and Scientific-Inferiors:
  Option 1) one.subs for both
  Option 2) one.sinf & oneinferior
  We are including all three options in our encoding (one.subs + one.sinf + oneinferior).
  We should pick option1 or option2, and remove the unused ones. It makes no sense to include them all.
  My vote goes for Option2, thus removing .subs form “LatinPro” and migrating .sinf from “LatinPro Case” to “LatinPro”
  More info here https://www.glyphsapp.com/tutorials/superscript-and-subscript-figures

Alexei answered there, that the matter have already been discussed, but I still think they are getting it wrong (probably because the Glyph's blog post about the issue is a bit confusing. I have to read it quite a few times). For example, for the Subscript and Scientific-Inferiors, we can choose to have:
- ONLY .subs unencoded glyphs (using the same glyphs for both OT features) 
- OR .sinf unencoded glyphs + *inferior encoded glyphs. (one for each OT feature, semantically correct but bigger/cumbersome font files).
But currently we are using .subs + *inferior (a combination that does not make sense IMHO, at least according to what I understand from the glyph blog post, unless I get it wrong too).

**Comment by josescaglione** [comment]
Anything about this:

 Expert set: Glyphs suggests the name schwa-cy.sc instead of schwa.sc - and the Glyphs name allows for auto-generation of the smcp feature, so perhaps schwa.sc should be renamed in the definition?

**Comment by josescaglione** [comment]
About inferiors my recommendation is:
ONLY one nomenclature and unencoded glyphs (using the same glyphs for both OT features)

**Comment by alexeiva** [comment]
@davelab6 
`germandbls.alt.sc` is a rudimentary entry, should be renamed to `germandbls.calt.sc` and moved to the recommended section. It is required alongside 'germandbls.calt' to enable switching from 'ß' 'lc' to 'uc' according to [glyphs tutorial](https://www.glyphsapp.com/tutorials/localize-your-font-german-capital-sharp-s):

`Germandbls=germandbls.calt`

@josescaglione thanks for the input. I agree `.subs` and `.inferior` should be just `.subs`
  
> Expert set: Glyphs suggests the name schwa-cy.sc instead of schwa.sc - and the Glyphs name allows for auto-generation of the smcp feature, so perhaps schwa.sc should be renamed in the definition?

What are the steps to repro this issue? I generated a new `schwa.sc` and Glyphs didn't change it after `update glyph info`. It passes the legal names test too.

I believe can be encountering a glyphs bug. According to `glyphsdata.xml` these are two different unicode spots, and are not interchangeable. 

```
<glyph unicode="0259" name="schwa" sortName="sz" category="Letter" subCategory="Lowercase" script="latin" production="uni0259" description="LATIN SMALL LETTER SCHWA" />
<glyph unicode="04D9" name="schwa-cy" sortName="cy195" category="Letter" subCategory="Lowercase" script="cyrillic" production="uni04D9" altNames="afii10846, schwacyrillic" description="CYRILLIC SMALL LETTER SCHWA" anchors="top" accents="dieresiscomb" />
```

**Comment by alexeiva** [comment]
So instead of two methods we stick to one. It will require manually copying code for `sups` and `sinf` features. 

feature name | created | sub one by ...
--- | --- | ---
`sups` | manually | `one.sups`
`subs` | auto | `one.subs`
`sinf` | manually | `one.subs`

**Comment by davelab6** [comment]
@m4rc1e please can you make sure your script takes care of checking the manual code is in place?

**Comment by davelab6** [comment]
@alexeiva

> should be renamed to germandbls.calt.sc and moved to the recommended section

Please make it so :)

**Comment by alexeiva** [comment]
@davelab6 
> Expert set: Glyphs suggests the name schwa-cy.sc instead of schwa.sc - and the Glyphs name allows for auto-generation of the smcp feature, so perhaps schwa.sc should be renamed in the definition?

Both `schwa` and `schwa-cy` are correct. Perhaps this was an old Glyphs bug. 
Here is a sample from [Vollkorn](https://github.com/FAlthausen/Vollkorn-Typeface/).
<img width="571" alt="screen shot 2017-01-10 at 12 36 45 am" src="https://cloud.githubusercontent.com/assets/16634089/21788032/ea7ee20a-d6cc-11e6-9de5-7b1871cbe93e.png">

**Comment by alexeiva** [comment]
> should be renamed to germandbls.calt.sc and moved to the recommended section
> Please make it so :)

@davelab6 This has been fixed

**Comment by alexeiva** [comment]
I have made the amends for number sets in this branch
https://github.com/google/fonts/tree/glyphsets-update/tools/encodings/GF%202016%20Glyph%20Sets

**Comment by davelab6** [comment]
@alexeiva awesome! I made a PR for that branch, https://github.com/google/fonts/pull/571 - pls merge when ready :)
