### ISSUE TITLE
STIX Two Math: math rendering is broken

### ISSUE THREAD

**Issue by fred-wang** [google/fonts#3773]
cc @tiroj @RosaWagner  @vv-monsalve  @thlinard @bkardell 

Follow-up of https://github.com/google/fonts/issues/530 and https://github.com/google/fonts/pull/3304 

The following page uses the CSS suggested on https://fonts.google.com/specimen/STIX+Two+Math ; try opening it in Chrome Canary (with the experimental web platform features enabled), Firefox or Safari:

https://people.igalia.com/fwang/mathml-stix-two/google-fonts.html

It should render the same as this version, which uses the WOFF2 files provided by the STIX fonts project:

https://people.igalia.com/fwang/mathml-stix-two/math-fonts.html

Currently that's not the case. I guess Google fonts split the fonts into smaller chunks to speed up download or maybe filter out some data, and we lose some code points, glyphs or information from the MATH table.

**Comment by twardoch** [comment]
GF subsets the fonts it serves, which works well for many fonts but does not for math fonts which rely on the MATH table and all glyphs being present. 

I think it's sensible to delist the STIX Two Math font (but keep STIX Two Text) for now.

**Comment by tiroj** [comment]
So the GF served font may be structurally different from the GF downloadable font? Ack.

**Comment by twardoch** [comment]
You mean the webfonts? Sure, GF-served webfonts are typically not one solid WOFF2 but instead subsets that the browser assembles into a font stack. This mostly works and massively reduces load time because the browser only loads the subset it needs to render the current page. For CJK fonts this is pretty much a mandatory approach. 

But with GPOS, it becomes complicated and with something like MATH, well, it never works. 

The GF eng team is aware of the limitations of the current approach and I imagine they'll be working on a more flexible system. I think some fonts could be flagged in the metadata as not-to-be-subsetted/sliced.

**Comment by RosaWagner** [comment]
Stix Two Math got de-listed.
