### ISSUE TITLE
Manrope removed Vietnamese characters?

### ISSUE THREAD

**Issue by giang** [google/fonts#3863]
Hello,

I remembered that Manrope font supported Vietnamese, but now when I'm trying to add to my website and Vietnamese characters supported have been removed?

I checked the original author repo and his font is still supported Vietnamese.

Why remove it from Google Webfonts?

**Comment by RosaWagner** [comment]
Hi
Thanks for reporting. Google subsets the fonts they serve by following a file that lists the supported glyphsets. This file is missing the Vietnamese set — probably because of some combining diacritics that are missing in the fonts. 

Until we fix this, you can download the font directly et self-host (the Vietnamese characters will be in the version you download).

**Comment by thlinard** [comment]
I don't see any glyph missing in https://fonts.google.com/specimen/Manrope?preview.text=Do%20b%E1%BA%A1ch%20kim%20r%E1%BA%A5t%20qu%C3%BD%20n%C3%AAn%20s%E1%BA%BD%20d%C3%B9ng%20%C4%91%E1%BB%83%20l%E1%BA%AFp%20v%C3%B4%20x%C6%B0%C6%A1ng&preview.text_type=custom

Maybe a subset missing in METADATA.pb?

**Comment by thlinard** [comment]
On the other hand, the version served by the API is 4.501, where ₫ is missing and º ª wrong. The version here is 4.504 which fixes this.
