### ISSUE TITLE
Change GF Axis Registry `wdth` from `Normal` to `Medium`?

### ISSUE THREAD

**Issue by eliheuer** [google/fonts#4058]
This issue was suggested in a Fontbakery issue here: https://github.com/googlefonts/fontbakery/issues/3505

The [GF Axis Registry](https://github.com/google/fonts/blob/main/axisregistry/width.textproto#L26) has `wdth:100` set to `Normal`, but in the [OpenType docs](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#uswidthclass) `Medium` is the default, and in Glyphs App `Medium` is also the default(it is not easy to change `Medium` to `Normal` in the Glyphs UI).

<img width="308" alt="glyphs-medium" src="https://user-images.githubusercontent.com/5162664/141389144-8111d63b-ccd6-4aa4-88cd-af047776c74b.png">

In the GF spec `wdth:100` is blank: https://googlefonts.github.io/gf-docs/Spec/

**Comment by eliheuer** [comment]
I notice fonts like [Truculenta](https://github.com/Omnibus-Type/Truculenta) use `Medium` and I don't see any custom parameters or anything like that changing the entry to `Normal`.

**Comment by RosaWagner** [comment]
The axis registry is to build the instance names, and the STAT table has to be consistent with it.

Width Class is a parameter in the OS/2 table, it can be called Medium or in the opentype Spec in Glyphs or wherever, but at the end it just will be a value in the OS/2 table: `<usWidthClass value="5"/>`. This is not where you set up the instance name or the values in the STAT table.

"Normal" width (100) is supposed to be elided, so the Normal/Medium width (or whatever it is called) won't appear in the instance name. So as a matter of fact, it is not supposed to matter much how this value is named. But GF wants consistency in naming schemes, even for elided values. I guess decision was for "Normal" to not confuse with Medium weight style in naming composition if this value would not be elided for whatever reasons (otherwise we would have "Font Name Medium Medium". 

If you look at Truculenta; the STAT table and the instance name scheme follows these guidelines.
