### ISSUE TITLE
Not all fonts are available on google fonts

### ISSUE THREAD

**Issue by johnoseni1** [google/fonts#4070]
like i was told to use a calibri font by a client of mine, just to get to know that google fonts doesn't have that, that could be resolved right?

**Comment by fitojb** [comment]
Calibri’s license is proprietary, so it is of course not available on Google Fonts.

**Comment by davelab6** [comment]
I wish I knew how to solve this, but I don't, so I'm closing the issue :)

**Comment by tphinney** [comment]
Just in case the original poster doesn’t understand…
Google Fonts is not a search engine for fonts. It is not all the world’s fonts. It is instead a curated collection of libre-licensed fonts.

In order to be available through Google fonts, a font needs to be available under a libre license, and to pass certain quality checks. And there are still other considerations!

So, “not all fonts are available on Google Fonts” is… to be expected.
