### ISSUE TITLE
Xolonium font family for your consideration

### ISSUE THREAD

**Issue by sevmeyer** [google/fonts#413]
Source: http://gitlab.com/sev/xolonium
Release: http://fontlibrary.org/font/xolonium

Xolonium originated as a custom font family for an open-source game in need of a futuristic font. Subsequently, I have made it available as a stand-alone release, and it found use in other projects as well.

Because the latest release finally includes a hinted ttf version, this should be a good time to make you aware of its existence, and offer Xolonium to be added to Google fonts.

If there is indeed interest, I can create a Google+ account and submit the required CLA.
Cheers

**Comment by davelab6** [comment]
@severinmeyer thanks for submitting this! I'll get another type designer to give it a design review (perhaps @alexeiva since it has Cyrillic) and a font engineer (perhaps @m4rc1e) to look at its internals. The inkscape/fontforge build process is unusual :D

**Comment by severinmeyer** [comment]
@davelab6 Great to hear, thanks! Note that I give Inkscape credit because I used it in part for the creation and review of the outlines. However, it is not a depency for the build process.

The build process is fairly standard. Python scripts use FontForge and FontTools to load the outlines from `sfd` files, add kerning and features from `fea` files, and perform some cleanup.

The only unorthodox part is the creation of the TrueType instructions. They are written in a custom format and translated to optimized bytecode by a dedicated [compiler](http://gitlab.com/sev/htic), which is implemented in Python as well.

**Comment by davelab6** [comment]
I think this family is deprecated by https://fonts.google.com/specimen/Oxanium :)

@sevmeyer thanks for both great contributions!
