### ISSUE TITLE
Add Sai Sans ttf font

### ISSUE THREAD

**Issue by SaiCorporation** [google/fonts#4242]
**Font Project Git Repo: [Over here!](https://github.com/SaiCorporation/Sai-Sans-S-font)**

**Super short description of the Font Family: A simple and unique font based on real handriting**

**Requirements:ttf**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [ ] If the font targets latin based written languages, it supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/Lib/glyphsets/encodings/GF%20Glyph%20Sets/GF-latin-core_unique-glyphs.nam)
- [x] I read and agree with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [ ] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [x] I will maintain the repository

**Comment by RosaWagner** [comment]
Hi, the font and the repo don't respect some of the necessary requirements (I untick some of the cases accordingly). Your project is still not ready for publication on google fonts due to missing glyphs and license file (among other design issues). But continue your work and re-open this issue when your project is ready :) 

-> Make sure you read all the linked documents above and comply to the requirements before submitting.
