### ISSUE TITLE
SIL fonts onboarding (Summary)

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#4354]
See if we onbaorded all these fonts, and create issues for the missing ones (and then link issue here)

**Most important:**
- [x] #4369
- [x] #3756 
   - [x] de-list Andika New Basic
- [x] #3757 
    - ~Charis SIL Compact~
- [x] #3755
    - [x] de-list Gentium Basic
    - [x] de-list Gentium Book Basic
    - [x] Add Gentium Book Plus
    - [x] Add Gentium Plus
    - ~Gentium Plus Compact~
    - ~Gentium Book Plus Compact~
- [x] #2509
- [x] #4424

**Next priority:**
- [x] #4420
- [x] #4421
- [ ] #4512
- [x] #4514
- [x] #4515
- [x] #4516
- [x] #4517
- [ ] #4518
- [x] #4520
- [x] #4834 
- [x] #6190
- [x] #6189
- [x] #6188
- [x] #5243 
- [x] #6463
- [ ] #6493
- [x] #6496
- [x] #6494

**To not onbaord**
cf https://github.com/google/fonts/issues/4354#issuecomment-1079066885
- Apparatus SIL
- Awami Nastaliq
- Bosa
- Bosa Lisu
- CR Udom
- Dai Banna SIL
- Doulos SIL (#5797)
- Doulos SIL Compact
- Ezra
- Galatia SIL
- Kay Pho Du
- Kyebogyi
- Khmer Busra
- Khmer Mondulkiri
- Khmer Oureang
- Khmer Ratanakiri
- LisuTzimu
- Namdhinggo SIL
- Nastaliq Navees
- Nokyung
- Payap Lanna
- Salaowu
- Sapushan
- Scheherazade (replaces by Scheherazade new)
- ShiShan
- Sophia Nubian
- Tagmukay
- Taogu
- Zaghawa Beria

**Comment by jvgaultney** [comment]
Many of these fonts probably shouldn't be on Google Fonts as they are old and no longer maintained, have been replaced by other fonts, or are still pre-release. Our suggestion would be that you consider adding these with the following priority:

Most important:
- Abyssinica
- Andika
- Charis SIL
- Gentium
- Harmattan
- Scheherazade New

Next priority:
- Akatab
- Alkalami
- Annapurna SIL
- Ezra SIL
- Mingzat
- Narnoor
- Padauk
- Padauk Book
- Shimenkan
- Tagmukay
- Tai Heritage Pro

All the others are either old or pre-release, so they can be ignored.

**Comment by jvgaultney** [comment]
For all fonts please use the releases. All the ones I mentioned are currently ready, although some have further releases planned in upcoming months. Thanks!

**Comment by RosaWagner** [comment]
thanks @jvgaultney, do you mean Harmattan and Scheherazade New have been upgraded since we onboarded them?

**Comment by jvgaultney** [comment]
Harmattan has not - sorry about that. Sch New is now at v3.300.

**Comment by jvgaultney** [comment]
Ignore "Tai Heritage" - only have "Tai Heritage Pro"

**Comment by jvgaultney** [comment]
Sorry - another change - please *do* include Nuosu SIL.

**Comment by jvgaultney** [comment]
Not at the moment. Details:

Awami Nastaliq - requires Graphite technology and doesn't support OpenType so can only work with Firefox
Dai Banna SIL - due to be restructured as an axis-based family soon so we'd not want people to use the current ones as web fonts
Doulos SIL - we support this for legacy reasons but have no intention of promoting it as a good web font
Namdhinggo - v3 in final testing now as a restructured axis-based family so expect a request from use in a few weeks but not now

**Comment by thlinard** [comment]
Thank you for the details, specially for Doulos, I wasn't very sure.

**Comment by chrissimpkins** [comment]
I left comments on each of the open issue threads.  Let's understand where things are with development on any issues that blocked onboarding over the last several months so that we can schedule these projects.

**Comment by jvgaultney** [comment]
I have updated the separate issues for the remaining four fonts on the list (Shimenkan, Akatab, Annapurna, Narnoor) all of which are pending releases from us over the next few months. Longer-term there are more fonts to be onboarded, some that have been discussed, others that are new. Some of them are waiting for the SIL-Google RFN agreement to be amended to include them, which we hope to do in the next few weeks. We'll create new onboarding issues for those fonts when they are ready and after the RFN agreement has been updated.

**Comment by chrissimpkins** [comment]
Thank you very much for all of this information Victor!  Please let us know when you have a better idea of the Shimenkan, Akatab, Annapurna, Narnoor schedules.  I am planning our onboarding schedule and it will be helpful to understand when you anticipate that the releases will land.  No rush.  Thanks!

**Comment by jvgaultney** [comment]
Our guess at upcoming releases:
- [Akatab](https://software.sil.org/akatab/) (Q4CY22 - this quarter)
- [Kay Pho Du](https://software.sil.org/kayphodu/) (will add bold weights in Q1CY23)
- [Annapurna SIL](https://software.sil.org/annapurna/) (Q1CY23)
- [Narnoor](https://software.sil.org/Narnoor/) (Q1CY23)
- [Nokyung](https://software.sil.org/Nokyung/) (Q1CY23)
- [Shimenkan](https://software.sil.org/shimenkan/) (Q1 or Q2 CY23)

There are also a few others that would be pending an update of the RFN agreement because the names are new or changed:
- [Namdhinggo](https://software.sil.org/Namdhinggo/) (already released under updated name)
- [Dai Banna SIL](https://software.sil.org/daibanna/) (already released under updated name)
- [Ruwudu](https://software.sil.org/ruwudu/) (already released, but will add bold weights in Q1CY23)
- Lisu Bosa (Q1CY23)
- BJCree (Q1 or Q2 CY23) - UCAS project, maintenance being transferred to us

**Comment by chrissimpkins** [comment]
Thank you very much Victor!

@RosaWagner Pushed the milestone back to Q2 2023 based on Victor's input above.

**Comment by jvgaultney** [comment]
Latest update on fonts that are ready to be onboarded and upcoming releases:

Here is a list of the fonts that we can now onboard with the new RFN agreement in place. We've made new GF issues for each. Some of them are scripts that GF doesn't yet support, so let us know if you need additional material such as sample texts.

- [Ruwudu](https://github.com/google/fonts/issues/6463) - West African style of Arabic script
- [Namdhinggo](https://github.com/google/fonts/issues/6493) - Limbu script
- [Dai Banna SIL](https://github.com/google/fonts/issues/6494) - New Tai Lue script
- [Lisu Bosa](https://github.com/google/fonts/issues/6496) - Lisu (Fraser) script

Here are some of the anticipated releases and updates in the next few months, although the dates often change:

Q3 2023
- Kay Pho Du (new to GF - Kayah Li script)
- Narnoor (v3 update with more weights)
- Annapurna SIL (new to GF - Devanagari script)
- Nokyung (new to GF - New Tai Lue script)

Q4 2023
- Charis SIL (v7 update with more weights)
- Gentium Plus (v7 update with more weights)
- Andika (v7 update with more weights)
- Shimenkan (new to GF - Miao script)
- Busra (new to GF - Khmer script)
- Padauk (v5.1 update)

Q1 2024
- Dakdam (new to GF - Khmer script)
- BJCree (new to GF - subset of Canadian Syllabics)
- Akatab (v4 update)

There are some larger projects in the works but we're not yet ready to announce them.

**Comment by emmamarichal** [comment]
@jvgaultney 
Thanks a lot for this update Victor!
I put these issues in the queue :) I'll tell you if I have any questions!

**Comment by simoncozens** [comment]
We have reliable text samples for Limbu and New Tai Lue, but I am unconvinced about our Lisu sample so if you have any sample text I would appreciate it!

**Comment by jvgaultney** [comment]
Here is a short Lisu language sample text - it is a book title "How to prevent many health problems":

ꓠꓻ ꓟꓽ ꓔꓳꓹ ꓜꓳꓽ ꓕꓯꓽˍ ꓡꓰ ꓤ ꓟꓳ ꓢꓲ ꓮ ꓡꓲ ꓐꓰ ꓗꓽ ꓔ ꓠꓯꓹ ꓟ 

The text is openly licensed as one of the test texts in the Lisu Bosa project. There are also longer texts there.

**Comment by simoncozens** [comment]
Thank you. Looking at this, I think the sample text that we have for Lisu (which I now realise was probably taken from @r12a's [sample text website](https://r12a.github.io/scripts/samples/index.html?script=lisu#result)) could well be fine. I was unconvinced because I thought that, with the words being so short, it might just be a collection of letters... but it seems like Lisu words just are very short. So I think we shall be OK with the current text, but thank you anyway!

(@r12a: Do you know where you got your Lisu UDHR translation from? Your site quotes Unicode.org and Omniglot, but neither of those seem to actually have Lisu translations, which is another thing which was making me nervous about the sample... Please cite sources where you can!)

**Comment by r12a** [comment]
@simoncozens it was taken from https://www.evertype.com/standards/iso10646/pdf/fraser-sample.pdf

Thanks for pointing out the lacking source, i'll fix that.

**Comment by chrissimpkins** [comment]
Closing.  Let's open per family trackers for any outstanding onboarding that exists in this summary thread.
