### ISSUE TITLE
Spartan font is missing!!

### ISSUE THREAD

**Issue by DiegoR1988** [google/fonts#4495]
I am using this font in Bubble.io to create applications, and today i realized that the font was missing (https://fonts.google.com/specimen/Spartan), is it a bug?

**Comment by davelab6** [comment]
No, we delisted that family as we prefer the family League Spartan, which
you should find.

**Comment by ol2015101022** [comment]
What do you mean by "we deleted"? There are thousands of web sites using Spartan font. Why did you delete it? League Spartan is nowhere near it.

**Comment by RosaWagner** [comment]
Spartan is not deleted, it is de-listed. It means websites using it are still served with it, but GF is not showing it on its platform anymore because of too numerous bugs. League Spartan is the upgraded version of Spartan that is offering a broader glyphset and fixing former Spartan’s issues.

**Comment by mojzesz777** [comment]
and so what if when you enter the edition, you will not select this font anymore because it is only "new". absurd. I have 5 pages for clients in this font myself and now I will have to change the whole thing because until then I have support in Spartan and the new content will be in a different font. And so what if it is improved if it looks different from the pattern.

**Comment by m4rc1e** [comment]
@mojzesz777 If you disagree with our decisions, just host the fonts yourself. Here's a link to the previous Spartan, https://github.com/bghryct/Spartan-MB/tree/gfdev

**Comment by mojzesz777** [comment]
that's all I have left
