### ISSUE TITLE
Add Sono

### ISSUE THREAD

**Issue by davelab6** [google/fonts#4625]
https://github.com/sursly/sono
<img width="1697" alt="Capture d’écran 2022-05-27 à 14 09 16" src="https://user-images.githubusercontent.com/64773544/170696555-c68b432b-2d6d-4808-a2a5-40736545be68.png">

**Comment by RosaWagner** [comment]
What Marc did for Cormorant is not something we want to expand to other families ^^. It was very time consuming and non-standard — unfortunately necessary in that case because otherwise we couldn't onboard the different families at all. But in the case of Sono, it looks like a small stylistic substitution happening only on the static fonts, so it doesn't seem like a good idea to spend so much time on being able to export them with the substitution if we don't even onboard them.

Please proceed to export only the variable font; I am sure Tyler won't see as an inconvenience to export statics with Glyphs for his own repository, or to remove the rename glyph substitution to be able to export it all with fontmake.

**Comment by emmamarichal** [comment]
Okay, I'll do that, thanks!

**Comment by RosaWagner** [comment]
**Memo:**

The MONO axis in this project has been thought from Mono to Proportional, which is the opposite of GF mono axis definition. 

In order to redefine the default value to 1 (Monospace) instead of 0 (Proportional), we shall add to METADATA.pb:

```
registry_default_overrides {
  key: "MONO"
  value: 1
}
```

And we also should check in dev sandbox if the zip file generates correctly before pushing to sandbox. If this test fails, then we shall ask the designer if they would agree to go with GF mono axis definition; from proportional to monospace.
