### ISSUE TITLE
Documentation: Explain why we don't support Subresource Integrity

### ISSUE THREAD

**Issue by chris-griffin** [google/fonts#473]
I would like to suggest implementing [Subresource Integrity (SRI)](https://w3c.github.io/webappsec-subresource-integrity/) support for Google Fonts. This will inevitably require adding some type of versioning to the stylesheets which I know is at odds with the original intentions of using a non-versioned stylesheet to allow for seamless versioning of the actual .woff2 files. Perhaps using a versioned stylesheet could be an option for sites that require a higher degree of security?

**Comment by davelab6** [comment]
@chris-griffin good question! I'll circulate this issue with the GF engineering team and see what they say :)

**Comment by chris-griffin** [comment]
Thanks @davelab6

**Comment by tedmiston** [comment]
Just here for the +1.

@davelab6 Do you have any feedback from the GF team about SRI support?

**Comment by davelab6** [comment]
Hmmm.... the CSS returned by the GF API is different for different browsers... Could you be more specific about how you would like the GF API to work?

**Comment by chris-griffin** [comment]
@davelab6 yes, it is an interesting problem when the response changes depending on the browser/user-agent. A couple questions:

1. Do you know if the dynamic response is for performance or functionality?
2. What happens currently if no user-agent/browser is provided in the request?

If the dynamic css response is for better performance, then I would suggest adding 2 optional GET parameters: dynamic=x and version=x.x. This would ensure a consistent response, and allow high security websites to utilize Google Fonts.

**Comment by davelab6** [comment]
> Do you know if the dynamic response is for performance or functionality?

I personally see both aspects. 

Anyone can observe that if you use a Windows UA string, the fonts in the font-face URLs returned contain truetype hints, and if you use a Android/Apple UA string, the font files do no contain hints (which can be up to half the filesize); the latter platforms simply don't use them, so they are not included. I personally see that as performance related. 

And similarly, some UA strings return WOFF or WOFF2 urls, and others return TTF or EOT; and some return all subsets with unicode-range data, others return only the subsets requested in the API url. I personally see that as functionality related. 

> What happens currently if no user-agent/browser is provided in the request?

Anyone can observe that if you use no ua string, you get (non-woff) TTF fonts - which is optimal for almost no browser left today, but still works :) 

> allow high security websites to utilize Google Fonts

Since all gf fonts are libre licensed, such websites can self-host, losing out on the above optimizations, but getting total control and url-content stability to make SRI easy :)

**Comment by chris-griffin** [comment]
@davelab6 yup, we are self-hosting currently for sensitive areas. I'm hoping you'll reconsider this issue in the future as SRI gets larger adoption.

**Comment by wagey** [comment]
Is this issue still being looked into? I really hope it's considered.

**Comment by davelab6** [comment]
The Fonts API has a dynamic response both for performance or functionality; the suggested action here is to introduce versioned stylesheets as an option for sites that require a higher degree of security, but this would complicate the product, so it won't happen.

**Comment by davelab6** [comment]
Actually I'm going to keep this open as a documentation issue :)

**Comment by xCASx** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity#Using_Subresource_Integrity

> An integrity value may contain multiple hashes separated by whitespace. A resource will be loaded if it matches one of those hashes.

If a single font may have a few permutations it should be possible to generate a list of SRI hashes one per each possible permutation. Integrity may be achieved by setting the corresponding list as a value of integrity attribute.
Isn't it a solution for the problem?

**Comment by fulldecent** [comment]
@xCASx Could I please bother you to ask for an example of your proposal?

Here is one link I found on my site:

https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800

What would be the updated multi-SRI link for that? And does SRI even work in this circumstance where an SRI link is itself loading assets from a non-SRI link?

**Comment by xCASx** [comment]
@fulldecent with SRI you can check integrity of css itself. As far as I know there is no mechanism for checking integrity of `@font-face` source.

Here is an example how it could look like for 'Open Sans' font:
https://codepen.io/anon/pen/yZagZE

You may see that there are two different hashes defined in `integrity` attribute. One for Windows another for Mac OS. Here is how they were calculated:

```bash
$ curl -s -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36" https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800 | openssl dgst -sha384 -binary | openssl base64 -A | xargs -I {} echo 'sha384-'{}
sha384-mlP+AoH67RkQHyYnTc8d+1ch+vqMSH7aflgofbhqI/oSUSrRkk/OPK8FUYynSaLT
$ curl -s -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800 | openssl dgst -sha384 -binary | openssl base64 -A | xargs -I {} echo 'sha384-'{}
sha384-qoFP86ZH0+LeSBfGOBS/VD8KegDs8GfA7UDEM488w8LGZJ7wPKR/xZsBj7yroXZz
```

This is how we may generate hashes for all possible css permutations, but there are way too many possible `User-Agent` combinations: https://developers.whatismybrowser.com/useragents/explore/ and only Google developer team knows how this css is generated (which parts of User-Agent it depends on).

**Comment by fulldecent** [comment]
@xCASx Thank you! If the upgrade is as simple as the CodePen you shared then this will be a very easy upgrade and I can finally solve all those "no SRI" validator errors on my website!

**Comment by twiggy** [comment]
Old ticket, but one solution is to just download the style sheet server side overriding the user agent with that of the browser. Take the content and pass it inline in a style tag. I'm not sure if the user agent is the only thing that drives the content, but that appears to be the case today according to Google Fonts docs.

Here is some pseudo-ish python code using Python's requests http client/library. The HTTP_USER_AGENT is the one I get from the browser and so sort of proxy it along.

Depending on your load caching would probably be pretty important.

```
style_headers = requests.utils.default_headers()
style_headers.update({'User-Agent' : request.environ.get("HTTP_USER_AGENT","")})
font_style = requests.get('https://fonts.googleapis.com/css?family=Patrick+Hand|Ubuntu:400,700', headers = style_headers).text

<style>
${font_style}
</style>
```

Since the style tag is inlined there is no need for a SRI/integrity attribute to be added to a link tag. I'm not sure if the style tag will result in different browser behavior's though? Less packets/sockets from the client as well.

**Comment by eyeinsky** [comment]
> Old ticket, but one solution is to just download the style sheet server side [...]

I think people already know this (and with a downloaded stylesheet you can add SRI to the static copy on your server instead of inlining it). The problem is that this stylesheet won't be optimized to the user-agent who's browsing your site.

A solution would be to enumerate all the optimized variants and publish the hashes of those, but this would probably mean starting to version the fonts because any time the CSS changes everybody needs to update their SRIs, too. But perhaps this (versioning) wouldn't be such a bad idea?

**Comment by mattborja** [comment]
I would also like to see support for SRI come to Google Fonts.

A possible workflow that comes to mind is the use of release signing keys (i.e. RHEL, et. al.) for the vendor deploying signed package updates and consumers pulling updates and verifying them using the package manager's tool chain (i.e. signer's public key verified and trusted once for verifying all future updates).

Now, how you ship package management protocol into a browser is another story. Howbeit, it ought not to be too impossible, considering it's the parent site that trusts the vendor's signing key (not the user) and perhaps with a little bit of JS as the forerunner, we could still achieve the same thing.

Maybe I should work on a proof-of-concept. I'm kind of liking where these thoughts are going...

**Comment by rsheeter** [comment]
Our response can vary by UA and OS (including version). OS matters due to browser delegation of text rendering to the OS. For example, Firefox variable font support on Windows (https://bugzilla.mozilla.org/show_bug.cgi?id=1403299).

IIUC SRI requires features that significantly degrade the value of our service:

1. Version pinning
   * This complicates our ability to update as new web tech rolls out.
   * For example, we were able to deploy woff2 at scale just by updating our response.
1. A response safe to use across many versions of many browsers on many versions of many OS
   * We get reduced capability and larger responses
      * back to the good old days; https://www.paulirish.com/2009/bulletproof-font-face-implementation-syntax/
      * Some features will be limited to whatever the lowest common denominator is; rolling out new capabilities like https://developer.chrome.com/blog/colrv1-fonts/ would be more difficult. Maybe they just wouldn't work for SRI users.
 
That doesn't mean it can't ever happen, just that when we have to choose where to put our resources thus far they have gone elsewhere. For example, at time of writing we are trying to help get https://w3c.github.io/IFT/Overview.html done.

**Comment by matthewstick** [comment]
are they going to add this?

**Comment by eyeinsky** [comment]
> are they going to add this?

There are good reasons listed above why they are not going to add this. But if you do want it, download the font and serve it locally (through a CDN) with an SRI. Won't be the optimal font for all of your users though.

**Comment by davelab6** [comment]
I think @eyeinsky makes a fair appraisal of the situation, @matthewstick :) Therefore I'll close the issue to signal that the answer is "no" :)

**Comment by vilocity-aaron** [comment]
Just adding another opinion to this for balance. I, too enjoy "checking every box" and getting a green 100% score on every security/performance/etc test that can be run on a website... but sometimes this causes us to make poor tradeoffs just to chase a score.

Google Fonts serves CSS files. The likelihood of a MITM or a breach at Google using that CSS content to inject malicious content into our websites is about 0%. While it might be nice to get that shiny green 100% score on some security tool you're running, the trade-off would be that Google would need to version each change to a font (so that it would continue only serving versions that match your SRI hashes), which would prevent your website from ever getting updates to that font's CSS. In some cases, those CSS changes are important in keeping up-to-date with the web-platform (e.g. font-display).

I vote no to implementing SRI. As mentioned, if this is really important to you - just download the files and host your own.

**Comment by fulldecent** [comment]
Yes, Google already versions and tracks history for other things it hosts. This is a normal part of being a CDN. Here it is: https://developers.google.com/speed/libraries/

---

Some fonts haven't released new version in over 100 years. Fonts predate computers.

**Comment by KeithBush** [comment]
To add an alternative view, we desire SRI not to "check boxes" but to pin versions so we can be sure everything goes through QA/QC prior to hitting production.  Thankfully fonts don't seem to change too often so it hasn't been much of an issue.  But the desire to lock on a version of a font and apply an SRI check seems reasonable and a fairly standard CDN pattern.

A few people have made comments like "just download the files and host your own" but there are also comments in here indicating that the fonts returned by google servers are slimmed-down/customized/optimized for a users OS and browser.  This implies that if you download and serve a copy of these fonts then there are combinations of OS/browser where the font would not work and it isn't clear what these combinations might be.   There also seems to be no way to target a complete or unoptimized version from the google font website.  If this is indeed what is happening, then we realistically cannot download the files and host them ourselves.

**Comment by vilocity-aaron** [comment]
The fonts can be found here: https://github.com/google/fonts

**Comment by vilocity-aaron** [comment]
It's likely that for the vast majority of folks who want SRI with their fonts, they can skip all of the user-agent black magic that Google Fonts does and just self-host the woff2 file (or woff if they really need to support IE11).

Just fetch the original font file from here: https://github.com/google/fonts, then convert it to a woff/woff2, add that font to your CSS file using @font-face, and add SRI hashes to whichever resources you wish to protect. Then you'll have your "frozen forever" font version that you control.
