### ISSUE TITLE
Source sans pro bold not showing in office 2010 after installation

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [google/fonts#4923]
Hello,
Source Sans Pro Bold does not show in office 2010 (word, powerpoint) despite that that font familly is well installed in windows (source sans pro, source sans pro black, etc are well available. But not source sans pro bold.) Source sans pro bold is well installed in the windows fonts directory.  Confer the 2 images. And it is not possible to apply bold in power point to the source sans pro: if we do, nothing happens. 
![image](https://user-images.githubusercontent.com/44610746/178462824-8dd4acc6-9c7f-4d2a-8415-72d235c2bb42.png)
![image](https://user-images.githubusercontent.com/44610746/178462949-be93aa55-c889-47a4-a8a8-c4f200820c41.png)
Best regards,
Antoine

**Comment by GITHUBAntoineDENIS** [comment]
Hello,
Many thanks for your fast reply. 

I downloaded this one https://fonts.google.com/specimen/Source+Sans+Pro
the whole familly.

my computer = windows 7 :-/

I don't have libreoffice

Why? this font is the official font of my university identity and style guide. I try to respect it. 

Is Source Sans 3 "the same" or very similar to source sans pro? 

((I also installed that font familly for GIMP (https://www.gimp.org/downloads/) and in GIMP the whole familly is available without problem. But I think I also did a specific font installation in the GIMP directory.))

Best regards,

Antoine

----- Mail original -----
De: "kenmcd" ***@***.***>
À: "google/fonts" ***@***.***>
Cc: "Antoine DENIS" ***@***.***>, "Author" ***@***.***>
Envoyé: Mardi 12 Juillet 2022 22:03:04
Objet: Re: [google/fonts] Source sans pro bold not showing in office 2010 after installation (Issue #4923)

What version of Source Sans Pro? (for both Regular and Bold)
What version of Windows?

Note: if you also have LibreOffice it installs an older version on each update.
And you can end up with duplicate font files in the Fonts folder if they are in-use.

Why not use Source Sans 3?
It is a newer version, more glyphs, more features, more fixes ...
And no LibreOffice update annoyances.

**Comment by GITHUBAntoineDENIS** [comment]
Note: I installed now "Source sans 3", from here https://fonts.google.com/specimen/Source+Sans+3?query=source+sans+3, 
I downloaded the whole familly , and then installed only "static > source sans 3 - bold" . 
But in power point , only "source sans 3" appears, without mention of the "bold". confer image
![image](https://user-images.githubusercontent.com/44610746/178589513-9dfe3a10-041a-4682-bc74-396432dfde9e.png)

**Comment by kenmcd** [comment]
Source Sans 3 here:
https://fonts.google.com/specimen/Source+Sans+3
If it works, you may have some other installation issues (duplicate files, etc.).
It looks the same.
The characters are identical, but the vertical metrics are a bit different.
Try that. 
You may have to adjust your line-height setting, but that is all.
Otherwise it is a drop-in replacement.

**Comment by GITHUBAntoineDENIS** [comment]
I note that for "source sans pro", when i use the basic "source sans pro" in power point, I can manually add bold effect with the bold button of power point and it does make a bold effect. That's maybe why the "source sans pro bold" isn't showing in the dropdown list... because we have to access it with the bold button of power point.... it is an hypothesis. 
For the "source sans pro semi bold", that appears in the drop dow list of power point, the bold button of power point has no effect.

**Comment by kenmcd** [comment]
This is normal Windows behavior for Bold and Italics.
Windows uses "style groups" `R/I/B/BI`
That stands for: Regular/Italic/Bold/BoldItalic
Just the Regular appears in the font menu - i.e. Source Sans Pro
And then the other styles in the group are accessed via the `B` and `I` buttons.
There is no "bold" the the SemiBold style group, only an Italic, 
so the `I` button works, but not the `B` button.
Some font families may have multiple `R/I/B/BI` style groups. 
But since this is confusing to users, GF fonts only have the one `R/I/B/BI` group.
And all the others are just `R/I`
Maybe this has been the source of your confusion all along.

**Comment by GITHUBAntoineDENIS** [comment]
Yes I think so ! 
I got it ! 
Many thanks again for your detailed answers and time! 
Best regards,
Antoine

**Comment by fitojb** [comment]
>  And no LibreOffice update annoyances.

@kenmcd: The annoyance was entirely Adobe’s doing. You can’t expect us to have users manually change their fonts in their documents and templates just because someone made a stupid decision to hardcode version numbers in the fonts’ names.

**Comment by kenmcd** [comment]
> > And no LibreOffice update annoyances.
> 
> @kenmcd: The annoyance was entirely Adobe’s doing. You can’t expect us to have users manually change their fonts in their documents and templates just because someone made a stupid decision to hardcode version numbers in the fonts’ names.
> 
> In fact, I think it’s better if we stopped bundling this typeface project entirely.

No. I am not talking about Adobe Sans 3.
LO installs an older version of Adobe Sans Pro with each update.
For example the current version of Adobe Sans Pro Regular is v2.021.
If you have this installed, when LO updates it will install v2.010 again.
So I would un-install the older v2.010, and re-install v2.021.
Next LO update - and we are back to v2.010 again.
And again ...
So using Adobe Sans 3 avoids the issue entirely.

**Comment by fitojb** [comment]
@kenmcd: Yes, because someone decided to mess with the family name. So we stopped caring about updating our installer.

**Comment by khaledhosny** [comment]
May be LibreOffice shouldn’t have bundled fonts it does not have to in the first place, they are libre fonts so there is zero value added in bundling them, and Source Sans Pro is not the only outdated font LibreOffice is bundling.

Changing family name when the new family is metrically incompatible with the old one is not something unheard of, and it is a good thing; LibreOffice users will not upgrade and suddenly their documents are re-flowed. Taking issue with that just makes no sense.

**Comment by kenmcd** [comment]
> @kenmcd: Yes, because someone decided to mess with the family name. So I stopped caring about updating our installer — it wasn’t worth my time to be chasing versions around because you effectively internally forked your own project. And then how could I migrate files and users in a seamless way — just no.

This issue was there before Source Sans 3 was released. And is still there now.
This also affected Source Serif Pro which I how I became aware of the update issue as I had that as my default text font in LO templates.
I think that one may have finally been fixed.
Since moving to Source Serif 4 eliminated the LO update problem for me so I am not sure.

I do remember some discussion in the LO tracker about fixing the font version checking, but have no idea if that ever happened. Appears not.

Note: I am just another user and have nothing to do with this project.
Their reasons for the name change have been discussed here - and it makes sense to me.
And happily it gets rid of an LO update annoyance for me.

This typical reaction is why I stopped posting issues in LO bug tracker.

**Comment by fitojb** [comment]
@kenmcd Office 365 also bundles Source Sans Pro, so your singling-out of LO in an unrelated issue, in an unrelated bug tracker, was always a strawman argument from the get-go.

@khaledhosny I spend my volunteer time in updating any font I find, but I’ve only got two eyes. Bug reports really do make a difference. And, for the record, yes — I agree with you that we shouldn’t have ever bundled this font in the first place. If the old design team (Mirek Mazel et al.) had known how mismanaged Adobe Fonts would become in the future...

**Comment by fitojb** [comment]
@kenmcd Subscription-based Microsoft Office 365 [also bundles Source Sans Pro as part of its Cloud Fonts feature](https://support.microsoft.com/en-us/office/cloud-fonts-in-office-f7b009fe-037f-45ed-a556-b5fe6ede6adb#bkmk_cloudfontavailability), so your singling-out of LO in an unrelated issue, in an unrelated bug tracker, was always a strawman argument from the get-go. (OP of this thread never mentioned LO, he didn’t have it installed...) Now, don’t self-victimize that you get negative reactions when you don’t understand how/who to blame for apparent issues you have.

@khaledhosny I spend my volunteer time in updating any font I find, but I’ve only got two eyes. Bug reports really do make a difference. And, for the record, yes — I agree with you that we shouldn’t have ever bundled this font in the first place. If the old design team (Mirek Mazel et al.) had known how mismanaged Adobe Fonts would become in the future... Source 3 has negligible metric differences that don’t cause reflowing.

(And also, Khaled, I find funny your comment about the value of fonts. Is your own Amiri worthless too, then? Not everything in life has value measured purely monetarily — some of us believe in FLOSS because we’re not capitalists.)

**Comment by khaledhosny** [comment]
> (And also, Khaled, I find funny your comment about the value of fonts. Is your own Amiri worthless too, then? Not everything in life has value measured purely monetarily — some of us believe in FLOSS because we’re not capitalists. LO provides value to users in saving them the time in finding high-quality typefaces for use in their documents. That can’t really be measured in money, but then again...)

I saying that bundling free fonts with a free application does not provide any value to the users, because they can download them themselves. LibreOffice isn’t a type catalogue. Also the fonts are often outdated, including my own fonts. The first thing I do after installing LibreOffice is to go and remove all the bundled fonts, because they are more often than not older than the versions I already installed, or fonts I don’t need or use. LibreOffice does not provide and option not to install the bundled fonts nor to disable them, so it is an inconvenience for me rather than a useful feature.

**Comment by fitojb** [comment]
> I don’t recall ever reporting a bug in LibreOffice and getting it fixed.

I can understand that, my memory is getting increasingly inaccurate as well. It was not one, it was seven:

https://bugs.documentfoundation.org/buglist.cgi?bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&email1=dr.khaled.hosny%40gmail.com&emailreporter1=1&emailtype1=substring&list_id=1479030&order=Importance&query_format=advanced&resolution=FIXED
