### ISSUE TITLE
Add Delicious Handrawn

### ISSUE THREAD

**Issue by alphArtype** [google/fonts#5200]
**Font Project Git Repo URL: https://github.com/alphArtype/Delicious-Handrawn**

**Super short description of the Font Family:
Delicious is a font that was inspired by my own handwriting**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

![image1](https://user-images.githubusercontent.com/111665840/188525859-f047a11f-6a8e-4e16-9f64-6af116612d1c.png)

**Comment by alphArtype** [comment]
Thanks for the help, now I have completed the glyphs according to the gf standard, please check again.
Thank you @RosaWagner

**Comment by alphArtype** [comment]
Thank you for the help,
I have completed the glyphs according to the google font Latin Core glyphset, please check again.
Thank you @RosaWagner

**Comment by RosaWagner** [comment]
Thanks. We'll try to review it and get back to you if it gets accepted. Be aware that it may take a while though.

**Comment by davelab6** [comment]
@alphArtype we accept your submission! @emmamarichal will be in touch with you early next year

**Comment by emmamarichal** [comment]
@davelab6, @RosaWagner
The outlines do not occupy the full height of the box, which creates very large line spacing. 
It might be better to review the proportions and positions or change the value of UPM to 512 (instead of 1000), what do you think?


![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/64773544/210806367-0a224001-5287-428c-b3f1-de017de46648.png)

<img width="1604" alt="Capture d’écran 2023-01-05 à 15 43 58" src="https://user-images.githubusercontent.com/64773544/210806565-8d89514a-d92f-4ac7-ab2c-ed684e19512d.png">
