### ISSUE TITLE
Update Muli ttfautohint to prevent it looking taller on Windows

### ISSUE THREAD

**Issue by johnknoop** [google/fonts#528]
Hi

I noticed you just updated Muli on Google fonts. It now looks completely different. It's way too narrow at 14px (the most common font size for web I think?).

Did Google Fonts previously use Muli 1, and now it uses Muli 2? Or what may the reason be?

Thanks

Edit: it's not too narrow, it's too tall. This text was previousely 1 px lower:

![image](https://cloud.githubusercontent.com/assets/3394270/21055936/bf9240a2-be33-11e6-81c1-03c2c8104ceb.png)

**Comment by davelab6** [comment]
Muli was updated this week, yes - announced at https://fonts.googleblog.com/2016/12/raising-quality-of-fonts-in-our.html and https://twitter.com/googlefonts/status/806770154155560960

**Comment by davelab6** [comment]
> it's not too narrow, it's too tall. This text was previousely 1 px lower

I assume that is on windows, due to ttfautohint 

@fonthausen did the design work and @m4rc1e did the font engineering. Jacques, can you comment on the redesign changing the height?

**Comment by davelab6** [comment]
Also, the new Nunito Sans may be more like "Muli 1"

**Comment by johnknoop** [comment]
The o's used to be circular. Now they're oval.

**Comment by johnknoop** [comment]
Yes, I'm on Windows.

**Comment by johnknoop** [comment]
These are both 14px regular.

![image](https://cloud.githubusercontent.com/assets/3394270/21059565/430072ec-be43-11e6-918e-884459d43dc3.png)

**Comment by davelab6** [comment]
> Yes, I'm on Windows.

The 1px height jump can be adjusted with a ttfautohint option. @m4rc1e can help with this next year.

> The o's used to be circular. Now they're oval.

Okay :) 

Old: 

<img width="601" alt="screen shot 2016-12-09 at 10 13 46" src="https://cloud.githubusercontent.com/assets/261579/21059620/304e00c4-bdf8-11e6-8792-ba8f49214cd9.png">

New: 

<img width="614" alt="screen shot 2016-12-09 at 10 14 38" src="https://cloud.githubusercontent.com/assets/261579/21059643/513a6caa-bdf8-11e6-9550-1ceac3c45741.png">

I do see some condensing of the `o` counter; I guess @fonthausen will argue that it is _better_ this way. 

Its possible we could update it to be more circular if you suggest that was essential to its character.

**Comment by johnknoop** [comment]
Well I guess what is essential is up to the font's creator. But to me, the appeal of the font has gone away now. And I wouldn't be surprised if other users of the font will be annoyed. I think people choose a font because how it looks, and if the look changes then that might break the design of the entire website.

**Comment by johnknoop** [comment]
The difference isn't so noticable in large sizes like your example. But checkout my image above. Muli Regular 14px vs Muli Regular 14px. Yet it looks like two completely different fonts.

**Comment by davelab6** [comment]
@johnknoop you can self-host the original design if you want to keep it. I believe most people will want a better quality design, and the type designers who are doing the work are tasked with keeping the original spirit and look-n-feel while making it better quality. Sometimes those 2 things are in tension.

**Comment by davelab6** [comment]
However, in this specific case, this 'growing taller' effect is seen only on Windows, and is something that can be tweaked without more type design - its a ttfautohint production option to grow taller in smaller sizes to increase legibility, and can be turned off.

**Comment by davelab6** [comment]
https://www.freetype.org/ttfautohint/doc/ttfautohint.html#blue-zone-reference-font

**Comment by adrientetar** [comment]
The x-height rounding parameter could help here, by default it has a rounding up preference up to 14px: https://www.freetype.org/ttfautohint/doc/ttfautohint.html#x-height-increase-limit

**Comment by Fonthausen** [comment]
Hi John,

Vernon Adams did a great job in the first place, but during the original development he didn’t have as much time as we did. He was busy building the Google fonts Library together with other people at the time. 

During the most recent design process we had to make several choices to increase consistency and readability. The main goal was to uplift Muli to a professional level. Muli originally had a few weights, now it has 14. We tried to keep the original weights has good as possible, but the typeface is now part of a bigger system/family.

One of the choices was to balance out the horizontal proportions better than in the original. 
>> The o's used to be circular. Now they're oval.

When you compare the old and the new Muli, there are indeed some small differences. 

Here is the new Muli /o overlaying the old:

But when you compare the original /o and /p you will see that the counter (inner form) of the /o is much larger than the one of the /p:


Same comparison in the new design:





> The difference isn't so noticable in large sizes like your example. But checkout my image above. Muli Regular 14px vs Muli Regular 14px. Yet it looks like two completely different fonts.

> The 1px height jump can be adjusted with a ttfautohint option. @m4rc1e can help with this next year.

I had a look into the old font files. I noticed a few things that are being done differently nowadays. Aside of hinting, there will always be small differences on a technical level. Font technology, operating systems and hardware have changed a lot since 2007, the year Muli was produced.

We kept the vertical metrics as they were. If there is a size difference on your screen at 14px, this will be a rounding issue of the True Type hinting. As Dave already stated, this can be adjusted.

I am well aware that not everyone will like the changes we did in the new design. But overall it has become a better typeface on several levels. If you still want to use the original, it still is available, as Dave stated earlier.

Best regards,
Jacques

**Comment by Fonthausen** [comment]
I originally send my reply with pictures, not knowing GitHub didn't accept them. I attached them here
<img width="581" alt="schermafbeelding 2016-12-09 om 19 48 38" src="https://cloud.githubusercontent.com/assets/20181530/21062324/9b62db34-be50-11e6-8029-30d8035eac6b.png">
<img width="457" alt="schermafbeelding 2016-12-09 om 19 51 06" src="https://cloud.githubusercontent.com/assets/20181530/21062326/9b6973d6-be50-11e6-8131-e927458b69df.png">
<img width="438" alt="schermafbeelding 2016-12-09 om 20 15 25" src="https://cloud.githubusercontent.com/assets/20181530/21062325/9b657f88-be50-11e6-891a-2bbbb8fd31cc.png">
<img width="456" alt="schermafbeelding 2016-12-09 om 20 20 02" src="https://cloud.githubusercontent.com/assets/20181530/21062327/9b6c9084-be50-11e6-8f3e-31d565121dc3.png">

**Comment by johnknoop** [comment]
@davelab6 Is there anyway I can get hold of the old webfont files?

@FAlthausen I know you guys are doing a great job to the benefit of all. It's just in this particular case, I think the outcome is unfortunate. As much as I've been looking forward to the other styles of Muli, the big difference now forces me to self-host the old webfonts, if I can get them. And that just saves my website, wheres the design tool I use for high-fidelity mockups (moqups.com) pulls it's font's directly from Google, so I don't really have a solution for that yet.

**Comment by m4rc1e** [comment]
@johnknoop old version is [here](https://github.com/vernnobile/MuliFont)

**Comment by johnknoop** [comment]
Nevermind, I just googled Muli woff and found another cdn that serves the fonts, and they actually look great! Not sure how serious/reliable this site is, so I downloaded them as well.
https://www.onlinewebfonts.com/

https://www.onlinewebfonts.com/download/fe82d4bebb545cd0d8c9683e258e961c

**Comment by johnknoop** [comment]
@m4rc1e That just the ttf's. I tried converting them with Fontsquirrel, but couldn't make it look good (I'm no font expert).

**Comment by davelab6** [comment]
@m4rc1e I've assigned this to you, this is something quick we can work on in January

**Comment by m4rc1e** [comment]
Hey,

Here's a gif to animate the difference between ttfautohint's xheight rounding (default=14px) vs disabled. 

![muli-xheight](https://cloud.githubusercontent.com/assets/7525512/22061633/bd5a3d18-dd6d-11e6-850b-e5d1afc0bfd3.gif)

**Comment by adrientetar** [comment]
Yes, that seems to be it.

**Comment by m4rc1e** [comment]
@davelab6 shall we release the version with no x-height scaling?

I'm still questioning the whether we should do this collection wide. It should probably be made on a case by case basis for each family.

**Comment by OpalSnow** [comment]
It appears the issue still persists

**Comment by johnknoop** [comment]
> Hey,
> 
> Here's a gif to animate the difference between ttfautohint's xheight rounding (default=14px) vs disabled.
> 
> Chrome, Win 7
> ![muli-xheight](https://cloud.githubusercontent.com/assets/7525512/22061633/bd5a3d18-dd6d-11e6-850b-e5d1afc0bfd3.gif)
> _click image to view full size_

Here's an odd request: I would love to get my hands on this version (the non-xheight roundig version), but I have no experience in fontmaking. I tried downloading FontForge and play around with different settings, but without success.

Is there anyone of you fontmakers here who could consider doing me the huge favor of re-creating the version in @m4rc1e ´s screenshot above? I'm not a stranger to paying for your trouble.

**Comment by ea0723** [comment]
@johnknoop  I was looking for the original Muli as well and since I wasn't able to find it, here is a font that is very similar in shape (roundness) and balance. https://www.myfonts.com/fonts/jam-type-design/jt-marnie/regular/
While it may not be Muli, it's very close (I was looking for numbers specifically and this one the 9 is not hooked at the bottom - so may not work for you, but the overall look is quite similar).
Hope this helps!

**Comment by johnknoop** [comment]
@ea0723 if you want the _old_ Muli version, you can find it here: https://www.onlinewebfonts.com/download/fe82d4bebb545cd0d8c9683e258e961c

What I'm looking for is the _new_ version, but with the no-xheight-rounding modification that @m4rc1e demonstrated earlier in this thread.

**Comment by davelab6** [comment]
I believe this was fixed when the family was upgraded to a weight axis variable font.
