### ISSUE TITLE
How should indestructible type* fonts be identified

### ISSUE THREAD

**Issue by applecuckoo** [google/fonts#5569]
Fonts from indestructible type* have been attributed to Owen Earl in the past, my question is if they should be attributed to indestructible type* instead, maybe without the asterisk since that will probably break search.

**Describe the issue**
Fonts from Owen Earl should be attributed to indestructible type

**Additional context**
@EwonRael can provide his opinion on this.

**Comment by RosaWagner** [comment]
@applecuckoo thanks for your question, although if this is something Owen wants, he can make the demand himself in the issue tracker, or by email since he has our contacts. No credit will change at the demand of users, it must be the demand of the authors themselves. These credits are also made in collaboration with the authors, so we will be happy to add the foundry if it is a concern of him :)
