### ISSUE TITLE
Darker Grotesque backwards quotation marks 

### ISSUE THREAD

**Issue by abilambert** [google/fonts#5599]
Specify the font name in title with a short description of the bug. 
Please report any issue related to Noto fonts in this repository: https://github.com/googlefonts/noto-fonts/issues.

**Describe the bug**
The quotation marks for Darker Grotesque are backwards.

**To Reproduce**
To test this bug, type a quotation mark " while using the font Darker Grotesque on Google Docs,  Google Slides, or as a font file in Adobe or Microsoft products. An example could be “Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.”

**Expected behavior**
The quotation marks for Darker Grotesque should point the opposite direction on either side of a quote. 

**Screenshots**
<img width="1108" alt="Screen Shot 2022-11-21 at 7 03 12 PM" src="https://user-images.githubusercontent.com/118780386/203182450-c570cdd3-8884-4f2b-97ab-2e96703f3646.png">

**Comment by kenmcd** [comment]
U+201C and U+201D are reversed.

**Comment by CML-SYS** [comment]
Is there an ETA for when in Q1 this might be fixed? Would users need to reinstall the font once fixed?

**Comment by kenmcd** [comment]
This same issue was reported in the upstream repo over 18 months ago. https://github.com/bettergui/DarkerGrotesque/issues/4
No response from the font developer.

There have been no updates there since the first uploads.
And the Italic source was never uploaded.
And there are many interpolation errors in the Roman source - which do appear in the static fonts (e.g euro, arrows, etc.).

Appears the font developer is MIA.
So these fonts are probably not to be fixed any time soon.
You may want to find another font.
