### ISSUE TITLE
KonKhmer_SleokChher

### ISSUE THREAD

**Issue by suonmaysophanith7** [google/fonts#5607]
**Font Project Git Repo URL:** [KonKhmer_SleokChher](https://github.com/suonmaysophanith7/KonKhmer_SleokChher)

**Super short description of the Font Family:** Type of leaf, Leaf letter in Khmer alphabet 

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository
![BOD-06](https://user-images.githubusercontent.com/111719409/203718751-6711acdc-ae75-48da-9a0e-c09a674c25b3.png)
![KonKhmer_SleokChher-06](https://user-images.githubusercontent.com/111719409/203718894-bbd1b24f-a7ad-41f9-bd8d-82fef37b5756.png)

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

**Comment by RosaWagner** [comment]
Hi @suonmaysophanith7 and thanks for your submission. I see some minor technical issues in the repository; you can remove the template artifacts such a the Rubik font itself, and update the README.md and config.yaml so it matches your project. 

I was unable to open the Glyphs source file due to "Unexpected character '0xa' at line 74". If you could look into fixing the source file then I would be able to review the family :)

Danh Hong has published several Khmer fonts on GF, you can take a look at his sources for technical production: https://github.com/danhhong/Koulen

**Comment by suonmaysophanith7** [comment]
Dear @RosaWagner  Now, I have updated some minor issue, please kindly recheck. Thank you

**Comment by RosaWagner** [comment]
@suonmaysophanith7 thanks, now we can review it :) Would you see anything against removing the underscore in the family name? It disturbs the tools.

Noting here that since it's a Khmer font, we don't necessitate the support of GF_Latin_Core glyphset, [GF_Latin_Kernel](https://github.com/googlefonts/glyphsets/blob/main/GF_glyphsets/Latin/txt/nice-names/GF_Latin_Kernel.txt) is enough.

We'll let you know if GF wants to onboard it or not when the "submission board" has gathered (it can take a while), but I added the font to the list ;)

**Comment by suonmaysophanith7** [comment]
@RosaWagner  Thank you so much for your feedback, I will remove the underscore in the family name to avoid disturbing the tool., furthermore please kindly let me know to adjust and fix some issue in the font if it will onboard, and I wish , I will try to do as required.

**Comment by davelab6** [comment]
@suonmaysophanith7 great work, I am looking forward to onboarding this. @yanone will be in touch next year with next steps :)
