### ISSUE TITLE
DM Serif/Sans design credit is confusing

### ISSUE THREAD

**Issue by frankrolf** [google/fonts#5644]
[DM Serif Display](https://fonts.google.com/specimen/DM+Serif+Display?query=dm+serif) and [Text](https://fonts.google.com/specimen/DM+Serif+Text) both list me as a designer; however, I am not entirely comfortable with that credit. The work is based on my design (Source Serif), but I had absolutely no influence over the outcome — in fact, I was surprised by it.

May I suggest a different approach:
DM Serif | designed by Colophon | based on Source Serif

This would disassociate me from any modifications of Source Serif, but still clarify the connection to the original source.

I think there might be other examples of this in the GF library — actually am interested what @jonpinhorn thinks about the association with DM Sans.

**Comment by RosaWagner** [comment]
Hi @frankrolf, thanks for reporting. We have both situations where designers want to be credited and other not, because of the ambiguity of the situation. So we prefer to credit the designer of the designers of the original font cause it seems to be the correct legal outcome.

But it is totally up to you, if you find it uncomfortable, we can remove the credit whilst making sure the description is mentioning the original source and their designers :)

@emmamarichal we should update profiles and descriptions of DM Serif Display and Text:
- bio is in designer profile (last paragraph should be removed)
- description mention the original fonts and their designer
- remove Frank from credit in METADATA.pb for both.

@frankrolf feel free to fill up this form so we can also publish your bio in the Source fonts: https://docs.google.com/forms/d/e/1FAIpQLSeMwHN8J213ZaxHrr5lHCrX56HY_NjGrWB8o604g98YxuMrdA/viewform

**Comment by davelab6** [comment]
@frankrolf the catalog is a template driven website and customizing the strings on arbitrary pages isn't feasible for the team to maintain, and the temple doesn't support reflecting remix relationships; we've just kept the credits from the parent projects. 

Rosalie's recommendation to remove you from the credit and better explain the heritage is fine with me
