### ISSUE TITLE
Lato font missing characters such as 🖧

### ISSUE THREAD

**Issue by Konglomneshued** [google/fonts#5725]
Specify the font name in title with a short description of the bug. 
Please report any issue related to Noto fonts in this repository: https://github.com/googlefonts/noto-fonts/issues.

**Describe the bug**

Lato seems to be missing characters, making them render improperly.

**To Reproduce**

1. On Fedora 37, install Lato fonts from dnf - `sudo dnf in lato-fonts`.
2. Install Brave Flatpak from Software center.
3. Reset all Brave settings to defaults, then change all fonts to Lato, just in case.
4. Restart Brave.
5. Visit a website that uses this character: 🖧.  https://www.reddit.com/r/pop_os/

**Expected behavior**

Supposedly the character should look like this:
![image](https://user-images.githubusercontent.com/94726665/208791770-5be74d90-da83-44a6-a0ca-5f5e7429287f.png)

**Screenshots**

Instead it looks like this:
![image](https://user-images.githubusercontent.com/94726665/208791040-efcd3393-8bd6-4f8e-927c-0030e6eece6b.png)

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)

- Fedora 37
- Brave Web Browser

```
Name         : lato-fonts
Version      : 2.015
Release      : 14.fc37
Architecture : noarch
Size         : 11 M
Source       : lato-fonts-2.015-14.fc37.src.rpm
Repository   : @System
From repo    : fedora
```

**Comment by marekjez86** [comment]
This is intentional aka a feature :-). Lato supports extended Latin Unicode codepoints. The character you mention is a Symbol and is, for example, included in https://fonts.google.com/noto/specimen/Noto+Sans+Symbols+2. If a font containing your symbol is removed from your font fallback stack, then you'll experience what you experienced. 

Lato doesn't support Telugu. Please go to a Telugu site, with exactly the same setup as described here, for example https://www.eenadu.net/ and I believe you'll also experience the same situation.

**Comment by Konglomneshued** [comment]
I actually don't see any 
![image](https://user-images.githubusercontent.com/94726665/209027541-bd4e7ea8-5b1a-4763-aace-5fd3ca7b0d64.png)

Is there a font that builds on Lato or maybe something that looks similar?  I'm looking for something with support for more characters, so I don't see those symbols.  I had the same issue with Fira Code and switched my code font to Cascadia.

**Comment by RosaWagner** [comment]
@Konglomneshued https://fonts.google.com/noto/specimen/Noto+Sans+Symbols+2 is supporting this character :)

This is not a problem with Laton so closing this issue.
