### ISSUE TITLE
Add Inclusive Sans

### ISSUE THREAD

**Issue by LivKing** [google/fonts#5728]
[**Font Project Git Repo URL:**](https://github.com/LivKing/Inclusive-Sans)

**Inclusive Sans is a text font designed for accessibility and readability. It incorporates key features at a character level to ensure legibility for all people.**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**
![InclusiveSans](https://user-images.githubusercontent.com/44744214/209619259-1689a6e2-cc21-4856-9902-cbbbe428affd.jpg)

**Note**
I've followed the repository and font file requirements as close as possible, but would appreciate help from a GF team member with the tooling and building process for my font.

**Comment by RosaWagner** [comment]
Hi @LivKing, thanks for your submission. It looks good and it is well documented. I added it to the submission to review with the rest of the team.

**Comment by emmamarichal** [comment]
Hi @LivKing,
Thanks for your nice project! I took a look to the file, and noticed that the glyphset doesn't follow the [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/) (maybe it has been updated since December 2022).
Here are the missing glyphs:
less, greater, asciicircum, grave, asciitilde, section, dieresis, ordfeminine, guillemetleft, acute, paragraph, cedilla, ordmasculine, guillemetright, multiply, circumflex, caron, breve, dotaccent, ring, ogonek, tilde, hungarumlaut, minus, Cdotaccent, Gbreve, Gdotaccent, Hbar, IJ, Idotaccent, Scommaaccent, Germandbls, Tcommaaccent, Ubreve, cdotaccent, gbreve, gdotaccent, hbar, idotaccent, ij, scommaaccent, tcommaaccent, ubreve, nbspace, .notdef, periodcentered.loclCAT, periodcentered.loclCAT.case, guilsinglleft, guilsinglright

<img width="920" alt="Capture d’écran 2023-06-01 à 14 18 23" src="https://github.com/google/fonts/assets/64773544/c03a3d47-9c45-4ee0-bd25-8b5f18d4980e">


Some of them are quick to generate, I usually can do it, but in that case, a lot of them need some design work (section, paragraph, Germandbls, etc.) 
Also, we keep legacy accents (without "comb"), which are composites, so easy to generate. 

Don't hesitate if you have any question :)
Thanks!

Attached, the last version of sources, with the missing glyphs added (pink one)
[InclusiveSans.glyphs.zip](https://github.com/google/fonts/files/11625120/InclusiveSans.glyphs.zip)
