### ISSUE TITLE
Wrong binary / bad embedding bits for Noto Color Emoji

### ISSUE THREAD

**Issue by simoncozens** [google/fonts#5729]
**Describe the bug**

Noto Color Emoji 2.038 in the noto-emoji repository has no embedding restrictions:

```
$ ttx -o - -t OS/2 fonts/NotoColorEmoji.ttf | grep fsType
Dumping "fonts/NotoColorEmoji.ttf" to "-"...
Dumping 'OS/2' table...
    <fsType value="00000000 00000000"/>
```

However, the one in *this* repository does:

```
$ ttx -o - -t OS/2 ofl/notocoloremoji/NotoColorEmoji-Regular.ttf | grep fsType
Dumping "ofl/notocoloremoji/NotoColorEmoji-Regular.ttf" to "-"...
Dumping 'OS/2' table...
    <fsType value="00000000 00000100"/>
```

I wonder how that got past fontbakery?

**Comment by RosaWagner** [comment]
@rsheeter seems to have onboarded the font in https://github.com/google/fonts/pull/4226 and https://github.com/google/fonts/pull/4994. I don't think fontbakery was used.

**Comment by rsheeter** [comment]
Can confirm fontbakery was not used. Hm. Can we easily make fontbakery part of CI for https://github.com/googlefonts/noto-emoji? - the font only gets to this repo relatively late in it's lifecycle.

**Comment by anthrotype** [comment]
FWIW I think noto-emoji is so special that it might not pass all fontbakery checks.. but you can try.

also, it's not clear to me why OS/2.fsType would be different.. I don't recall any tool that would change that. `NotoColorEmoji` is the CBDT/CBLC font so I think that has it preset in the .ttx template used for font-wide metadata like OS/2.

**Comment by anthrotype** [comment]
Another strange thing I noticed.. the copy that is inside this fonts repo at [ofl/notocoloremoji/NotoColorEmoji-Regular.ttf](https://github.com/google/fonts/blob/main/ofl/notocoloremoji/NotoColorEmoji-Regular.ttf) was added 8 months ago (July 28 2022) with https://github.com/google/fonts/pull/4994, according to git.

However upstream has had a new release onSeptember 16 titled "Unicode 15.0":
https://github.com/googlefonts/noto-emoji/releases/tag/v2.038

So it seems like the two are out of sync..

Which one is the file that we serve from fonts.google.com?
And if it's different from the one in [ofl/notocoloremoji/NotoColorEmoji-Regular.ttf](https://github.com/google/fonts/blob/main/ofl/notocoloremoji/NotoColorEmoji-Regular.ttf), then.. what's the latter used for?

**Comment by anthrotype** [comment]
> `NotoColorEmoji` is the CBDT/CBLC font

self-correction: that is _not_ the CBDT noto-emoji font, despite the name seems to suggest it so..
The file at https://github.com/google/fonts/blob/main/ofl/notocoloremoji/NotoColorEmoji-Regular.ttf contains vector color tables so it's equivalent to https://github.com/googlefonts/noto-emoji/blob/main/fonts/Noto-COLRv1.ttf, with the addition of OT-SVG table generated by `maximum_color` tool.

**Comment by anthrotype** [comment]
the naming confusion might explain why the file `fonts/NotoColorEmoji.ttf` on the noto-emoji repo (i.e. the CBDT font) has different embedding restrictions from `ofl/notocoloremoji/NotoColorEmoji-Regular.ttf` (COLRv1 + OT-SVG) on this repository; they are entirely different fonts, produced by different toolchains.

Still I don't know why the Noto-COLRv1 font doesn't have OS/2.fsType set like in the old NotoColorEmoji font, maybe we should file an issue about that on the noto-emoji repo.
Probably nanoemoji doesn't care to set that, and ufo2ft uses a reasonable default value for fsType..  which turns out to be exactly 0x100 like @simoncozens reported.

https://github.com/googlefonts/ufo2ft/blob/5b22f201b4650ab9ef1169357702a732e3127a5e/Lib/ufo2ft/fontInfoData.py#L386

**Comment by anthrotype** [comment]
let's keep this open until the copy in ofl/notocoloremoji actually gets updated

**Comment by RosaWagner** [comment]
@anthrotype @rsheeter has the fix been pushed to prod?
