### ISSUE TITLE
Webfonts Interface - Support for .woff + .woff2 Files

### ISSUE THREAD

**Issue by michael-kreatif** [google/fonts#5899]
Hi guys, 
I hope it's ok if I write this as an issue....

Is there any way to download the fonts in woff or woff2 on the https://fonts.google.com/ website? I can only find the option to download them as .ttf files.
I think it was possible a few years ago to select the formats and download .woff and .woff2 files as well. Is that possible or am I mistaken?

Cheers,
Michael

**Comment by rsheeter** [comment]
I don't recall supporting download in woff/woff2. Our CSS API will use the best format the useragent supports so you could hack it by sending requests with varied user agent if you felt especially determined. However, this may cause problems as those files can be platform-specific to accomodate the idiosyncracies of different environments. Would not recommend :)

IMHO it would be best to create your own woff2 files. https://rsheeter.github.io/font101/#diy-google-fonts has an example, search for "Compression". AFAIK you don't really need woff as all major browsers support woff2.

**Comment by jesperingels** [comment]
Hi @rsheeter,

As a developer I want my users to have the best user experience possible. To make sure my users don't see a FOUT or FOIT I want my font to load as fast as possible. I could for instance pre-load my custom web-font, but to do this I would have to have the exact url to the font-file. I currently don't see a way to get this url to the woff2 font file on the google fonts website.

I would really like this feature because it saves me the hustle of manually calling the api and extracting the download url's (as described in these articles: [Use variable fonts to reduce your font load significantly](https://ckeditor.com/blog/optimize-font-size-with-variable-fonts/) & [Getting the Most Out of Variable Fonts on Google Fonts](https://css-tricks.com/getting-the-most-out-of-variable-fonts-on-google-fonts/)
 
Furthermore it would also be faster to self-host this font file since the user has already made a connection to my server, connecting to an external server (Google api) would slow down the time to download the font. So then I would also like to be able to download the woff2 font-file through the interface of the google-fonts website instead of doing this manually. 

I think that users (developers) would really like the feature of being able to download font files through the interface of the google fonts website.

I'm curious what you think about this concerning web-performance.

**Comment by rsheeter** [comment]
It's entirely reasonable to self-host but it would be better to compress yourself than to grab files from our cdn because our files are not always meant to be reusable across user-agents. If I wanted to self-host my inclination would be to write a script to clone this repo and compress the fonts I want to use. All the tooling to do so is public and open source.

For context, in theory we could provide a mechanism to obtain css (for unicode range) and woff2 files that would work on most modern browsers but we don't currently have an implementation. Our system thinks about things in terms of what asset can we send given the capabilities of the user agent so the changes to support this are slightly more fiddly than one might initially imagine.

Wrt web performance there is some nuance. Short-term you can reap the benefit of not connecting to an additional host. Mid to long term you will miss out on any optimizations we ship unless you update your sites. In the past we shipped unicode-range (and various tweaks to the ranges) and woff2 to our users w/o requiring any client change. In future we aspire to ship https://www.w3.org/TR/IFT/.
