### ISSUE TITLE
Add Pixelify Sans

### ISSUE THREAD

**Issue by eifetx** [google/fonts#5910]
Font Project Git Repo URL: https://github.com/eifetx/Pixelify-Sans

Super short description of the Font Family:
pixel display font. It works great for your retro party designs, game creation or pretty much anything that demands a “go back in time” vibe.

Requirements:

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.
![PREVIEW (1)](https://user-images.githubusercontent.com/123919967/219847075-7b3c2931-3e27-4ce6-a28e-cfed2102c87d.png)

**Comment by RosaWagner** [comment]
Hi again @eifetx, thanks for your submission. Very cool pixel font! Unfortunately we can't give reviews when the sources are missing from the repository. Would you consider adding them?

**Comment by jdavidleon** [comment]
Hi, could you tell me how I can know when a font is ready to be incorporated into Google Fonts and I can collaborate by uploading it?

**Comment by eifetx** [comment]
> Hi again @eifetx, thanks for your submission. Very cool pixel font! Unfortunately we can't give reviews when the sources are missing from the repository. Would you consider adding them?

hi @RosaWagner i will add a missing file. thank you

**Comment by eifetx** [comment]
> Hi, could you tell me how I can know when a font is ready to be incorporated into Google Fonts and I can collaborate by uploading it?

Hi. i just upload the missing file. you want to collaborate with this fonts ?

**Comment by eifetx** [comment]
> Hi again @eifetx, thanks for your submission. Very cool pixel font! Unfortunately we can't give reviews when the sources are missing from the repository. Would you consider adding them?

Hi, Rosa. i just upload the missing file. thanks for letting me know

**Comment by jdavidleon** [comment]
> > Hi, could you tell me how I can know when a font is ready to be incorporated into Google Fonts and I can collaborate by uploading it?
> 
> Hi. i just upload the missing file. you want to collaborate with this fonts ?

Hi, I would like to collaborate, but I am new to this topic, I had never collaborated before. Although I was reading the documentation and apparently if you were missing a file.
If you could give me the summarized step by step to guide me, it would help me a lot.

**Comment by eifetx** [comment]
> > > Hi, could you tell me how I can know when a font is ready to be incorporated into Google Fonts and I can collaborate by uploading it?
> > 
> > 
> > Hi. i just upload the missing file. you want to collaborate with this fonts ?
> 
> Hi, I would like to collaborate, but I am new to this topic, I had never collaborated before. Although I was reading the documentation and apparently if you were missing a file. If you could give me the summarized step by step to guide me, it would help me a lot.

thank you for interest this font.
im new too in github, im never collaborated with someone else.
maybe, we should wait Rosa for review this fonts

**Comment by cancermood** [comment]
Hi @eifetx, nice work! Will these fonts be available on Google Fonts? Thanks

**Comment by eifetx** [comment]
> Hi @eifetx, nice work! Will these fonts be available on Google Fonts? Thanks

hello, thank you for interest this font. unfortunately, this font isn't available on google fonts.
or you should ask @RosaWagner thanks!

**Comment by emmamarichal** [comment]
Hi @eifetx!

I'm Emma, working with the Google Fonts team and I've been assigned to this project :)

There are indeed several rules/specifications to follow in order to publish a project on Google Fonts. Here are a very good documentation done by our team, where you can find a lot of informations about it: https://googlefonts.github.io/gf-guide/index
- New fonts guide: https://googlefonts.github.io/gf-guide/onboarding.html#new-fonts

But I can start to guide you for the main issues 👍 

-----------------

#### Here is a list of what you should modify:

- [ ] Glyphset: you will find attached the Glyphs file with the missing glyphs coloured in pink (IJ Germandbls idotaccent ij jdotless ordfeminine ordmasculine nbspace periodcentered.loclCAT periodcentered.loclCAT.case dieresiscomb dotaccentcomb gravecomb acutecomb hungarumlautcomb caroncomb.alt circumflexcomb caroncomb brevecomb ringcomb tildecomb macroncomb commaturnedabovecomb commaaccentcomb cedillacomb ogonekcomb dieresis dotaccent acute hungarumlaut circumflex caron breve ring tilde macron cedilla ogonek)
- [ ] Font infos: copyright, parameters, v-metrics, instances, features, you can have a look to the guide, but if you are not sure, I'll do it, no worries! 
- [ ] Readme: https://googlefonts.github.io/gf-guide/readmefile.html Don't hesitate to add some images :)
- [ ] It's better if you draw the .notdef
- [ ] Accents: Here is the diacritics guide: https://googlefonts.github.io/gf-guide/diacritics.html

First, accented letters should be composites, made of components. 
To create this, select all your accented letters and do Glyphs > create composite (hold "option" to display "for all masters")
I advice you to copy your design in the background, to not loose the accents positions (select all your glyphs and cmd + J in the two masters)
<img width="347" alt="Capture d’écran 2023-07-07 à 15 03 29" src="https://github.com/google/fonts/assets/64773544/44ceffcd-b1b9-411d-8a38-802646cfd83f">

All your base glyphs need to have anchors (cmd + U)
<img width="345" alt="Capture d’écran 2023-07-07 à 15 03 38" src="https://github.com/google/fonts/assets/64773544/5ae0e3d6-252a-46ff-825c-00de511d979c">

The accent attached to the letter is a "combining accent", with the suffix "comb". They have anchors too, that are linked the the letters ones.
<img width="192" alt="Capture d’écran 2023-07-07 à 15 04 00" src="https://github.com/google/fonts/assets/64773544/eaa1a459-a4d9-4912-8cdc-7a1b85107922">

Accents without "comb" suffix are called "legacy accents" and should be a composite
<img width="282" alt="Capture d’écran 2023-07-07 à 15 03 51" src="https://github.com/google/fonts/assets/64773544/ffea1f6b-70a7-49bd-8aca-d204c8a4de19">

In the source file attached, I give you an exemple with the grave accent (on 'è'). You can follow this modele for the rest of the glyphset :) 

[Pixelfy Sans.glyphs.zip](https://github.com/google/fonts/files/11982452/Pixelfy.Sans.glyphs.zip)


----------------------

I run fontbakery to get a report and find fails. There are some but I can easily fix them on my side. I still copy/paste it here if you are interested to solve them by yourself.

## Fontbakery report

Fontbakery version: 0.8.13

<details><summary><b>[1] Family checks</b></summary><div><details><summary>ℹ <b>INFO:</b> Check axis ordering on the STAT table.  (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/STAT/axis_order">com.google.fonts/check/STAT/axis_order</a>)</summary><div>


* ℹ **INFO** From a total of 1 font files, 0 of them (0.00%) lack a STAT table.

	And these are the most common STAT axis orderings:
	('wght', 1) [code: summary]
</div></details><br></div></details><details><summary><b>[29] Pixelfy Sans[wght].ttf</b></summary><div><details><summary>🔥 <b>FAIL:</b> Checking file is named canonically. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/canonical_filename">com.google.fonts/check/canonical_filename</a>)</summary><div>


* 🔥 **FAIL** Expected "PixelifySans[wght].ttf. Got Pixelfy Sans[wght].ttf. [code: bad-filename]
</div></details><details><summary>🔥 <b>FAIL:</b> Checking OS/2 fsType does not impose restrictions. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/fstype">com.google.fonts/check/fstype</a>)</summary><div>


* 🔥 **FAIL** In this font fsType is set to 8 meaning that:
The font may be embedded but must only be installed temporarily on other systems.

No such DRM restrictions can be enabled on the Google Fonts collection, so the fsType field must be set to zero (Installable Embedding) instead. [code: drm]
</div></details><details><summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in fonts (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/font_copyright">com.google.fonts/check/font_copyright</a>)</summary><div>


* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: "Copyright 2019 The Familyname Project Authors (git url)"
But instead we have got:
"Copyright (c) 2021 by Stefie Justprince. All rights reserved." [code: bad-notice-format]
</div></details><details><summary>🔥 <b>FAIL:</b> Check variable font instances (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/fvar_instances">com.google.fonts/check/fvar_instances</a>)</summary><div>


* 🔥 **FAIL** fvar instances are incorrect:
- wght coordinates are wrong for some instances
| Name | current | expected |
| :--- | :--- | :--- |
| Regular | wght=400.0 | wght=400.0 |
| Medium | wght=500.0 | wght=500.0 |
| SemiBold | wght=600.0 | wght=600.0 |
| Bold | wght=650.0 | wght=700.0 |
| ExtraBold | wght=700.0 | wght=800.0 |
| Black | wght=900.0 | wght=900.0 | [code: bad-fvar-instances]
</div></details><details><summary>🔥 <b>FAIL:</b> Check font follows the Google Fonts vertical metric schema (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vertical_metrics">com.google.fonts/check/vertical_metrics</a>)</summary><div>


* 🔥 **FAIL** OS/2.sTypoLineGap is "200" it should be 0 [code: bad-OS/2.sTypoLineGap]
* 🔥 **FAIL** The sum of hhea.ascender + abs(hhea.descender) + hhea.lineGap is 1000 when it should be at least 1200 [code: bad-hhea-range]
</div></details><details><summary>🔥 <b>FAIL:</b> OS/2.fsSelection bit 7 (USE_TYPO_METRICS) is set in all fonts. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/os2/use_typo_metrics">com.google.fonts/check/os2/use_typo_metrics</a>)</summary><div>


* 🔥 **FAIL** OS/2.fsSelection bit 7 (USE_TYPO_METRICS) wasNOT set in the following fonts: ['Pixelfy Sans[wght].ttf']. [code: missing-os2-fsselection-bit7]
</div></details><details><summary>🔥 <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/family/win_ascent_and_descent">com.google.fonts/check/family/win_ascent_and_descent</a>)</summary><div>


* 🔥 **FAIL** OS/2.usWinAscent value should be equal or greater than 916, but got 750 instead [code: ascent]
</div></details><details><summary>🔥 <b>FAIL:</b> Checking OS/2 Metrics match hhea Metrics. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/os2_metrics_match_hhea">com.google.fonts/check/os2_metrics_match_hhea</a>)</summary><div>


* 🔥 **FAIL** OS/2 sTypoAscender (631) and hhea ascent (800) must be equal. [code: ascender]
</div></details><details><summary>🔥 <b>FAIL:</b> Ensure soft_dotted characters lose their dot when combined with marks that replace the dot. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/soft_dotted">com.google.fonts/check/soft_dotted</a>)</summary><div>


* 🔥 **FAIL** The dot of soft dotted characters used in orthographies must disappear in the following strings: i̊ i̋ j̀ j́ j̃ j̄ j̈ į̀ į́ į̂ į̃ į̄ į̌ і́

The dot of soft dotted characters should disappear in other cases, for example: i̇ ǐ i̒ i̦̇ i̦̊ i̦̋ ǐ̦ i̦̒ i̧̇ i̧̊ i̧̋ ǐ̧ i̧̒ j̆ j̇ j̊ j̋ ǰ j̒ j̦̀ [code: soft-dotted]
</div></details><details><summary>🔥 <b>FAIL:</b> The variable font 'wght' (Weight) axis coordinate must be 700 on the 'Bold' instance. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/fvar.html#com.google.fonts/check/varfont/bold_wght_coord">com.google.fonts/check/varfont/bold_wght_coord</a>)</summary><div>


* 🔥 **FAIL** The "wght" axis coordinate of the "Bold" instance must be 700. Got 650.0 instead. [code: wght-not-700]
</div></details><details><summary>🔥 <b>FAIL:</b> STAT table has Axis Value tables? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/stat.html#com.adobe.fonts/check/stat_has_axis_value_tables">com.adobe.fonts/check/stat_has_axis_value_tables</a>)</summary><div>


* 🔥 **FAIL** STAT table is missing Axis Value for 'wght' value '650.0' [code: missing-axis-value-table]
</div></details><details><summary>⚠ <b>WARN:</b> Checking OS/2 achVendID. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vendor_id">com.google.fonts/check/vendor_id</a>)</summary><div>


* ⚠ **WARN** OS/2 VendorID value 'NONE' is not yet recognized. If you registered it recently, then it's safe to ignore this warning message. Otherwise, you should set it to your own unique 4 character code, and register it with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx
 [code: unknown]
</div></details><details><summary>⚠ <b>WARN:</b> Check Google Fonts glyph coverage. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyph_coverage">com.google.fonts/check/glyph_coverage</a>)</summary><div>


* ⚠ **WARN** GF_Cyrillic_Core is almost fulfilled. Missing codepoints:

	- 0x0400 (CYRILLIC CAPITAL LETTER IE WITH GRAVE)


	- 0x040D (CYRILLIC CAPITAL LETTER I WITH GRAVE)


	- 0x041E (CYRILLIC CAPITAL LETTER O)


	- 0x041F (CYRILLIC CAPITAL LETTER PE)


	- 0x0406 (CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I)


	- 0x0450 (CYRILLIC SMALL LETTER IE WITH GRAVE)
 

	- 0x045D (CYRILLIC SMALL LETTER I WITH GRAVE)
 [code: missing-codepoints]
* ⚠ **WARN** GF_Greek_Core is almost fulfilled. Missing codepoints:

	- 0x03CF (GREEK CAPITAL KAI SYMBOL)


	- 0x03C2 (GREEK SMALL LETTER FINAL SIGMA)


	- 0x03AF (GREEK SMALL LETTER IOTA WITH TONOS)


	- 0x03CA (GREEK SMALL LETTER IOTA WITH DIALYTIKA)


	- 0x0390 (GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS)


	- 0x03CB (GREEK SMALL LETTER UPSILON WITH DIALYTIKA)


	- 0x03B0 (GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS)


	- 0x03D7 (GREEK KAI SYMBOL)


	- 0x0387 (GREEK ANO TELEIA)


	- 0x037E (GREEK QUESTION MARK)
 

	- 4 more.

Use -F or --full-lists to disable shortening of long lists. [code: missing-codepoints]
</div></details><details><summary>⚠ <b>WARN:</b> Are there caret positions declared for every ligature? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/ligature_carets">com.google.fonts/check/ligature_carets</a>)</summary><div>


* ⚠ **WARN** This font lacks caret position values for ligature glyphs on its GDEF table. [code: lacks-caret-pos]
</div></details><details><summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences">com.google.fonts/check/kerning_for_non_ligated_sequences</a>)</summary><div>


* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:

	- f + i 

	- i + l [code: lacks-kern-info]
</div></details><details><summary>⚠ <b>WARN:</b> Ensure fonts have ScriptLangTags declared on the 'meta' table. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/meta/script_lang_tags">com.google.fonts/check/meta/script_lang_tags</a>)</summary><div>


* ⚠ **WARN** This font file does not have a 'meta' table. [code: lacks-meta-table]
</div></details><details><summary>⚠ <b>WARN:</b> Font contains '.notdef' as its first glyph? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/mandatory_glyphs">com.google.fonts/check/mandatory_glyphs</a>)</summary><div>


* ⚠ **WARN** Glyph '.notdef' should contain a drawing, but it is empty. [code: empty]
</div></details><details><summary>⚠ <b>WARN:</b> Check font contains no unreachable glyphs (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/unreachable_glyphs">com.google.fonts/check/unreachable_glyphs</a>)</summary><div>


* ⚠ **WARN** The following glyphs could not be reached by codepoint or substitution rules:

	- i.loclTRK

	- periodcentered.loclCAT

	- periodcentered.loclCAT.case 

	- uni030C.alt
 [code: unreachable-glyphs]
</div></details><details><summary>⚠ <b>WARN:</b> Ensure dotted circle glyph is present and can attach marks. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/dotted_circle">com.google.fonts/check/dotted_circle</a>)</summary><div>


* ⚠ **WARN** No dotted circle glyph present [code: missing-dotted-circle]
</div></details><details><summary>⚠ <b>WARN:</b> Check math signs have the same width. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/math_signs_width">com.google.fonts/check/math_signs_width</a>)</summary><div>


* ⚠ **WARN** The most common width is 403 among a set of 3 math glyphs.
The following math glyphs have a different width, though:

Width = 586:
plusminus, plus

Width = 556:
greater, less

Width = 502:
minus, logicalnot

Width = 528:
multiply

Width = 368:
approxequal

Width = 438:
greaterequal, lessequal
 [code: width-outliers]
</div></details><details><summary>⚠ <b>WARN:</b> Checking Vertical Metric Linegaps. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/linegaps">com.google.fonts/check/linegaps</a>)</summary><div>


* ⚠ **WARN** OS/2 sTypoLineGap is not equal to 0. [code: OS/2]
</div></details><details><summary>⚠ <b>WARN:</b> Are there any misaligned on-curve points? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_alignment_miss">com.google.fonts/check/outline_alignment_miss</a>)</summary><div>


* ⚠ **WARN** The following glyphs have on-curve points which have potentially incorrect y coordinates:

	* Q (U+0051): X=433.0,Y=-192.0 (should be at descender -193?)

	* Q (U+0051): X=333.0,Y=-192.0 (should be at descender -193?)

	* grave (U+0060): X=105.0,Y=630.0 (should be at ascender 631?)

	* grave (U+0060): X=60.0,Y=630.0 (should be at ascender 631?)

	* uni00B2 (U+00B2): X=256.0,Y=629.0 (should be at ascender 631?)

	* uni00B2 (U+00B2): X=106.0,Y=629.0 (should be at ascender 631?)

	* Oslash (U+00D8): X=330.0,Y=-2.0 (should be at baseline 0?)

	* Oslash (U+00D8): X=248.0,Y=-2.0 (should be at baseline 0?)

	* egrave (U+00E8): X=220.0,Y=630.0 (should be at ascender 631?)

	* egrave (U+00E8): X=175.0,Y=630.0 (should be at ascender 631?) 

	* 86 more.

Use -F or --full-lists to disable shortening of long lists. [code: found-misalignments]
</div></details><details><summary>ℹ <b>INFO:</b> Show hinting filesize impact. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/hinting_impact">com.google.fonts/check/hinting_impact</a>)</summary><div>


* ℹ **INFO** Hinting filesize impact:

 |               | Pixelfy Sans[wght].ttf          |
 |:------------- | ---------------:|
 | Dehinted Size | 86.4kb |
 | Hinted Size   | 86.4kb   |
 | Increase      | 24 bytes      |
 | Change        | 0.0 %  |
 [code: size-impact]
</div></details><details><summary>ℹ <b>INFO:</b> Font has old ttfautohint applied? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/old_ttfautohint">com.google.fonts/check/old_ttfautohint</a>)</summary><div>


* ℹ **INFO** Could not detect which version of ttfautohint was used in this font. It is typically specified as a comment in the font version entries of the 'name' table. Such font version strings are currently: ['Version 1.000;gftools[0.9.32]'] [code: version-not-detected]
</div></details><details><summary>ℹ <b>INFO:</b> EPAR table present in font? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/epar">com.google.fonts/check/epar</a>)</summary><div>


* ℹ **INFO** EPAR table not present in font. To learn more see https://github.com/googlefonts/fontbakery/issues/818 [code: lacks-EPAR]
</div></details><details><summary>ℹ <b>INFO:</b> Is the Grid-fitting and Scan-conversion Procedure ('gasp') table set to optimize rendering? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/gasp">com.google.fonts/check/gasp</a>)</summary><div>


* ℹ **INFO** These are the ppm ranges declared on the gasp table:

PPM <= 65535:
	flag = 0x0F
	- Use grid-fitting
	- Use grayscale rendering
	- Use gridfitting with ClearType symmetric smoothing
	- Use smoothing along multiple axes with ClearType®
 [code: ranges]
</div></details><details><summary>ℹ <b>INFO:</b> Check for font-v versioning. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/fontv">com.google.fonts/check/fontv</a>)</summary><div>


* ℹ **INFO** Version string is: "Version 1.000;gftools[0.9.32]"
The version string must ideally include a git commit hash and either a "dev" or a "release" suffix such as in the example below:
"Version 1.3; git-0d08353-release" [code: bad-format]
</div></details><details><summary>ℹ <b>INFO:</b> Font contains all required tables? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/required_tables">com.google.fonts/check/required_tables</a>)</summary><div>


* ℹ **INFO** This font contains the following optional tables:

	- loca

	- prep

	- GPOS

	- GSUB 

	- gasp [code: optional-tables]
</div></details><details><summary>ℹ <b>INFO:</b> List all superfamily filepaths (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/superfamily/list">com.google.fonts/check/superfamily/list</a>)</summary><div>


* ℹ **INFO** . [code: family-path]
</div></details><br></div></details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 11 | 11 | 104 | 8 | 112 | 0 |
| 0% | 4% | 4% | 42% | 3% | 46% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **PASS**
* **DEBUG**

Don't hesitate if you have any questions!
Cheers!
Emma

**Comment by eifetx** [comment]
hello @emmamarichal . thank you for responding.
im just checked file from your attached, im still working on it.

my questions,

1. If this font can be boarding on Google Fonts, is it possible for me to only want "regular" only ?  think there are too many warnings on this axis font

2. After I fix this font, can I just attach it here or do I have to update the repository?

**Comment by emmamarichal** [comment]
Hi @eifetx,

Don't worry about the warning about the weight axis, I often have them and I can fix it easily. 
And yes, you can update the repo with the new files, tell me when it's updated :) 

Thanks a lot!

**Comment by eifetx** [comment]
hi @emmamarichal 

thank you in advance you have helped a lot

I have fixed and have updated my repo. if what I fixed still has issues, please let me know.
