### ISSUE TITLE
Add Sahabat Kecil

### ISSUE THREAD

**Issue by eifetx** [google/fonts#6010]

**Comment by Daymarius** [comment]
What is the difference with Aileron?

**Comment by eifetx** [comment]
> What is the difference with Aileron?

there's so many difference with aileron. from the shape, character set, language support. and many more

**Comment by davelab6** [comment]
@eifetx thanks - please could you provide more visual explanations of this issue? For now I would prioritize adding actual Aileron over your project, when I can't really tell the value added here, but I'm happy to reconsider if you can persuade us :)

**Comment by davelab6** [comment]
Hmm, it seems Vegur and Ailreon's upstream has deleted the projects, so, I think this is good to go.

**Comment by davelab6** [comment]
@eifetx I am still in interested in the comparison tho :)

**Comment by kenmcd** [comment]
Ailreon has italics. This does not.

Characters added:
- 20 accented characters to Latin Extended-A
- 1 character to Latin Extended-B

OpenType features appear to be the same except Ailreon has `mark` and this does not.

Conversion to variable would be relatively easy because of clean originals. (only 28 mis-matches in roman)

**Comment by eifetx** [comment]
> @eifetx I am still in interested in the comparison tho :)

Hi Daves!
After I researched about the Aileron font, and I immediately realized that the font that I have been developing for 3 years is really very similar to Aileron. My inspiration for making this font is from the Roboto font. I know this Aileron font from someone who commented on my repo.

I conclude, that this Aileron has an italic style, and some characters that don't exist. Here's an example:

In the little friend font there is no iItalic version and some characters. Here's an example:

If you have any problems with Sahabat Kecil font, let me know.
Thank you Dave!

![prev1-100](https://user-images.githubusercontent.com/123919967/226096589-45ec9e73-08a5-4f09-9d44-99d517c1986a.jpg)
![prev2-100](https://user-images.githubusercontent.com/123919967/226096593-348effde-1a35-44e5-9d06-02f838619a13.jpg)

**Comment by RosaWagner** [comment]
So I took the sources from Sahabat Kecil and overlay some outlines of the Regular master from Aileron Regular style that you can download everywhere. They are exactly the same, to the points coordinates, sidebearing and kerning values. Just to confirm that this is a fork, not an inspiration.

@eifetx the open source license authorizes to appropriate other people's work and publish it under the same open source license. Now there is a minimal ethic about that: the first one is to be honest about the project you appropriate and respect the original authors.

I personally wouldn't vouch in onboarding the font unless:
- TypoType is contacted and they confirm they are okay with it, maybe they would actually prefer to make their own sources available.
- the mistake is fixed in the license and the README; the fork needs to be clearly stated in the description.
- @eifetx is not credited as the original author of font, but as contributor instead. Adding few accented glyphs from existing components is not an act of original design.
- trademark gets removed
- the font shows a significant change/improvement. The least would be: better spacing, larger glyphset, more styles.

**Comment by eifetx** [comment]
@RosaWagner hi again rosa, I'm really sorry about posting this font. one of our work team is manipulating about the font and the font description. after I told you about your comment, he just admitted that he was manipulating. yes, better this font isn't board to google font. I'm very sorry.
and I will close this post/repo.

**Comment by eifetx** [comment]
@RosaWagner hi again rosa, I'm really sorry about posting this font. one of our work team is manipulating about the font and the font description. after I told you about your comment, he just admitted that he was manipulating. yes, better this font isn't board to google font. I'm very sorry.
and I will close this post/repo.
