### ISSUE TITLE
Hebrew: Some misplaced nikud under double-yud and double-vov digraphs

### ISSUE THREAD

**Issue by emmamarichal** [google/fonts#6062]
Is there anyone who knows Hebrew who would know how to solve this problem? I tried to add anchors on the "yodyod-hb", but nothing changes. Thanks!

**Specify the font name in title with a short description of the bug.**
Frank Ruhl Libre

**Describe the bug**
A designer has this issue https://github.com/fontef/frankruhllibre/issues/16, and I noticed that some other fonts seem to have the same problem (sometime this sign even doesn't appear).

<img width="1364" alt="Capture d’écran 2023-03-22 à 14 25 28" src="https://user-images.githubusercontent.com/64773544/226918900-dd5ff1fb-583e-49dc-af21-ee1bf9354122.png">

**To Reproduce**
Sample:
װַײלע מײַנע

**Expected behavior**
"patah-hb" should be centered

**Additional context**
This is the mail I received from the designer:

> Here attached are screen shots of both the libre and non-libre (MS) version of this font with some relevant sample text shown in FontBook on my Mac.
> 
> Here's the sample text used in the screen shots: װַײלע מײַנע
> 
> In each screen shot, each of the two digraph characters is shown with a diacritic (Unicode Character 'HEBREW POINT PATAH' (U+05B7)).  The libre version centers the diacritic under the leftmost subcharacter of the digraph, which is incorrect: it should be centered with respect to both characters, or ideally with respect to the midpoint of the two stems of each subcharacter, but just centered would be a lot better.  Actually, the positioning of the diacritic for the double-vov in the MS version is slightly too far left, but that's a fine point....
> 
> Anyhow, I cannot understand why the Libre font is doing what it's doing -- positioning the diacritic with respect to the left subcharacter, since I cannot understand this format well enough.

![FR-libre-wrong-double-vov-wrong-double-yud-Screen Shot 2023-03-21 at 5 03 21 PM](https://user-images.githubusercontent.com/64773544/226920727-294574f8-d357-4f13-8968-405b1a5acc70.png)
![FR-MS-ok-double-vov-good-double-yud-Screen Shot 2023-03-21 at 5 04 47 PM](https://user-images.githubusercontent.com/64773544/226920728-1cf0e480-aa4a-4b67-865f-569fa100fd7b.png)

**Comment by RosaWagner** [comment]
c'est quelque chose qu'on a corrigé dans Rubik si je me souviens bien; peut-être jette un œil dans les sources (+features ccmp etc)

**Comment by tiroj** [comment]
Check that U+05F2 is not being decomposed by the shaping engine. It should not be, because the Yiddish digraphs do not have either canonical or compatibility decompositions in Unicode, but shaping engine handling of Hebrew is complicated by the need to work around broken normalisation in Unicode, so possibly someone got carried away.

**Comment by simoncozens** [comment]
That or this is being treated as a ligature so needs lig anchors. I'll take a look, anyway.

**Comment by simoncozens** [comment]
> That or this is being treated as a ligature

Yes, this is exactly the issue. You need to explicitly set the Glyphs category and subcategory to something like `Letter`/`Other` or else this will be treated as a ligature. Then you can add ordinary anchors.

<img width="637" alt="Screenshot 2023-03-23 at 09 33 43" src="https://user-images.githubusercontent.com/106728/227161747-3d5effb6-9c4d-4351-bc28-11440b05abc0.png">

![shape](https://user-images.githubusercontent.com/106728/227161827-f3b84716-d654-4340-98e7-3eb81528c5e0.png)

**Comment by chrissimpkins** [comment]
Simon posted this issue on Glyphs forum

**Comment by simoncozens** [comment]
> Simon posted this issue on Glyphs forum

I did, and Georg will fix it in upcoming versions of Glyphs (and so *if* we get the GlyphInfo.xml file into a glyphsLib release and *if* the affected fonts have anchors in their sources, and *if* we re-build and onboard them, then all will be well), but I always advise everyone working on any "interesting" scripts with Glyphs.app to make sure that they set the category and subcategory explicitly for all their glyphs rather than relying on the automatic category assignments; it will avoid this kind of mistake.
