### ISSUE TITLE
Inconsolata: inconsistent ss03

### ISSUE THREAD

**Issue by palacz-uj** [google/fonts#611]
Single and double ASCII quotes in the original Inconsolata font are slightly curled. In the 2.000 version they were straightened. Their original, curled variants were (I guess) supposed to move to stylistic set 3, but only quotesingle.ss03 is slanted. quotedbl.ss03 is straight, which is probably a bug.

Also, is there any documentation explaining the use of stylistic sets in this new Inconsolata version? Neither FONTLOG.txt nor DESCRIPTION.en_us.html contain any information about these changes.

**Comment by m4rc1e** [comment]
@alexeiva 

![screen shot 2017-01-28 at 18 57 01](https://cloud.githubusercontent.com/assets/7525512/22399037/a0da1af2-e58b-11e6-8ae4-903610feff1e.png)

@palacz-uj  thanks

**Comment by alexeiva** [comment]
@palacz-uj Thanks for reporting. This is fixed in https://github.com/cyrealtype/Inconsolata/commit/3599deda3fb061ad2bfb4d3bd394c259e8b5400e

![screen shot 2017-02-01 at 1 28 16 pm](https://cloud.githubusercontent.com/assets/16634089/22503375/814b8c26-e882-11e6-9c65-1362f557e193.png)

@m4rc1e please update upstream
