### ISSUE TITLE
Noto Sans Japanese of any weight is displayed as Thin.

### ISSUE THREAD

**Issue by ShigeUe** [google/fonts#6187]
**Describe the bug**
When checking elements with the web font Noto Sans JP applied in Chrome's Developer Tools, all rendered fonts are shown as `Noto Sans JP Thin` .

**Screenshots**
[![Shot](https://i.gyazo.com/1ae615825d5f0cbf1b8543e9df576364.png)](https://gyazo.com/1ae615825d5f0cbf1b8543e9df576364)  
In the screenshot above, a font with font-weight: 400 is applied.

**Additional context**
The version of Chrome is 112.0.5615.87. It happens on both Windows and Mac.

**Comment by RosaWagner** [comment]
Hi @ShigeUe, thanks for your report. It might be that Chrome is showing the "full font name", ie the family name of the typeface and the style origin. Indeed, all variable fonts have a "default" style, which is the one an app would fallback to in case it doesn't support the variable font format. For Noto Sans JP, it is the Thin style. I don't know why Chrome's Developer Tools show the variable font's full font name instead of family name + chosen style name, but this not a font bug.

More informations about the variable font format in this document: https://learn.microsoft.com/en-us/typography/opentype/spec/otvaroverview

**Comment by fitojb** [comment]
Does it make sense to forward this issue to the bug tracker at crbug.com, or is there a better way to engage the Chrome team?
