### ISSUE TITLE
Add Kode Mono VF

### ISSUE THREAD

**Issue by isaozler** [google/fonts#6191]
[**https://github.com/isaozler/kode-mono**](https://github.com/isaozler/kode-mono)

A custom-designed typeface explicitly created for the developer community.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

![Kode Mono cover](https://github.com/isaozler/kode-mono/raw/main/documentation/image1.png)

**Comment by RosaWagner** [comment]
## Fontbakery report

Fontbakery version: 0.8.13

<details><summary><b>[1] Family checks</b></summary><div><details><summary>ℹ <b>INFO:</b> Check axis ordering on the STAT table.  (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/STAT/axis_order">com.google.fonts/check/STAT/axis_order</a>)</summary><div>


* ℹ **INFO** From a total of 1 font files, 0 of them (0.00%) lack a STAT table.

	And these are the most common STAT axis orderings:
	('wght', 1) [code: summary]
</div></details><br></div></details><details><summary><b>[30] KodeMono[wght].ttf</b></summary><div><details><summary>🔥 <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/family/win_ascent_and_descent">com.google.fonts/check/family/win_ascent_and_descent</a>)</summary><div>


* 🔥 **FAIL** OS/2.usWinDescent value should be equal or greater than 1000, but got 640 instead. [code: descent]
</div></details><details><summary>🔥 <b>FAIL:</b> Ensure soft_dotted characters lose their dot when combined with marks that replace the dot. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/soft_dotted">com.google.fonts/check/soft_dotted</a>)</summary><div>


* 🔥 **FAIL** The dot of soft dotted characters used in orthographies must disappear in the following strings: i̊ i̋ i̍ i̐ i̓ j̀ j́ j̃ j̄ j̈ j̑ į̀ į́ į̂ į̃ į̄ į̌ ɨ̀ ɨ́ ɨ̂ ɨ̃ ɨ̄ ɨ̈ ɨ̋ ɨ̌ ɨ̏ ɨ̧̀ ɨ̧́ ɨ̧̂ ɨ̧̌ ɨ̱̀ ɨ̱́ ɨ̱̈ ḭ̀ ḭ́ ḭ̄ ị̀ ị́ ị̂ ị̃ ị̄

The dot of soft dotted characters should disappear in other cases, for example: i̅ i̇ i̎ i̒ i̔ i̖̅ i̖̇ i̖̊ i̖̋ i̖̍ i̖̎ i̖̐ i̖̒ i̖̓ i̖̔ i̗̅ i̗̇ i̗̊ i̗̋ i̗̍ [code: soft-dotted]
</div></details><details><summary>🔥 <b>FAIL:</b> Checking font version fields (head and name table). (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/head.html#com.google.fonts/check/font_version">com.google.fonts/check/font_version</a>)</summary><div>


* 🔥 **FAIL** head version is "1.01601" while name version string (for platform 3, encoding 1) is "Version 1.000;gftools[0.9.28]". [code: mismatch]
</div></details><details><summary>⚠ <b>WARN:</b> DESCRIPTION.en_us.html should end in a linebreak. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/eof_linebreak">com.google.fonts/check/description/eof_linebreak</a>)</summary><div>


* ⚠ **WARN** The last characther on DESCRIPTION.en_us.html is not a line-break. Please add it. [code: missing-eof-linebreak]
</div></details><details><summary>⚠ <b>WARN:</b> Checking OS/2 achVendID. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vendor_id">com.google.fonts/check/vendor_id</a>)</summary><div>


* ⚠ **WARN** OS/2 VendorID value 'KDA' is not yet recognized. If you registered it recently, then it's safe to ignore this warning message. Otherwise, you should set it to your own unique 4 character code, and register it with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx
 [code: unknown]
</div></details><details><summary>⚠ <b>WARN:</b> Check for codepoints not covered by METADATA subsets. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/unreachable_subsetting">com.google.fonts/check/metadata/unreachable_subsetting</a>)</summary><div>


* ⚠ **WARN** The following codepoints supported by the font are not covered by
    any subsets defined in the font's metadata file, and will never
    be served. You can solve this by either manually adding additional
    subset declarations to METADATA.pb, or by editing the glyphset
    definitions.

 * U+02C7 CARON: try adding one of: tifinagh, canadian-aboriginal
 * U+02D8 BREVE: try adding canadian-aboriginal
 * U+02D9 DOT ABOVE: try adding canadian-aboriginal
 * U+02DB OGONEK: try adding canadian-aboriginal
 * U+0300 COMBINING GRAVE ACCENT: try adding one of: cherokee, tai-le, coptic, old-permic
 * U+0301 COMBINING ACUTE ACCENT: try adding one of: osage, cherokee, tai-le, tifinagh, coptic
 * U+0302 COMBINING CIRCUMFLEX ACCENT: try adding one of: cherokee, math, coptic, tifinagh
 * U+0303 COMBINING TILDE: try adding one of: syriac, glagolitic, math
 * U+0304 COMBINING MACRON: try adding one of: gothic, syriac, osage, cherokee, caucasian-albanian, tifinagh, coptic
 * U+0305 COMBINING OVERLINE: try adding one of: gothic, elbasan, glagolitic, math, coptic 
 33 more.

Use -F or --full-lists to disable shortening of long lists.

Or you can add the above codepoints to one of the subsets supported by the font: `latin`, `latin-ext`, `menu` [code: unreachable-subsetting]
</div></details><details><summary>⚠ <b>WARN:</b> License URL matches License text on name table? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/license_url">com.google.fonts/check/name/license_url</a>)</summary><div>


* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=14] [code: http-in-license-info]
</div></details><details><summary>⚠ <b>WARN:</b> A static fonts directory with at least two fonts must accompany variable fonts (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/repo/vf_has_static_fonts">com.google.fonts/check/repo/vf_has_static_fonts</a>)</summary><div>


* ⚠ **WARN** Please consider adding a subdirectory called "static/" and including in it static font files. [code: missing]
</div></details><details><summary>⚠ <b>WARN:</b> Check font follows the Google Fonts vertical metric schema (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vertical_metrics">com.google.fonts/check/vertical_metrics</a>)</summary><div>


* ⚠ **WARN** We recommend the absolute sum of the hhea metrics should be between 1.2-1.5x of the font's upm. This font has 1.549x (3098) [code: bad-hhea-range]
</div></details><details><summary>⚠ <b>WARN:</b> METADATA.pb: Designers are listed correctly on the Google Fonts catalog? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/designer_profiles">com.google.fonts/check/metadata/designer_profiles</a>)</summary><div>


* ⚠ **WARN** It seems that Isa Ozler is still not listed on the designers catalog. Please submit a photo and a link to a webpage where people can learn more about the work of this designer/typefoundry. [code: profile-not-found]
</div></details><details><summary>⚠ <b>WARN:</b> Ensure variable fonts include an avar table. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/mandatory_avar_table">com.google.fonts/check/mandatory_avar_table</a>)</summary><div>


* ⚠ **WARN** This variable font does not have an avar table. [code: missing-avar]
</div></details><details><summary>⚠ <b>WARN:</b> Ensure Stylistic Sets have description. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/stylisticset_description">com.google.fonts/check/stylisticset_description</a>)</summary><div>


* ⚠ **WARN** The stylistic set ss03 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss04 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss06 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss07 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss09 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss10 lacks a description string on the 'name' table. [code: missing-description]
</div></details><details><summary>⚠ <b>WARN:</b> Ensure fonts have ScriptLangTags declared on the 'meta' table. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/meta/script_lang_tags">com.google.fonts/check/meta/script_lang_tags</a>)</summary><div>


* ⚠ **WARN** This font file does not have a 'meta' table. [code: lacks-meta-table]
</div></details><details><summary>⚠ <b>WARN:</b> Glyph names are all valid? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/valid_glyphnames">com.google.fonts/check/valid_glyphnames</a>)</summary><div>


* ⚠ **WARN** The following glyph names may be too long for some legacy systems which may expect a maximum 31-char length limit:
greater_greater_equal_middle.seq, greater_greater_hyphen_middle.seq, greater_greater_hyphen_start.seq and numbersign_underscore_parenleft.liga [code: legacy-long-names]
</div></details><details><summary>⚠ <b>WARN:</b> Check font contains no unreachable glyphs (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/unreachable_glyphs">com.google.fonts/check/unreachable_glyphs</a>)</summary><div>


* ⚠ **WARN** The following glyphs could not be reached by codepoint or substitution rules:

	- acute.case.loclPLK

	- at.spacer

	- braceright.spacer

	- commareversedbelowcomb.case

	- l.spacer

	- parenleft.spacer

	- strokelongoverlay 

	- strokeshortoverlay
 [code: unreachable-glyphs]
</div></details><details><summary>⚠ <b>WARN:</b> Does the font contain a soft hyphen? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/soft_hyphen">com.google.fonts/check/soft_hyphen</a>)</summary><div>


* ⚠ **WARN** This font has a 'Soft Hyphen' character. [code: softhyphen]
</div></details><details><summary>⚠ <b>WARN:</b> Detect any interpolation issues in the font. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/interpolation_issues">com.google.fonts/check/interpolation_issues</a>)</summary><div>


* ⚠ **WARN** Interpolation issues were found in the font: 	- Contour order differs in glyph 'bar_bar.liga': [0, 1] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x109c1e970>, [1, 0] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x109c1e070>.

	- Contour order differs in glyph 'bar_bar_equal_end.seq': [0, 1, 2, 3] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x109c1e970>, [1, 0, 2, 3] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x109c1e070>.

	- Contour order differs in glyph 'bar_bar_equal_start.seq': [0, 1, 2, 3] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x109c1e970>, [1, 0, 2, 3] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x109c1e070>.

	- Contour order differs in glyph 'bar_bar_greater.liga': [0, 1, 2] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x109c1e970>, [0, 2, 1] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x109c1e070>.

	- Contour order differs in glyph 'bar_bar_hyphen_end.seq': [0, 1, 2] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x109c1e970>, [1, 0, 2] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x109c1e070>.

	- Contour order differs in glyph 'bar_bar_hyphen_middle.seq': [0, 1, 2, 3] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x109c1e970>, [1, 0, 2, 3] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x109c1e070>.

	- Contour order differs in glyph 'bar_bar_hyphen_start.seq': [0, 1, 2] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x109c1e970>, [1, 0, 2] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x109c1e070>. 

	- Contour order differs in glyph 'less_bar_bar.liga': [0, 1, 2] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x109c1e970>, [0, 2, 1] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x109c1e070>. [code: interpolation-issues]
</div></details><details><summary>⚠ <b>WARN:</b> Checking correctness of monospaced metadata. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/name.html#com.google.fonts/check/monospace">com.google.fonts/check/monospace</a>)</summary><div>


* ⚠ **WARN** The OpenType spec recomments at https://learn.microsoft.com/en-us/typography/opentype/spec/recom#hhea-table that hhea.numberOfHMetrics be set to 3 but this font has 1 instead.
Please read https://github.com/fonttools/fonttools/issues/3014 to decide whether this makes sense for your font. [code: bad-numberOfHMetrics]
</div></details><details><summary>⚠ <b>WARN:</b> Check glyphs in mark glyph class are non-spacing. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/gdef.html#com.google.fonts/check/gdef_spacing_marks">com.google.fonts/check/gdef_spacing_marks</a>)</summary><div>


* ⚠ **WARN** The following spacing glyphs may be in the GDEF mark glyph class by mistake:
	 acute (U+00B4), acute.case (unencoded), acutebelowcomb (U+0317), acutecomb (U+0301), breve (U+02D8), breve.case (unencoded), brevebelowcomb (U+032E), brevecomb (U+0306), breveinvertedbelowcomb (U+032F), breveinvertedcomb (U+0311) and 54 more.

Use -F or --full-lists to disable shortening of long lists. [code: spacing-mark-glyphs]
</div></details><details><summary>⚠ <b>WARN:</b> Check mark characters are in GDEF mark glyph class. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/gdef.html#com.google.fonts/check/gdef_mark_chars">com.google.fonts/check/gdef_mark_chars</a>)</summary><div>


* ⚠ **WARN** The following mark characters could be in the GDEF mark glyph class:
	 strokelongcomb (U+0336) and strokeshortcomb (U+0335) [code: mark-chars]
</div></details><details><summary>⚠ <b>WARN:</b> Check GDEF mark glyph class doesn't have characters that are not marks. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/gdef.html#com.google.fonts/check/gdef_non_mark_chars">com.google.fonts/check/gdef_non_mark_chars</a>)</summary><div>


* ⚠ **WARN** The following non-mark characters should not be in the GDEF mark glyph class:
	 U+00A8, U+00AF, U+00B4, U+00B8, U+02C6, U+02D8, U+02D9, U+02DA, U+02DB, U+02DC, U+02DD and U+2018 [code: non-mark-chars]
</div></details><details><summary>⚠ <b>WARN:</b> Are there any misaligned on-curve points? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_alignment_miss">com.google.fonts/check/outline_alignment_miss</a>)</summary><div>


* ⚠ **WARN** The following glyphs have on-curve points which have potentially incorrect y coordinates:

	* degree (U+00B0): X=709.0,Y=1398.0 (should be at cap-height 1400?)

	* Thorn (U+00DE): X=160.0,Y=-1.0 (should be at baseline 0?)

	* Thorn (U+00DE): X=320.0,Y=-1.0 (should be at baseline 0?)

	* edieresis (U+00EB): X=720.0,Y=1398.0 (should be at cap-height 1400?)

	* edieresis (U+00EB): X=919.0,Y=1398.0 (should be at cap-height 1400?)

	* odieresis (U+00F6): X=720.0,Y=1398.0 (should be at cap-height 1400?)

	* odieresis (U+00F6): X=919.0,Y=1398.0 (should be at cap-height 1400?)

	* cdotaccent (U+010B): X=491.0,Y=1398.0 (should be at cap-height 1400?)

	* cdotaccent (U+010B): X=691.0,Y=1398.0 (should be at cap-height 1400?)

	* edotaccent (U+0117): X=500.0,Y=1398.0 (should be at cap-height 1400?) 

	* 15 more.

Use -F or --full-lists to disable shortening of long lists. [code: found-misalignments]
</div></details><details><summary>ℹ <b>INFO:</b> Does DESCRIPTION file contain a upstream Git repo URL? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/git_url">com.google.fonts/check/description/git_url</a>)</summary><div>


* ℹ **INFO** Found a git repo URL: https://github.com/isaozler/kode-mono [code: url-found]
</div></details><details><summary>ℹ <b>INFO:</b> Show hinting filesize impact. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/hinting_impact">com.google.fonts/check/hinting_impact</a>)</summary><div>


* ℹ **INFO** Hinting filesize impact:

 |               | /Users/rosalie/Desktop/kode-mono/fonts/ofl/kodemono/KodeMono[wght].ttf          |
 |:------------- | ---------------:|
 | Dehinted Size | 101.3kb |
 | Hinted Size   | 101.4kb   |
 | Increase      | 24 bytes      |
 | Change        | 0.0 %  |
 [code: size-impact]
</div></details><details><summary>ℹ <b>INFO:</b> Font has old ttfautohint applied? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/old_ttfautohint">com.google.fonts/check/old_ttfautohint</a>)</summary><div>


* ℹ **INFO** Could not detect which version of ttfautohint was used in this font. It is typically specified as a comment in the font version entries of the 'name' table. Such font version strings are currently: ['Version 1.000;gftools[0.9.28]'] [code: version-not-detected]
</div></details><details><summary>ℹ <b>INFO:</b> EPAR table present in font? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/epar">com.google.fonts/check/epar</a>)</summary><div>


* ℹ **INFO** EPAR table not present in font. To learn more see https://github.com/googlefonts/fontbakery/issues/818 [code: lacks-EPAR]
</div></details><details><summary>ℹ <b>INFO:</b> Is the Grid-fitting and Scan-conversion Procedure ('gasp') table set to optimize rendering? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/gasp">com.google.fonts/check/gasp</a>)</summary><div>


* ℹ **INFO** These are the ppm ranges declared on the gasp table:

PPM <= 65535:
	flag = 0x0F
	- Use grid-fitting
	- Use grayscale rendering
	- Use gridfitting with ClearType symmetric smoothing
	- Use smoothing along multiple axes with ClearType®
 [code: ranges]
</div></details><details><summary>ℹ <b>INFO:</b> Check for font-v versioning. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/fontv">com.google.fonts/check/fontv</a>)</summary><div>


* ℹ **INFO** Version string is: "Version 1.000;gftools[0.9.28]"
The version string must ideally include a git commit hash and either a "dev" or a "release" suffix such as in the example below:
"Version 1.3; git-0d08353-release" [code: bad-format]
</div></details><details><summary>ℹ <b>INFO:</b> Font contains all required tables? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/required_tables">com.google.fonts/check/required_tables</a>)</summary><div>


* ℹ **INFO** This font contains the following optional tables:

	- loca

	- prep

	- GPOS

	- GSUB 

	- gasp [code: optional-tables]
</div></details><details><summary>ℹ <b>INFO:</b> List all superfamily filepaths (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/superfamily/list">com.google.fonts/check/superfamily/list</a>)</summary><div>


* ℹ **INFO** /Users/rosalie/Desktop/kode-mono/fonts/ofl/kodemono [code: family-path]
</div></details><br></div></details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 3 | 19 | 47 | 9 | 168 | 0 |
| 0% | 1% | 8% | 19% | 4% | 68% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **PASS**
* **DEBUG**

## [Proof.zip](https://github.com/google/fonts/files/11956411/Proof.zip)

**Comment by RosaWagner** [comment]
> 🔥 FAIL: Checking OS/2 usWinAscent & usWinDescent. ([com.google.fonts/check/family/win_ascent_and_descent](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/family/win_ascent_and_descent))
🔥 FAIL OS/2.usWinDescent value should be equal or greater than 1000, but got 640 instead. [code: descent]

> ⚠ WARN: Check font follows the Google Fonts vertical metric schema ([com.google.fonts/check/vertical_metrics](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vertical_metrics))
⚠ WARN We recommend the absolute sum of the hhea metrics should be between 1.2-1.5x of the font's upm. This font has 1.549x (3098) [code: bad-hhea-range]

You can read https://googlefonts.github.io/gf-guide/metrics.html for more info about how to deal with vertical metrics

> ⚠ WARN: Check glyphs in mark glyph class are non-spacing. ([com.google.fonts/check/gdef_spacing_marks](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/gdef.html#com.google.fonts/check/gdef_spacing_marks))
⚠ WARN The following spacing glyphs may be in the GDEF mark glyph class by mistake:
acute (U+00B4), acute.case (unencoded), acutebelowcomb (U+0317), acutecomb (U+0301), breve (U+02D8), breve.case (unencoded), brevebelowcomb (U+032E), brevecomb (U+0306), breveinvertedbelowcomb (U+032F), breveinvertedcomb (U+0311) and 54 more.

You need to make sure all combining glyphs has anchors (cf https://googlefonts.github.io/gf-guide/outlines.html)

> ⚠ WARN: Does the font contain a soft hyphen? ([com.google.fonts/check/soft_hyphen](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/soft_hyphen))
⚠ WARN This font has a 'Soft Hyphen' character. [code: softhyphen]

you can remove all deprecated glyphs such as: soft hyphen, CR, .null

> 🔥 FAIL: Checking font version fields (head and name table). ([com.google.fonts/check/font_version](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/head.html#com.google.fonts/check/font_version))
🔥 FAIL head version is "1.01601" while name version string (for platform 3, encoding 1) is "Version 1.000;gftools[0.9.28]". [code: mismatch]

Yep, make sure version field are consistent

> ⚠ WARN: Detect any interpolation issues in the font. ([com.google.fonts/check/interpolation_issues](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/interpolation_issues))

Check what's reported here to be sure nothing is missed

You can ignore the rest.

**Comment by RosaWagner** [comment]
Hi @isaozler I finally have some time to look up into this submission. We decided that all your work to follow the guide and make the PR yourself should be rewarded by an acceptation ;)

In term of outlines issues this is what I found:

Caron shouldn't be the same as an apostrophe (cf http://diacritics.typo.cz/index.php?id=5)
 
<img width="204" alt="Screenshot 2023-07-05 at 11 43 15" src="https://github.com/google/fonts/assets/12222436/cd196c28-e4cc-475f-8491-ff8199c10575">

Dot should be placed to end up exactly in the middle of two L. 
<img width="275" alt="Screenshot 2023-07-05 at 11 42 14" src="https://github.com/google/fonts/assets/12222436/8167d5ba-d112-489b-b014-cb05e8620bd6">
<img width="185" alt="Screenshot 2023-07-05 at 11 43 04" src="https://github.com/google/fonts/assets/12222436/34eb642f-4272-4212-a831-911d242c4d57">

I don't know how voluntary this is but g has some strange proportions. Lower bowl should be bigger than the smaller bowl

<img width="411" alt="Screenshot 2023-07-05 at 11 54 57" src="https://github.com/google/fonts/assets/12222436/0dca211c-1780-4ee5-974a-19c6c6312d69">

**Comment by isaozler** [comment]
Hi @RosaWagner, this is so great to hear! So grateful you took the time to look into it. I will make sure the issues will get resolved as soon as possible. The g was actually on purpose, but I'll revise it.

**Comment by isaozler** [comment]
Hi @RosaWagner, I fixed all the issues/improvements except the check for all combining glyphs having anchors.

[Fix 1](https://github.com/isaozler/kode-mono/commit/6487407cf06abc2a330944f7a959778469adb03c)
[Fix 2](https://github.com/isaozler/kode-mono/commit/e8886e3387efbe06265567217b12e868f0e0b960)

---

✅  <img width="736" alt="image" src="https://github.com/google/fonts/assets/1378630/ba3814dc-d6d4-49f1-af8c-a241ac930e1b">


---

<img width="757" alt="image" src="https://github.com/google/fonts/assets/1378630/7ba5d096-8fb4-46e8-be79-e1b1281c60ab">

But this second warning still needs to be resolved. I checked all the anchors, and some combining glyphs were indeed missing anchors. Despite adding the missing anchors, the warning persists. So, I need to check that issue a bit closer.

**Comment by RosaWagner** [comment]
This warn means there is probably a confusion between legacy and combining marks. This chapter of the guide is pretty thorough about the topic: https://googlefonts.github.io/gf-guide/diacritics.html

**Comment by isaozler** [comment]
@RosaWagner should I ignore the "com.google.fonts/check/gdef_mark_chars" warning?

**Comment by RosaWagner** [comment]
Nope, you should set up your combining accent properly following the instruction in the guide.
- Combining marks (like acutecomb) should have anchors and be used as components in accented glyphs (like aacute)
- Legacy accent should be there without anchors (they can be made as component of the combining counterpart)
- update and compile features

**Comment by RosaWagner** [comment]
@isaozler do you have any update since my last comment or do you need help with it?

**Comment by isaozler** [comment]
> @isaozler do you have any update since my last comment or do you need help with it?

I was on holiday, just back last week. Can I ask for your help in case I get stuck?

**Comment by isaozler** [comment]
@RosaWagner, when do I need to push all updates/fixes to be on schedule for review/release?

**Comment by RosaWagner** [comment]
If you are stuck, don't hesitate. But I am no fluent in Fontlab. There are the useful tuto I found:
- https://help.fontlab.com/fontlab-vi/Tutorial-Building-accented-characters/
- https://help.fontlab.com/fontlab-vi/Anchors-and-Pins/

Apparently fontlab calls the "combining marks" > "non spacing accent", and "legacy accents" > "spacing marks" (which is also right), they have different unicodes. In your accented letters, you need 2 components/elements: le base letter + non spacing mark (for eg. `a` + `combining acute`). In both elements you have the outline + an anchor, so the elements can automatically get attached to each other without manual positioning in the composite glyph.

The spacing/legacy marks are just glyphs made as component from the combining marks, but without anchors.

There is no schedule, this repo is chaos.

**Comment by isaozler** [comment]
New PR link https://github.com/google/fonts/pull/7136

**Comment by isaozler** [comment]
Hi, @chrissimpkins 👋 Is there anything on my side you expect me to do to help the process?

The issues Rosa mentioned are all fixed. I also shared the new PR link #7136 fyi

**Comment by isaozler** [comment]
Any updates on this @chrissimpkins ? Can provide any input needed. Thanks in advance.

**Comment by chrissimpkins** [comment]
I discussed this with the onboarders today.  We added this project to the Q1 queue.  We will try to fit it in.  Thanks for the PR!

**Comment by isaozler** [comment]
Thanks! 🤞 great news! Looking forward to the onboarding 🙌

**Comment by isaozler** [comment]
Hi @emmamarichal, I'm just curious: the status is currently blocked, which Rosa initially changed from PR GF to Blocked in December due to needed fixes. Those are all resolved, and since Kode Mono moved to onboarding, is this still accurate?
