### ISSUE TITLE
All fonts provided by fonts.google.com cannot be viewed/installed in KDE Plasma on Linux

### ISSUE THREAD

**Issue by Sunspark-007** [google/fonts#6325]
**Describe the issue**
Any font obtained from fonts.google.com (e.g. Roboto), upon trying to double-click the file to open the font viewer, or selecting the file in the font manager results in an error of "Could not read font." or "<fontfilename> is not a font."

**To Reproduce**
Unzip the downloaded zip file from fonts.google.com, then double-click on the .ttf or .otf file in the file manager or select "Install from file" in font management and navigate to the .ttf or .otf file.

**Expected behavior**
The font should be displayed with the waterfall at different point sizes and be able to be successfully installed.

**Additional context**
This issue is specific to fonts served by fonts.google.com. ALL other sites/sources of .ttf/.otf fonts can be viewed/installed. Something is happening with the fonts.google.com build system which is preventing the output from being used with KDE Plasma on Linux.

**Comment by kenmcd** [comment]
The "font" files downloaded from Google Fonts are ZIP files.
You need to un-zip them first to get to the font files inside.

**Comment by Sunspark-007** [comment]
> The "font" files downloaded from Google Fonts are ZIP files.
> You need to un-zip them first to get to the font files inside.

Thanks Ken. I did not initially state that this issue is after the .zip file contents have been extracted. I have updated the original comment to now indicate that unzipping the downloaded zip is a required step for reproducing.

**Comment by kenmcd** [comment]
The GF fonts are downloaded and install thousands of times per day, by thousands of users - and all of those users have no issues installing the fonts.
So it is highly unlikely there is an issue with the GF "build system."
Since you are getting a message that says the font file is not a font, perhaps there is an issue with the app used to extract the zip which is creating broken files.
You could also try testing those fonts on a different system, or OS, and see if the files are corrupted, or work there.

You can also test the font files on various online font tools:
Font Drop: https://fontdrop.info/
Wakamai Fondue: https://wakamaifondue.com/
Font Inspector: https://opentype.js.org/font-inspector.html
Bulletproof Font Tester: https://bulletproof.italic.space/
If those do not work, the font files are bad.
If those do work, you have an issue with your system.

My guess is the issue is with your system.
You can post a zip with the files here and I can test them for you.

**Comment by Sunspark-007** [comment]
file:///home/deck/Desktop/Roboto.zip

Font Drop: Spins endlessly saying "Parsing"
Wakamai Fondue: "Oops, I couldn’t handle that font!"
Font Inspector: "Error: Unsupported OpenType signature /* "

At this point, I switched over to Windows and downloaded the exact same family file.. and there is a difference. It is NOT my system. It is the build system. With the archive downloaded on Windows, the files are larger than 131 bytes in size, and they pass the tests on the websites on the links you shared.

file:///home/deck/Desktop/Roboto downloaded on Windows

So the question becomes, why is fonts.google.com serving up a dud 14.3 kilobyte file when downloaded on Linux and a 1.5 megabyte file when downloaded on Windows?

**Comment by Sunspark-007** [comment]
Unbelievable, I figured it out. It was a browser extension that was mangling it. Apparently, if a call to fonts.googleapis.com was being blocked, it was also blocking the zip file from being constructed properly. Interesting!
