### ISSUE TITLE
Update Source Sans 3

### ISSUE THREAD

**Issue by davelab6** [google/fonts#6394]
https://twitter.com/pauldhunt/status/1670749697911431168

**Comment by vitorsr** [comment]
Hi, @davelab6.

Source Code Pro’s STAT table seems to be broken on GF since the last update, I believe due to source and the following metadata changes:

- https://github.com/google/fonts/pull/4010/files#diff-faae3350a36e2582e3457dda069d4f0dedbd0f117194784d3e8d2fe7c523948bR11
- https://github.com/google/fonts/pull/4010/files#diff-faae3350a36e2582e3457dda069d4f0dedbd0f117194784d3e8d2fe7c523948bR20

In addition, the served version appears to be the 1.018 variable font family whereas the latest release is the following:

https://github.com/adobe-fonts/source-code-pro/releases/latest

Can we piggyback a Source Code Pro metadata fix and update to this issue?
