### ISSUE TITLE
'Normal' Font Weight Removed In Montserrat

### ISSUE THREAD

**Issue by tempusrname** [google/fonts#647]
New Montserrat went live. However the font-weight of the previous version is missing. Theres '400' but thats too thin compared to the '400' of the previous version. '500' is to thick compared to the '400' of the previous version. There isn't a middle ground. the '500' font weight of new version should have had the same thickness as the '400' of the previous one. Otherwise you practically removed a font weight. I'm kinda disappointed. The extra styles are nice but the previous font weight was perfect.

Comparison: https://ibb.co/nETG1F

I would like to know if this is something that will be fixed soon. If it won't be fixed I'll have to make the most of it and alter my CSS.

**Comment by dtweedle** [comment]
Adding to this, Montserrat's recent decision or oversight of moving what was previously the regular weight to what is now roughly medium has had some very annoying consequences.

Anyone that has previously installed Montserrat on their machine will not notice the changes since their local version will override the font. We now need to manually edit all of out prototypes and design files to match these updates, a lot of people will not notice these changes for some time.

**Comment by davelab6** [comment]
> I would like to know if this is something that will be fixed soon. If it won't be fixed I'll have to make the most of it and alter my CSS.

@julietaula and @juandelperal have to answer that

**Comment by dshimola** [comment]
Was there new information on this issue? Additionally, is there a hosted version of the font before the recent update?

**Comment by davelab6** [comment]
@dshimola new since when? :)

No, Google Fonts has no versioning exposed to end users. If you want to self-host a previous version, the libre license respects your freedom to do so.

**Comment by davelab6** [comment]
Please see the issue in the font project upstream

**Comment by gkiely** [comment]
For anyone coming from Google, Montserrat was updated, if you would like the old version the answer is to self host.
https://github.com/JulietaUla/Montserrat/issues/39#issuecomment-279740744
