### ISSUE TITLE
Update David Libre

### ISSUE THREAD

**Issue by markhdavid** [google/fonts#6518]
**Font Project Git Repo URL:** https://github.com/meirsadan/david-libre/

**Current version:** 1.003

**New available version:** 1.100

**Super short description of the upgrade:** Fix bad positioning of diacritics under Yiddish digraphs; fix component spacing for Yiddish ligatures; change qamats to "qamats qatan" form; add dlig feature for Yiddish ligatures and yod hiriq; add final kaf with dagesh, sheva and qamats forms.

**Bugs reported in this repo which this upgrade would fix:** (in David Libre repo:)
> https://github.com/meirsadan/david-libre/issues/19
> https://github.com/meirsadan/david-libre/issues/17
> https://github.com/meirsadan/david-libre/issues/16

Thanks to font designer/developer @meirsadan for the fixes and new version.
Thanks in advance to @emmamarichal for Google Fonts help.

**Comment by emmamarichal** [comment]
cc @davelab6 @chrissimpkins 
Any thoughts?
________________

I did a first quick review and update: https://github.com/emmamarichal/david-libre/commits/master

But there are still some issues that need to be fixed by the upstream:
- Glyphset to be completed (most of missing glyphs are easy to generate automatically.)
- No kerning
- Check accents
- Bonus/optional: make it variable and generate more styles by fixing the compatibility issues (see screenshot). It concerns mainly the Hebrew.

________________
<img width="468" alt="Capture d’écran 2023-07-12 à 15 15 24" src="https://github.com/google/fonts/assets/64773544/9e02ff31-2966-4a81-8aea-a7fe386f1df9">

________________

<img width="1272" alt="Capture d’écran 2023-07-13 à 10 45 54" src="https://github.com/google/fonts/assets/64773544/9b6a0101-efb4-4276-aee5-9dc933e218a5">

List of missing glyphs:
/Aogonek/Eogonek/Gcommaaccent/Hbar/Iogonek/Kcommaaccent/Lcaron/Lcommaaccent/Ncommaaccent/Rcommaaccent/Scedilla/Scommaaccent/Germandbls/Tcommaaccent/Uogonek/aogonek/dcaron/eogonek/gcommaaccent/hbar/idotaccent/iogonek/kcommaaccent/lcaron/lcommaaccent/ncommaaccent/rcommaaccent/scedilla/scommaaccent/tcaron/tcommaaccent/uogonek/exclamdown/questiondown/periodcentered.loclCAT/periodcentered.loclCAT.case/underscore/quotesinglbase/at/cent/yen/asciitilde/caroncomb.alt/commaturnedabovecomb/commaaccentcomb
________________
<img width="1598" alt="Capture d’écran 2023-07-13 à 10 55 34" src="https://github.com/google/fonts/assets/64773544/0d15e613-8621-41e1-8d50-d0e84b01bbe4">

**Comment by davelab6** [comment]
@markhdavid thanks for posting this issue to request GF to update to the latest upstream release. I agree with @emmamarichal there is more work to do upstream, so I'm adding appropriate tags for that, and reassigning to you for now. I'll post an issue on the upstream project's issue tracker, and ask that you keep discussion about development there and we use this issue to track only the process of onboarding into GF :)

**Comment by markhdavid** [comment]
> I'll post an issue on the upstream project's issue tracker

Here's a direct link to said issue for convenience:

https://github.com/meirsadan/david-libre/issues/20
