### ISSUE TITLE
Nuosu SIL - Apostrophe Space

### ISSUE THREAD

**Issue by lx-mstar** [google/fonts#6547]
Specify the font name in title with a short description of the bug. 
Please report any issue related to Noto fonts [here](https://notofonts.github.io/reporter.html).
Report any issue with Google Icon/Symbols [here](https://github.com/google/material-design-icons)

**Describe the bug**
Using the ' apostrophe seems to be adding trailing space. 
![image](https://github.com/google/fonts/assets/117708496/5586e015-b80f-4e51-acde-b29eda3c3de6)

It is specific to to the font as I can change the font and it displays as intended.  Also worth noting is if edit the text in the browser elements it is not an issue. 

Must be specific to the character output from WordPress. 

Feel free to view here: https://youareseen.com.au/do-not-underestimate-your-child/

**Expected behavior**

I would expect don't and not don' t. 

**Screenshots**
Attached above. 

**Additional context**
Add any other context about the problem here (OS version, browser, printer…)
Using WordPress with Divi. 
Google fonts are loaded on pageload.

**Comment by RosaWagner** [comment]
Hi @lx-mstar, thanks for your report. Nuosu SIL, as the description mentioned, is a font specifically made to support the Yi script in China. Therefore each character used for this script is having an equal width. The latin script contained in this font is really limited and is here to allow the display of the family name of the font in applications, or for short sentences in a Yi text.

You can eventually use the character `'` instead of `’` since this one seems to be specific to the latin script. But in a general way, if you wish to write only English, I would suggest to use a similar font but made to support primarily Latin script such as:
- [Cormorant Garamond](https://fonts.google.com/specimen/Cormorant+Garamond)
- [Baskervville](https://fonts.google.com/specimen/Baskervville)
- [Playfair](https://fonts.google.com/specimen/Playfair)
- [Stix two text](https://fonts.google.com/specimen/STIX+Two+Text)
