### ISSUE TITLE
Issue getting Mitr and Barlow fonts

### ISSUE THREAD

**Issue by ltenti-eventboost** [google/fonts#6553]
**Describe the bug**
I'm trying to get Mitr and Barlow fonts from Google Fonts API, but I get an error

**To Reproduce**
The following calls returns a "400: Missing font family" error:
https://fonts.googleapis.com/css2?family=Mitr:wght@200..700
https://fonts.googleapis.com/css2?family=Barlow:ital,wght@0,100..900;1,100..900

**Expected behavior**
To get the correct css with @font-face

**Comment by RosaWagner** [comment]
Hi @ltenti-eventboost, thanks for your report. We'll investigate.

**Comment by chrissimpkins** [comment]
Neither family is a variable font on production.  This is why the URL syntax fails here

**Comment by chrissimpkins** [comment]
You'll need to use a discrete weight rather than a weight range in your API call.  Try something like this instead:

https://fonts.googleapis.com/css2?family=Mitr:wght@200;300;400;500;600;700

See the ["Individual Style" CSS API docs](https://developers.google.com/fonts/docs/css2#individual_styles_such_as_weight) for additional details.  Hope it helps!
