### ISSUE TITLE
Oswald Medium and Semibold colon spacing bug

### ISSUE THREAD

**Issue by jukkasalm** [google/fonts#666]
Colons are squashed together in font weights 500 (Medium) and 600 (Semibold). 

https://fonts.google.com/specimen/Oswald

**Comment by m4rc1e** [comment]
Hey @jukkasalm this has been fixed in #659. 

It still needs to get pushed to the dev server.

**Comment by davelab6** [comment]
Thanks for reporting this! The fix is queued up and on its way out to
production soon :)

On Feb 17, 2017 6:27 PM, "Jukka Salminen" <notifications@github.com> wrote:

Semicolons are squashed together in font weights 500 (Medium) and 600
(Semibold).

https://fonts.google.com/specimen/Oswald

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/fonts/issues/666>, or mute the thread

**Comment by tombennet** [comment]
Hi @davelab6, any idea when this fix (#659) will go out to production? Thanks :)

**Comment by jukkasalm** [comment]
Still waiting for this fix to go live. Any updates on when? Thanks!

**Comment by james-spark** [comment]
Hi all, I'd be VERY interested to hear when the colon character is fixed as well!

Our new client loves the Oswald face, but we really need the colons to look right in all their presentations. 

Thanks!
James

**Comment by julienburns** [comment]
Ditto.

**Comment by TamaraBale** [comment]
Looking forward for colons to be fixed...

**Comment by Leland** [comment]
My doctor says I still need my colon examined but I'm hoping this PR does the trick.

**Comment by williamconifer** [comment]
This Colon issue is still present. When will the fix be live?

**Comment by combs** [comment]
Still seeing this in production.

**Comment by combs** [comment]
@m4rc1e did this slip through the cracks?

**Comment by davelab6** [comment]
@combs I bet you have the old version installed locally

**Comment by davelab6** [comment]
If you remove it, all should be well 

(You may need to check Adobe Fonts sync)

**Comment by m4rc1e** [comment]
I get the following

<img width="353" alt="screenshot 2018-12-05 at 16 04 33" src="https://user-images.githubusercontent.com/7525512/49526318-7d499000-f8a7-11e8-9c2d-a34446219007.png">

LGTM

**Comment by combs** [comment]
Ahhh, yes, I think you're right! Thank you!
