### ISSUE TITLE
Update Wavefont

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#6703]
**Font Project Git Repo URL:**
https://github.com/dy/wavefont

**Current version:**
3.004

**New available version:**
3.005 

**Super short description of the upgrade:**
~Addition of a WIDHT axis~
expanded weight axis' range and remap values

**Comment by dy** [comment]
Width axis wasn't added eventually. It's only linearized weight axis & expanded its range.
Npm version is new, which version should I bump?

**Comment by RosaWagner** [comment]
@dy the font version (in the name table) in your repo is still 3.004

**Comment by dy** [comment]
Got it. Bumped

**Comment by RosaWagner** [comment]
@dy while reviewing my PR, my colleague @vv-monsalve asked why not mapping 20 to 1 to have an Hairline instance in the STAT table. I want to be sure my suggestion in https://github.com/dy/wavefont/pull/60 was not overlooked, are you sure you want to keep the minimal range at 20? It's okay if you don't want, but I'd to make sure before merging.

**Comment by dy** [comment]
with default at 100 it's safe to extend to hairline indeed. The main limitation is compatibility with linefont, but maybe I should introduce default at 100 there too. I guess @vv-monsalve is right, I'll try hairline

**Comment by RosaWagner** [comment]
yes the default at 100 is also expected for Linefont

**Comment by vv-monsalve** [comment]
Excellent @dy, thank you!

**Comment by dy** [comment]
Ok, just experimented with weight=1 value, and there's multiple limitations making it not feasible.
* First, userspace wgth maps to designspace coords as 1:0.25, but .designspace doesn't support fractional values for axis mapping, gftools fails on
```
        <axis default="100" minimum="1" maximum="1000" name="Weight" tag="wght">
            <map input="1" output="0.25"/>
            <map input="100" output="25"/>
            <map input="1000" output="250"/>
        </axis>
``` 
* It's possible to avoid external mapping and just rescale font internally, but it creates inconsistency between x and y scale, which makes calculation a bit more complicated
* Somehow hairline style (wght=1) is not visible at any font-size, seemingly it's too thin for rendering engine
<img width="618" alt="image" src="https://github.com/google/fonts/assets/300067/b343aa6c-3bf0-4f07-b8f4-62699476025d">
<img width="746" alt="image" src="https://github.com/google/fonts/assets/300067/ad5808bf-98f2-43c0-8ba5-e2d77a7f3101">
That reduces the value of hairline style, I wonder if it's as meaningful here.

The premise about the wavefont/linefont is that they're not intended for rendering precise data, since they have only 127 values. Besides, rendering too much data with wght=1 is not performant. Min value of wght=20 is more-or-less meaningful limitation in terms of healthy font usage, since values lower than that either slow down performance or display errors. It seems likely safer to keep that limit of wght=20.

**Comment by RosaWagner** [comment]
We were proposing to map this way:
`<map input="20" output="1"/>`, is that problematic?

**Comment by dy** [comment]
This creates non-linearity, since mapping is a factor of 4. The furthest I can safely get is `<map input="4" output="1">`, but that doesn't reach hairline-style instance. Should I proceed with that?

**Comment by RosaWagner** [comment]
I reversed the value above so I edited my comment. 

Honestly we are not picky on what a hairline style should look like. We just suggest a way to have the minimum range in the STAT table for future update of the API that could generate an instance for it in the future. If your user value (input) 1, you choose whatever design value (output) you think would fit.

**Comment by dy** [comment]
Ah, ok. So should I add hairline instance in designspace then?

**Comment by RosaWagner** [comment]
Only in the STAT table, so in the config.yaml

**Comment by dy** [comment]
Ok, added
