### ISSUE TITLE
Single Day

### ISSUE THREAD

**Issue by allabakashs** [google/fonts#6747]
**Describe the bug**
I'm using Single Day font in my application. I have issues with the "Indian Rupee" symbol (₹). It is displaying properly in "Windows" OS. Recently, I've migrated to "macOS". The "Indian Rupee" symbol is not displaying in the Mac.

**To Reproduce**
1. Open the font URL "https://fonts.google.com/specimen/Single+Day?query=single+day" in Chrome browser. This will give a test page.
2. Type ₹ (Indian Rupee symbol).
3. Only a black text appears.

**Expected behavior**
It should display the "India Rupee" symbol (in the same way that it is displaying the "Indian Rupee" symbol in "Windows" OS

**Screenshots**

**Additional context**
can be tested in both macOS (it has issues) and Windows (working fine in Windows)

**Comment by RosaWagner** [comment]
Hi @allabakashs, thanks for your report. As noted in the description of the font, Single Day is a Korean font, therefore it supports only few latin letters to be able to display english. So the Rupee sign has not been designed because it is not necessary to the Korean language. The one that you see on Windows is most probably from another font (the browser's default maybe) thanks to a fallback system in case of a missing glyph.  

I would recommend to use another font that supports the rupee sign. For that you can filter your search for "handwriting" fonts, with the rupee sign as custom text: https://fonts.google.com/?preview.text=hello%20₹&preview.text_type=custom&classification=Handwriting. The fonts displaying a square instead of a rupee sign are not supporting it unfortunately.

**Comment by allabakashs** [comment]
Thank you @RosaWagner for your response. I used this font for my youtube videos (which are produced using a whiteboard animation software). At the moment the font is so ingrained into the videos that it become an iconic font for these videos. As it is working fine for Windows (I don't think that it is a fallback to another font), I strongly feel that it is feasible to make this font compatible in macOS too. Request you to analyze it again and act accordingly. As always, I highly appreciate the font team for such a fantastic effort and creativity that is put into it. Thank you very much.

**Comment by RosaWagner** [comment]
I opened the font file already, and there is no Rupee sign inside it. The only way to make it "macOS compatible" would be to design the missing glyphs, re-export the font and re-onboard it. If you don't want to change the font completely, you can use another font to display the rupee sign only.

**Comment by allabakashs** [comment]
That shows some light at the end of the tunnel. Am I allowed to do it? If so, can you please let me know the process/procedure.

**Comment by RosaWagner** [comment]
To be sure that the font you use to display the Rupee sign is available on Mac you would have to choose one that is supported broadly such as Arial. It should be available in the font option of the software you are using. When you select this character within your text frame, there must be the option to select another font to display it. If you have more questions about the font support of your editing software, I would suggest to ask their user support directly.
