### ISSUE TITLE
[tools/encodings] Unit tests to keep Glyph Sets in sync

### ISSUE THREAD

**Issue by davelab6** [google/fonts#678]
Following #675 I realise that it would be good to have some kind of unit test that ensures the children are in sync with the parents

**Comment by graphicore** [comment]
Ok, I'm getting here results from the tests that I made.

One test is checking if a filter-list is a subset of it's Namelist. It will also complain when there are not Unicode encoded glyph names in the filter lists but not in the Namelist. Which we should fix by adding the unencoded glyphs to the Namelists.

The other test is comparing "uni names" and "nice names" filter lists to match their counterparts. some of these need fixes as well, e.g. `encodings/GF Glyph Sets/Greek/filter lists/{uni names|nice names}/archaic.txt` contain the same glyphs, but `nice names` has 75 uni{12345} names in, so that the test fails (I'm comparing by making uni names into nice names). Fixing this should be easy and then there are some smaller issues, but it seems like there's nothing tragic going on :-)

@davelab6 I wonder how you want the tests deployed?

Also, should we have a test that checks if a Namelist let's say `GF-latin-plus_unique-glyphs.nam` and the filter-list with the exact matching name i.e. `filter lists/plus_unique-glyphs.txt`contain the same set of glyphs? I mean, there are obvious subsets, like `filter lists/plus_unique-glyphs_vietnamese-unique.txt`I wouldn't expect that to be the same set as  `GF-latin-plus_unique-glyphs.nam` but  `filter lists/plus_unique-glyphs.txt` should be an exact match.

And one more thing, we could probably generate some of the filter-lists automatically and so reduce sources of error. I think the mapping via GlyphData.xml that I'm doing is good enough. So once the above issues with the data are solved we could generate nice-names and uni-names  filter-lists for all Namelist files (making the first type of test always pass for these files).

**Comment by davelab6** [comment]
> @davelab6 I wonder how you want the tests deployed?

I have given you admin access to the repo, please deploy with travis :)

**Comment by davelab6** [comment]
All your suggestions sound good

**Comment by graphicore** [comment]
> I have given you admin access to the repo, please deploy with travis :)

Allright, thanks!

So far it's running on Travis and the Python2.7 job is failing as expected by me. You can see what kind of problems the tests right now detect, the stuff I described above with a rather verbose output. Starts here: https://travis-ci.org/google/fonts/jobs/208420631#L322

I also added a Python 3.6 job, but that's failing because of a bytes/str incompatibility in a generated file https://github.com/google/fonts/blob/master/tools/fonts_public_pb2.py so that'll need to be updated I guess or we skip testing on Python 3 for now.

**Comment by graphicore** [comment]
Getting closer, the tests with 2.7 are now passing. I changed some of the .nam files and some of the filterlists for this.

However, python 3 is not passing, due to google/google-apputils#9

The test that doesn't pass is more like a nice to have test, nothing critical. It checks that the old parsing of Namelists and the new parsing produces the same char sets. So either we can get google/google-apputils#9 fixed or  skip the test for python 3 or skip it at all.

**Comment by graphicore** [comment]
python 3, using the google-apputils version directly from https://github.com/joachimmetz/google-apputils/tree/python3
There's also a PR at https://github.com/google/google-apputils/pull/15 and then we need to get apputils pushed to PyPI. until then, I think the direct git download is just fine.

**Comment by graphicore** [comment]
closing, #685 did this
