### ISSUE TITLE
Add Noto Serif New Tai Lue

### ISSUE THREAD

**Issue by AshtonTameirao25** [google/fonts#6916]
**Font Project Git Repo URL:**

**Super short description of the Font Family:**

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [ ] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [ ] I am the author of the font, or the author agreed to this submission
- [ ] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**
![2023-10-26 (1)](https://github.com/google/fonts/assets/146303618/2ff72044-eae8-4548-b25b-b11a288ebd18)

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by kenmcd** [comment]
OMG.
Please stop with these ridiculous posts!

Note: I am just another user subscribed to this repo issue tracker.
I have no connection to Google Fonts (GF).
But I have had it with your nonsense.
And am not as polite are they are.

Your lazy empty posts are nothing but useless annoyances.
The GF folks have too much to do already without having to deal with your nonsense all the time.
They have tried to politely request you stop this.
And you have rudely ignored these replies and continue to post useless garbage posts which are nothing but time-wasting distractions.

They are well aware of all Unicode updates and do not need your continuing clueless posts.
The Add Font template is for users who have actually made a font to request adding that font to GF - and all check boxes should be checked, and be true.
You should not be using this unless you have fonts to contribute, and you can honestly check all the boxes.
Otherwise...
JUST STOP NOW!

Any future abuse of this process will result in you being reported to GitHub (and they hopefully ban you).
