### ISSUE TITLE
Lipi Pragatuchhi

### ISSUE THREAD

**Issue by abhimm5** [google/fonts#6933]
**Font Project Git Repo URL:https://github.com/abhimm5/Lipipra-font.git**

**Super short description of the Font Family:Open source beautiful Odia font. It is based on OTFv2 (ory2) with many unique features.**

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:
![Momentum-Textile-Wallcovering-Original-Art-1-810x503](https://github.com/google/fonts/assets/24632205/9368406c-5b43-4423-924c-d5c366a2275f)
**

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by abhimm5** [comment]
I have updated the font.

**Comment by RosaWagner** [comment]
@abhimm5 thanks for the update. I looked at the files and unfortunately the typeface doesn't match Google Fonts technical quality standards and therefore we won't be able to onboard it. 

These are few recommendations to pursue your project:

- For fonts which primary script is not Greek, Latin, Cyrillic, we have the minimal latin requirement of the GF_Latin_Kernel glyphset which you can find here: https://github.com/googlefonts/glyphsets/blob/main/GF_glyphsets/Latin/txt/nice-names/GF_Latin_Kernel.txt. You can most probably find a Latin match in the existing Google Fonts catalog (you don't need to draw it entirely yourself), you will maybe have to scale it to have matching weight and proportion between the Odia script and the Latin.
 
- You can improve the outline quality by reading this chapter of the GF Guide: https://googlefonts.github.io/gf-guide/outlines.html. Since your are working with GlyphsApp, I would also recommend these tuto: https://glyphsapp.com/learn/drawing-good-paths, https://glyphsapp.com/learn/harmonization. You will also need to make optical adjustments and smoother curves.

Google Fonts definitely needs more Odia fonts so I hope you will continue this project. Please feel free to re-open a submission when you think you have improved the 2 points above :)

**Comment by abhimm5** [comment]
@RosaWagner thank you so much.

**Comment by abhimm5** [comment]
@RosaWagner hello i have resolved the 2 above issues. I re-opened the corner, updated with latin glyphs and improved the overall curves. It may have little, small issues, but I am committing to resolved in future. Hope, basic technical standard or requirements have been cleared this time.
