### ISSUE TITLE
Wendy One is missing Euro sign

### ISSUE THREAD

**Issue by d-mal** [google/fonts#6958]
**Describe the bug**
There's no € glyph in the font Wendy One as you can see in the screenshot.

![image](https://github.com/google/fonts/assets/24476952/253bf4b9-2abf-4e76-8647-b4d1886258bf)

**Comment by RosaWagner** [comment]
Hi @d-mal, thanks for your report. Indeed this family doesn't support some basic characters such as the euro sign. This is a pity. Unfortunately this is quite common with the oldest fonts from the catalog since the quality assurance was not the same as today. Since we don't have access to the sources anymore, it is very unlikely that this family will be updated with more glyphs anytime soon. I would recommend to use a euro sign from another font or to choose a similar font with better character support.

You could use Paytone One https://fonts.google.com/specimen/Paytone+One for example, it has a close design and a euro sign that would fit perfectly with Wendy One.
