### ISSUE TITLE
static subdirectories missing

### ISSUE THREAD

**Issue by janedenone** [google/fonts#6959]
For several fonts, the `static` subdirectory, which is present when downloading individual font families via the Google Fonts website and which contains the actual font files, seems to be missing (e.g. for Noto Sans Display or Open Sans). Why is that?

**Comment by kenmcd** [comment]
Both of those font family downloads have a static directory for me.
Noto Sans Display - 72 fonts
Open Sans - 36 fonts

**Comment by janedenone** [comment]
I just made a screenshot of fonts > ofl > notosansdisplay to illustrate the issue:

<img width="1483" alt="Screenshot 2023-11-15 at 07 52 42" src="https://github.com/google/fonts/assets/81964406/d7e5581f-025b-410a-ad52-86a432ddecea">

As you can see, there is no `static` subdir.

**Comment by RosaWagner** [comment]
Hi @janedenone, thanks for your report. Here you are showing the github repository and not Google Fonts website. The families that are variable fonts don't have a static subdirectories in the github repo because the API generates them when clicking the download button on fonts.google.com. If you do download the font from the actual website, you will have a static subdirectory.

<img width="1735" alt="Screenshot 2023-11-15 at 13 12 38" src="https://github.com/google/fonts/assets/12222436/d8086bb5-81d9-46c3-bce7-6da351a41d20">
<img width="490" alt="Screenshot 2023-11-15 at 13 13 12" src="https://github.com/google/fonts/assets/12222436/6de2a102-9921-46dc-820e-d3eafd0aba8c">

**Comment by janedenone** [comment]
I downloaded some families from the Google Fonts website initially, and discovered later that the static font versions were not present in the GitHub repository. Thank you for mentioning the API feature, this cleared things up! In the meantime, I found a [tool](https://fonttools.readthedocs.io/en/latest/index.html) to create static fonts from variable fonts locally (so I can work with the GitHub files without using the Google Fonts website). Thanks again!
