### ISSUE TITLE
Share Tech Mono render problem

### ISSUE THREAD

**Issue by jan-r0374778** [google/fonts#71]
Hello,

There is a bug in redering text written as "Share Tech Mono". the combination fi results in a dot instead of the expected letters fi.

**Comment by adrientetar** [comment]
cc @carrois

Also noticed about this font, thorn has overlap in both the Mono and non-Mono versions.

**Comment by davelab6** [comment]
Which one, Þ or þ ? I couldn't reproduce in Chrome/Firefox on mac, using either the version in the API or the version I just checked in

**Comment by adrientetar** [comment]
þ

**Comment by adrientetar** [comment]
It’s fixed in the file you just checked-in but not in the proportional variant of the font.

**Comment by m4rc1e** [comment]
Hey folks,

I've left the mono untouched but have amended the proportional font.

![screen shot 2016-08-31 at 15 18 09](https://cloud.githubusercontent.com/assets/7525512/18130226/720b790a-6f8e-11e6-83bd-cb512efde39d.png)

Since there wasn't an existing repo I could find. I created [one](https://github.com/m4rc1e/ShareTech)

Cheers,
Marc
