### ISSUE TITLE
arabic: Add Kurdish language support

### ISSUE THREAD

**Issue by riccardoerra** [google/fonts#734]
I'm using Scheherazade font on client's website using https://fonts.google.com. The client noticed that some characters were wrong. After few hours spent debugging the issue I realised that the web version of the font renders in different ways from the downloaded version. At the beginning I thought that was a problem with .woff2, but thanks to https://github.com/majodev/google-webfonts-helper I tried with all the other versions, included .ttf, and the issue remained. But then when I tried with the downloaded versions from https://github.com/google/fonts/tree/7a4070f65f2ca85ffdf2d465ff5e095005bae197/ofl/scheherazade everything is fine. This happens also with Lalezar font for example. I wonder if it's a more generic issue regarding how Google serves the web versions of the fonts.

I created a CodePen to show the issue: https://codepen.io/riccardoerra/pen/aWvGNx
Left web font = wrong, right downloaded font = correct

**Comment by thlinard** [comment]
When you substitute https://fonts.googleapis.com/css?family=Scheherazade:400,700&amp;subset=arabic (the url given by GF) by https://fonts.gstatic.com/l/font?kit=AuKlqGWzUC-8XqMOmsqXiwxQ-1203nFW-7D6Jv7RhieBfnpr3YzEM7mN_1ZaLKSfzLuvPFpw7sRXHGzdTkvmZyUNW3BaINaGJKm1h1egTGuvb9Nz9-X5H-XHadBbfPWAU351u4zXxG3Zon7kYtJ4HdGHtesWt3uAGKfY6OieEIN5TWlAkHkMmKZXR3UVIxOdA1ym5g8o113cwmw33_f2Eu2HYLFVZbmocBW0N97rmZuBrh7BOHNJaZ_r1RgQ2PEgki7rymzorwo6Eec_RlgdX3lKVqQ18Irt3YiY4OAmB2579s2G3MSO_-tke3UY0zU5&skey=7780c105dffad02f&v=v12 (the url used by GF for the live preview on https://fonts.google.com/specimen/Scheherazade), the result is good.
So the version served by GF is the same on Github. The bug lies probably in the subset code.

**Comment by riccardoerra** [comment]
So probably the URL given by Google Fonts doesn't contain all the characters as it should?

**Comment by davelab6** [comment]
@riccardoerra hmm, not sure what is going on with this. I wonder if @Gue3bara could help explain

**Comment by riccardoerra** [comment]
@davelab6 Let's hope, for now I'm just using the .ttf file. Not ideal because it's a such an heavy file!

**Comment by Gue3bara** [comment]
It works fine on GF preview, i don't see the problem with the version on GF seems totally fine 
will look more into it and update you @riccardoerra @davelab6

**Comment by riccardoerra** [comment]
@Gue3bara I just checked again the CodePen I created to show the issue, https://codepen.io/riccardoerra/pen/aWvGNx , and everything seems fine now. Probably Google pushed an update?

**Comment by davelab6** [comment]
You probably installed it locally

**Comment by thlinard** [comment]
Yes, probably. Still wrong here.

**Comment by riccardoerra** [comment]
@davelab6 & @thlinard, you are right. Issue still present.

**Comment by khaledhosny** [comment]
This is a subsetting issue, `ڵ` is not part of the standard Arabic subset served by default. One way to fix this is to include all the characters you need in the font request.

**Comment by davelab6** [comment]
Should it be standard?

**Comment by khaledhosny** [comment]
It is used in Kurdish, but if you want to support Kurdish a few more characters will be needed.

**Comment by riccardoerra** [comment]
@khaledhosny So the only way to serve a "complete" webfont version is to include all the characters you need in the font request?

**Comment by khaledhosny** [comment]
AFAIK that is the only supported way. There is an undocumented subset name (full, all?) that serves the original font unmodified, but @davelab6 will say it is unsupported and should not be used.

**Comment by davelab6** [comment]
Renaming and refiling this as "Update arabic nam file / subsets with Kurdish language support"

**Comment by khaledhosny** [comment]
What about an Arabic Extended encoding for the extra languages than currently supported? Kurdish might not be the only language people need.

**Comment by davelab6** [comment]
I think we are moving away from -ext subsets, but how many more glyphs
could be added for language support?

**Comment by khaledhosny** [comment]
4 new characters, 10 glyphs in average font:
```
0x0692 # ARABIC LETTER REH WITH SMALL V, ڒ
0x06B5 # ARABIC LETTER LAM WITH SMALL V, ڵ
0x06C6 # ARABIC LETTER OE, ۆ
0x06CE # ARABIC LETTER YEH WITH SMALL V, ێ
```

**Comment by davelab6** [comment]
Just for Kurdish, I assume. What other languages could be considered?

On Sep 26, 2017 8:46 AM, "Khaled Hosny" <notifications@github.com> wrote:

4 new characters, 10 glyphs in average font:

0x0692 # ARABIC LETTER REH WITH SMALL V, ڒ
0x06B5 # ARABIC LETTER LAM WITH SMALL V, ڵ
0x06C6 # ARABIC LETTER OE, ۆ
0x06CE # ARABIC LETTER YEH WITH SMALL V, ێ

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/google/fonts/issues/734#issuecomment-332186511>, or mute
the thread

**Comment by khaledhosny** [comment]
On top of my head, Pashto, Sindhi and Uighur. Alternatively, any language that has a Wikipedia written in Arabic script.

**Comment by khaledhosny** [comment]
List of Wikipedias for reference: https://meta.wikimedia.org/wiki/List_of_Wikipedias

**Comment by simoncozens** [comment]
https://github.com/googlefonts/glyphsets/pull/92 added all characters in the Arabic Unicode block to the arabic subset.
