### ISSUE TITLE
Mismatch between Noto Sans and Noto Serif HK

### ISSUE THREAD

**Issue by tomasdev** [google/fonts#7616]
This character is missing from this font, Noto Sans Hong Kong. "鄕" While it is available in Noto Serif Hong Kong

Also the instructions when filing this bug requests to file Noto bugs at https://notofonts.github.io/reporter.html but there's not HK or Hong Kong in the font dropdown.

**Additional context**
b/337852202

**Comment by chrissimpkins** [comment]
@simoncozens do you want this on the Noto CJK tracker?

**Comment by simoncozens** [comment]
Ideally, yes; this is one for Adobe.

**Comment by verdy-p** [comment]
Is there a roadmap to complete existing Noto CJK fonts (for SC/TC/HK/JP/KR), at least in plane 0 (BMP)?
This could be done even if other fonts will be needed for planes 2 and 3 (due to OpenType limitations).

----

Note that UniHan will soon be updated with Unicode 16.0, with more precise radical/stroke indexes and a new development for additional properties (notably the first residual stroke, described, but that will not be implemented in Unicode 16.0 and CLDR data).

As well, there are active developments to fully describe the strokes and radicals of CJK ideographs... and may be it will then possible to develop CJK fonts from a database of their radical/stroke components... this could be the base of a new OpenType extension where CJK fonts would be much smaller, could support all CJK characters in all planes, including all variants encoded in the Unicode IVS database, by defining glyphs only for stroke components (if such OpenType addition gets supported in future text renderers), without being limited by the existing maximum number of glyphs mapped per font.

**Comment by chrissimpkins** [comment]
I reposted this issue on the Noto CJK repository tracker @ https://github.com/notofonts/noto-cjk/issues/279

@verdy-p Will you please post your question in https://github.com/google/fonts/issues/7616#issuecomment-2147500358 on this tracker: https://github.com/notofonts/noto-cjk/issues?  We try to use this repository for onboarding management, not for individual project development issues.  Let's move that discussion to the upstream development repository. Thanks
