### ISSUE TITLE
Add Sen (Regular, Bold, ExtraBold)

### ISSUE THREAD

**Issue by philatype** [google/fonts#79]
https://github.com/philatype/Sen

**Comment by philatype** [comment]
Is there anything I'm supposed to do in addition to post the repo link as an issue here?

**Comment by davelab6** [comment]
@philatype that looks great! I'll file issues on that repo's tracked as I find them and onboard this soon :)

**Comment by philatype** [comment]
Can't wait! :)

**Comment by philatype** [comment]
Hello Dave, what's the status of this?

**Comment by davelab6** [comment]
Its in my queue, I hope to get to it before the end of the year :)

**Comment by philatype** [comment]
The end of the year passed. Any idea when this will be up?

**Comment by philatype** [comment]
bump

**Comment by philatype** [comment]
Hooray, activity!

**Comment by philatype** [comment]
What does this label mean? Is there action required on my part?

**Comment by philatype** [comment]
@davelab6  can you respond?

**Comment by davelab6** [comment]
@philatype No, no action on your part yet. I now have @m4rc1e working with me to processes these requests so I hope to see action on our part to check your files soon :) Thanks for your patience

**Comment by philatype** [comment]
Soo... it's been about 5 years since my initial contribution request. 
@davelab6 @m4rc1e I noticed there were contribution guidelines that popped up recently — Is it some criteria that my submission didn't meet?  I'm wondering if there's anything I can do, again, to expedite this.

Also, I'm confused about the process as there have been plenty of new fonts designed _after_ I've even submitted, and they were subsequently submitted, approved, and added to the library in record time. I'd like to contribute other work to the library, but if it means waiting this long, what's the point?

**Comment by m4rc1e** [comment]
@philatype I apologise for not seeing this.

For the past two years, we've been improving our tools to check and dispatch families. The whole process is now pretty much automated. Many families have fallen through the cracks, unfortunately this is one of them. We aim to revisit them this year.

If I run the family though [fontbakery](https://www.github.com/googlefonts/fontbakery), we get the following report.

## Fontbakery report

Fontbakery version: 0.6.12.dev19+g6638c122.d20190308

<details>
<summary><b>[2] Family checks</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Check font has a license.</summary>

* [com.google.fonts/check/family/has_license](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/family/has_license)
* 🔥 **FAIL** No license file was found. Please add an OFL.txt or a LICENSE.txt file. If you are running fontbakery on a Google Fonts upstream repo, which is fine, just make sure there is a temporary license file in the same folder. [code: no-license]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Check that OS/2.fsSelection bold & italic settings are unique for each NameID1</summary>

* [com.adobe.fonts/check/family/bold_italic_unique_for_nameid1](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/os2.html#com.adobe.fonts/check/family/bold_italic_unique_for_nameid1)
* 🔥 **FAIL** Family 'Sen' has 2 fonts (should be no more than 1) with the same OS/2.fsSelection bold & italic settings: Bold=False, Italic=False

</details>
<br>
</details>
<details>
<summary><b>[10] Sen-Bold.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Checking OS/2 fsType.</summary>

* [com.google.fonts/check/fstype](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/fstype)
* 🔥 **FAIL** OS/2 fsType is a legacy DRM-related field.
In this font it is set to 8 meaning that:
The font may be embedded but must only be installed temporarily on other systems.
No such DRM restrictions can be enabled on the Google Fonts collection, so the fsType field must be set to zero (Installable Embedding) instead.
Fonts with this setting indicate that they may be embedded and permanently installed on the remote system by an application.

 More detailed info is available at:
 https://docs.microsoft.com/en-us/typography/opentype/spec/os2#fstype

</details>
<details>
<summary>🔥 <b>FAIL:</b> Check glyph coverage.</summary>

* [com.google.fonts/check/glyph_coverage](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyph_coverage)
* 🔥 **FAIL** Missing required codepoints: 0x000D (CARRIAGE RETURN), 0x00A0 (NO-BREAK SPACE), 0x00AA (FEMININE ORDINAL INDICATOR), 0x00AB (LEFT-POINTING DOUBLE ANGLE QUOTATION MARK), 0x00AC (NOT SIGN), 0x00AD (SOFT HYPHEN), 0x00B2 (SUPERSCRIPT TWO), 0x00B3 (SUPERSCRIPT THREE), 0x00B5 (MICRO SIGN), 0x00B9 (SUPERSCRIPT ONE) and 11 more.

</details>
<details>
<summary>🔥 <b>FAIL:</b> Substitute copyright, registered and trademark symbols in name table entries.</summary>

* [com.google.fonts/check/name/unwanted_chars](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/unwanted_chars)
* 🔥 **FAIL** NAMEID #0 contains symbol that should be replaced by '(c)'.
* 🔥 **FAIL** NAMEID #0 contains symbol that should be replaced by '(c)'.

</details>
<details>
<summary>🔥 <b>FAIL:</b> "License URL matches License text on name table?</summary>

* [com.google.fonts/check/name/license_url](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/license_url)
* 🔥 **FAIL** A known license URL must be provided in the NameID 14 (LICENSE INFO URL) entry. Currently accepted licenses are Apache or Open Font License. For a small set of legacy families the Ubuntu Font License may be acceptable as well. [code: no-license-found]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Are there non-ASCII characters in ASCII-only NAME table entries?</summary>

* [com.google.fonts/check/name/ascii_only_entries](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/ascii_only_entries)
* 🔥 **FAIL** There are 2 strings containing non-ASCII characters in the ASCII-only NAME table entries.

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in fonts</summary>

* [com.google.fonts/check/font_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/font_copyright)
* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright © 2015 by Kosal Sen, Philatype. All rights reserved.'
* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright © 2015 by Kosal Sen, Philatype. All rights reserved.'

</details>
<details>
<summary>🔥 <b>FAIL:</b> PPEM must be an integer on hinted fonts.</summary>

* [com.google.fonts/check/integer_ppem_if_hinted](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/integer_ppem_if_hinted)
* 🔥 **FAIL** This is a hinted font, so it must have bit 3 set on the flags of the head table, so that PPEM values will be rounded into and integer value.

</details>
<details>
<summary>🔥 <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent.</summary>

* [com.google.fonts/check/family/win_ascent_and_descent](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/family/win_ascent_and_descent)
* 🔥 **FAIL** OS/2.usWinDescent value should be equal or greater than 255, but got 240 instead [code: descent]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Checking OS/2 Metrics match hhea Metrics.</summary>

* [com.google.fonts/check/os2_metrics_match_hhea](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/os2_metrics_match_hhea)
* 🔥 **FAIL** OS/2 sTypoAscender and hhea ascent must be equal. [code: ascender]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Font contains glyphs for whitespace characters?</summary>

* [com.google.fonts/check/whitespace_glyphs](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/whitespace_glyphs)
* 🔥 **FAIL** Whitespace glyphs missing for the following codepoints: 0x00A0.

</details>
<br>
</details>
<details>
<summary><b>[10] Sen-ExtraBold.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Checking OS/2 fsType.</summary>

* [com.google.fonts/check/fstype](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/fstype)
* 🔥 **FAIL** OS/2 fsType is a legacy DRM-related field.
In this font it is set to 8 meaning that:
The font may be embedded but must only be installed temporarily on other systems.
No such DRM restrictions can be enabled on the Google Fonts collection, so the fsType field must be set to zero (Installable Embedding) instead.
Fonts with this setting indicate that they may be embedded and permanently installed on the remote system by an application.

 More detailed info is available at:
 https://docs.microsoft.com/en-us/typography/opentype/spec/os2#fstype

</details>
<details>
<summary>🔥 <b>FAIL:</b> Check glyph coverage.</summary>

* [com.google.fonts/check/glyph_coverage](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyph_coverage)
* 🔥 **FAIL** Missing required codepoints: 0x000D (CARRIAGE RETURN), 0x00A0 (NO-BREAK SPACE), 0x00AA (FEMININE ORDINAL INDICATOR), 0x00AB (LEFT-POINTING DOUBLE ANGLE QUOTATION MARK), 0x00AC (NOT SIGN), 0x00AD (SOFT HYPHEN), 0x00B2 (SUPERSCRIPT TWO), 0x00B3 (SUPERSCRIPT THREE), 0x00B5 (MICRO SIGN), 0x00B9 (SUPERSCRIPT ONE) and 11 more.

</details>
<details>
<summary>🔥 <b>FAIL:</b> Substitute copyright, registered and trademark symbols in name table entries.</summary>

* [com.google.fonts/check/name/unwanted_chars](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/unwanted_chars)
* 🔥 **FAIL** NAMEID #0 contains symbol that should be replaced by '(c)'.
* 🔥 **FAIL** NAMEID #0 contains symbol that should be replaced by '(c)'.

</details>
<details>
<summary>🔥 <b>FAIL:</b> "License URL matches License text on name table?</summary>

* [com.google.fonts/check/name/license_url](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/license_url)
* 🔥 **FAIL** A known license URL must be provided in the NameID 14 (LICENSE INFO URL) entry. Currently accepted licenses are Apache or Open Font License. For a small set of legacy families the Ubuntu Font License may be acceptable as well. [code: no-license-found]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Are there non-ASCII characters in ASCII-only NAME table entries?</summary>

* [com.google.fonts/check/name/ascii_only_entries](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/ascii_only_entries)
* 🔥 **FAIL** There are 2 strings containing non-ASCII characters in the ASCII-only NAME table entries.

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in fonts</summary>

* [com.google.fonts/check/font_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/font_copyright)
* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright © 2015 by Kosal Sen, Philatype. All rights reserved.'
* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright © 2015 by Kosal Sen, Philatype. All rights reserved.'

</details>
<details>
<summary>🔥 <b>FAIL:</b> PPEM must be an integer on hinted fonts.</summary>

* [com.google.fonts/check/integer_ppem_if_hinted](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/integer_ppem_if_hinted)
* 🔥 **FAIL** This is a hinted font, so it must have bit 3 set on the flags of the head table, so that PPEM values will be rounded into and integer value.

</details>
<details>
<summary>🔥 <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent.</summary>

* [com.google.fonts/check/family/win_ascent_and_descent](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/family/win_ascent_and_descent)
* 🔥 **FAIL** OS/2.usWinDescent value should be equal or greater than 255, but got 240 instead [code: descent]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Checking OS/2 Metrics match hhea Metrics.</summary>

* [com.google.fonts/check/os2_metrics_match_hhea](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/os2_metrics_match_hhea)
* 🔥 **FAIL** OS/2 sTypoAscender and hhea ascent must be equal. [code: ascender]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Font contains glyphs for whitespace characters?</summary>

* [com.google.fonts/check/whitespace_glyphs](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/whitespace_glyphs)
* 🔥 **FAIL** Whitespace glyphs missing for the following codepoints: 0x00A0.

</details>
<br>
</details>
<details>
<summary><b>[10] Sen-Regular.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Checking OS/2 fsType.</summary>

* [com.google.fonts/check/fstype](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/fstype)
* 🔥 **FAIL** OS/2 fsType is a legacy DRM-related field.
In this font it is set to 8 meaning that:
The font may be embedded but must only be installed temporarily on other systems.
No such DRM restrictions can be enabled on the Google Fonts collection, so the fsType field must be set to zero (Installable Embedding) instead.
Fonts with this setting indicate that they may be embedded and permanently installed on the remote system by an application.

 More detailed info is available at:
 https://docs.microsoft.com/en-us/typography/opentype/spec/os2#fstype

</details>
<details>
<summary>🔥 <b>FAIL:</b> Check glyph coverage.</summary>

* [com.google.fonts/check/glyph_coverage](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyph_coverage)
* 🔥 **FAIL** Missing required codepoints: 0x000D (CARRIAGE RETURN), 0x00A0 (NO-BREAK SPACE), 0x00AA (FEMININE ORDINAL INDICATOR), 0x00AB (LEFT-POINTING DOUBLE ANGLE QUOTATION MARK), 0x00AC (NOT SIGN), 0x00AD (SOFT HYPHEN), 0x00B2 (SUPERSCRIPT TWO), 0x00B3 (SUPERSCRIPT THREE), 0x00B5 (MICRO SIGN), 0x00B9 (SUPERSCRIPT ONE) and 11 more.

</details>
<details>
<summary>🔥 <b>FAIL:</b> Substitute copyright, registered and trademark symbols in name table entries.</summary>

* [com.google.fonts/check/name/unwanted_chars](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/unwanted_chars)
* 🔥 **FAIL** NAMEID #0 contains symbol that should be replaced by '(c)'.
* 🔥 **FAIL** NAMEID #0 contains symbol that should be replaced by '(c)'.

</details>
<details>
<summary>🔥 <b>FAIL:</b> "License URL matches License text on name table?</summary>

* [com.google.fonts/check/name/license_url](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/license_url)
* 🔥 **FAIL** A known license URL must be provided in the NameID 14 (LICENSE INFO URL) entry. Currently accepted licenses are Apache or Open Font License. For a small set of legacy families the Ubuntu Font License may be acceptable as well. [code: no-license-found]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Are there non-ASCII characters in ASCII-only NAME table entries?</summary>

* [com.google.fonts/check/name/ascii_only_entries](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/ascii_only_entries)
* 🔥 **FAIL** There are 2 strings containing non-ASCII characters in the ASCII-only NAME table entries.

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in fonts</summary>

* [com.google.fonts/check/font_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/font_copyright)
* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright © 2015 by Kosal Sen, Philatype. All rights reserved.'
* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright © 2015 by Kosal Sen, Philatype. All rights reserved.'

</details>
<details>
<summary>🔥 <b>FAIL:</b> PPEM must be an integer on hinted fonts.</summary>

* [com.google.fonts/check/integer_ppem_if_hinted](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/integer_ppem_if_hinted)
* 🔥 **FAIL** This is a hinted font, so it must have bit 3 set on the flags of the head table, so that PPEM values will be rounded into and integer value.

</details>
<details>
<summary>🔥 <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent.</summary>

* [com.google.fonts/check/family/win_ascent_and_descent](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/family/win_ascent_and_descent)
* 🔥 **FAIL** OS/2.usWinDescent value should be equal or greater than 255, but got 240 instead [code: descent]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Checking OS/2 Metrics match hhea Metrics.</summary>

* [com.google.fonts/check/os2_metrics_match_hhea](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/os2_metrics_match_hhea)
* 🔥 **FAIL** OS/2 sTypoAscender and hhea ascent must be equal. [code: ascender]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Font contains glyphs for whitespace characters?</summary>

* [com.google.fonts/check/whitespace_glyphs](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/whitespace_glyphs)
* 🔥 **FAIL** Whitespace glyphs missing for the following codepoints: 0x00A0.

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 32 | 19 | 175 | 19 | 165 |
| 0% | 8% | 5% | 43% | 5% | 40% |

**Note:** The following loglevels were omitted in this report:
* **WARN**
* **SKIP**
* **INFO**
* **PASS**

We'll be able to release the family once the failing issues have been solved. Please solve as many issues as possible, if you get stuck or an issue is unclear, please [report](https://github.com/googlefonts/fontbakery/issues) it.

**Comment by m4rc1e** [comment]
Family is now on Google Fonts, https://fonts.google.com/specimen/Sen?query=sen

Thanks @yanone

**Comment by yanone** [comment]
Manually linking PR: https://github.com/google/fonts/pull/2310
