### ISSUE TITLE
Cinzel Decorative has kerning issue on Firefox

### ISSUE THREAD

**Issue by iSimonWeb** [google/fonts#83]
There's an issue with the font Cinzel Decorative -> https://www.google.com/fonts/specimen/Cinzel+Decorative

As shown in this stackoverflow (http://stackoverflow.com/questions/23142367/overlap-between-letters-of-google-font-on-iphone-and-firefox) some couple of letters like "OO" and "HE" overlap due to missing kerning information. I tried to get the font from FontSquirrel but it didn't solve the problem.

**Comment by natenine** [comment]
You found a feature, not a bug. It is on purpose and it only happens on the decorative version, because it is, well, decorative :)
![screen shot 2015-07-20 at 20 04 34](https://cloud.githubusercontent.com/assets/5048844/8784563/a2494882-2f1a-11e5-939c-94f68c45e555.png)
Cinzel non-decorative has a 'normal' kerning here

**Comment by natenine** [comment]
At the time (2012 i guess) I used kerning in order to create this "ligatures". 
Just switch to the non-decorative version and you're good.

Hope I helped

**Comment by davelab6** [comment]
Thanks @natenine

**Comment by adrientetar** [comment]
> missing kerning information

Missing kerning would not produce this, as you can see the O spaces normally when followed by N per your second example.

**Comment by iSimonWeb** [comment]
Thanks guys for the explaination.
Anyway I could turn this issue upside-down telling you that this "feature"
is not working in Chrome.

**Comment by natenine** [comment]
Maybe chrome has some way of preventing colisions between glyphs, I don't
know. Either way I think your actual problem is solved if you dont use the
decorative version.
Best

No dia terça-feira, 21 de julho de 2015, Simone <notifications@github.com>
escreveu:

> Thanks guys for the explaination.
> Anyway I could turn this issue upside-down telling you that this "feature"
> is not working in Chrome.
>
> On Mon, Jul 20, 2015 at 10:52 PM Adrien Tétar <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > missing kerning information
> >
> > Missing kerning would not produce this, as you can see the O spaces
> > normally when followed by N per your second example.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/google/fonts/issues/83#issuecomment-123032908>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/fonts/issues/83#issuecomment-123259892>.
>


-- 
Natanael Gama
