### ISSUE TITLE
Add Parkinsans

### ISSUE THREAD

**Issue by redstonedesign** [google/fonts#8300]
**Font Project Git Repo URL:**

https://github.com/redstonedesign/parkinsans

**Description:**

Parkinsans is a geometric sans serif designed for UK charity Parkinson’s UK. Energetic, human, accessible, approachable – Parkinsans embodies Parkinson’s UK’s relentless energy, whilst typographic quirks reflect the unique experience of every Parkinson’s journey. Consisting of 6 weights, Parkinsans is designed to grab attention at display sizes and provide an accessible, easy reading experience for short form copy. Designed by award-winning, London based creative agency Red Stone, Parkinsans is derived from Indian Type Foundry's Poppins.

**Requirements:**

By opening this issue, I confirm the project meets the following requirements:

- [x] The entire font project is available in a Github repository (repo) and licensed under the [OFL](https://openfontlicense.org/open-font-license-official-text/)

- [x] The source files are available in the repo

- [x] I am the sole copyright author of the entire project, or, all other copyright authors have licensed their work to me under the OFL

- [x] There are no "Reserved Font Names" in the OFL license information, or in the project documentation of any known upstream projects. If there are RFNs, they are not used in whole or in part in this family name, or, I want to discuss how Google can work with my use of them.

- [x] The family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)

- [x] The font supports at least the Google Fonts 'Latin Core' glyphset from [github.com/googlefonts/glyphsets](https://github.com/googlefonts/glyphsets) ([direct link](https://github.com/googlefonts/glyphsets/blob/main/data/results/txt/nice-names/GF_Latin_Core.txt))

- [x] The repo has the [Google Fonts preferred upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)

- [x] I have read, agree with, and comply with, the full [Google Fonts contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)

- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

![Image](https://github.com/user-attachments/assets/efa8ba5b-2a02-4165-b3a1-9927509c1c5b)

**Comment by redstonedesign** [comment]
hey @emmamarichal , are you able to advise if we need to do anything else to get this added as a new font?

**Comment by m4rc1e** [comment]
Hey @redstonedesign.

Thank you for the submission. I will raise it in our onboarding meeting this week. I'll post back whether or not we accept the family (looks decent so it's likely).

Please be aware that onboarding the family may take some time and we may require further work in order for it to meet our criteria.

**Comment by davelab6** [comment]
This is wonderful work! Thanks @redstonedesign :)

**Comment by davelab6** [comment]
I've marked this as accepted but I believe it may not happen until mid Q1. hope thats OK for you

**Comment by emmamarichal** [comment]
Hi @redstonedesign!

Thank you for this great submission! I took a quick look so you can be able to add some changes before Q1 :)

- **Glyphset**
There are some missing glyphs, to follow the GF Latin Core glyphset: `/.notdef/periodcentered.loclCAT/periodcentered.loclCAT.case/caroncomb.alt/idotaccent`
Remark: the .notdef needs to contain outlines (a rectangle would be the best solution)

![Image](https://github.com/user-attachments/assets/938ed442-d285-4db1-b271-e5eac640b606)


- **Variable font**
When I will export the fonts, I'll generate a variable, this is the format we prefer. Nothing to do on your side, I just let you know.

- **Interpolation issues**
There is a interpolation issue with the eogonek.
![Image](https://github.com/user-attachments/assets/e84c3042-8605-499f-92f8-db7f6681cdec)

-**Kerning**
There is no kerning at all, it would be great if you could add the main pairs :) Please let me know if you need some kerning proofs!

![Image](https://github.com/user-attachments/assets/ae0bad59-5639-487a-9b9a-2c8ea0697084)


- **Fontbakery report**
I copy paste here the fontbakery report, please try to solve the most of the fail and warns you can, but don't worry if there are still some, I'll solve them during the onboarding process.

## FontBakery report

fontbakery version: 0.13.0a0





## Check results



<details><summary>[22] Parkinsans_AW_Google[wght].ttf</summary>
<div>
<details>
    <summary>🔥 <b>FAIL</b> Checking file is named canonically. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/vendorspecific.googlefonts.html#"></a></summary>
    <div>







* 🔥 **FAIL** <p>Expected &quot;Parkinsans[wght].ttf. Got Parkinsans_AW_Google[wght].ttf.</p>
 [code: bad-filename]



</div>
</details>

<details>
    <summary>⚠️ <b>WARN</b> Does GPOS table have kerning information? This check skips monospaced fonts as defined by post.isFixedPitch value <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/opentype.gpos.html#"></a></summary>
    <div>







* ⚠️ **WARN** <p>GPOS table lacks kerning information.</p>
 [code: lacks-kern-info]



</div>
</details>

<details>
    <summary>⚠️ <b>WARN</b> Check accent of Lcaron, dcaron, lcaron, tcaron <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/some_other_checks.html#"></a></summary>
    <div>









* ⚠️ **WARN** <p>Lcaron is decomposed and therefore could not be checked. Please check manually.</p>
 [code: decomposed-outline]



* ⚠️ **WARN** <p>dcaron is decomposed and therefore could not be checked. Please check manually.</p>
 [code: decomposed-outline]



* ⚠️ **WARN** <p>lcaron is decomposed and therefore could not be checked. Please check manually.</p>
 [code: decomposed-outline]



* ⚠️ **WARN** <p>tcaron is decomposed and therefore could not be checked. Please check manually.</p>
 [code: decomposed-outline]



</div>
</details>

<details>
    <summary>⚠️ <b>WARN</b> Detect any interpolation issues in the font. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/some_other_checks.html#"></a></summary>
    <div>







* ⚠️ **WARN** <p>Interpolation issues were found in the font:</p>
<pre><code>- Contour 1 start point differs in glyph 'eogonek' between location wght=475 and location wght=800

- Contour 1 in glyph 'eogonek': becomes underweight between wght=475 and wght=800.

- Contour 1 point 14 in glyph 'eogonek' has a kink between location wght=475 and location wght=800
</code></pre>
 [code: interpolation-issues]



</div>
</details>

<details>
    <summary>⚠️ <b>WARN</b> Are there caret positions declared for every ligature? <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/ligature_carets.html#"></a></summary>
    <div>







* ⚠️ **WARN** <p>This font lacks caret position values for ligature glyphs on its GDEF table.</p>
 [code: lacks-caret-pos]



</div>
</details>

<details>
    <summary>⚠️ <b>WARN</b> Check math signs have the same width. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/some_other_checks.html#"></a></summary>
    <div>







* ⚠️ **WARN** <p>The most common width is 476 among a set of 2 math glyphs.
The following math glyphs have a different width, though:</p>
<p>Width = 655:
plus</p>
<p>Width = 504:
less</p>
<p>Width = 676:
equal</p>
<p>Width = 492:
greater</p>
<p>Width = 651:
logicalnot</p>
<p>Width = 657:
plusminus</p>
<p>Width = 591:
multiply</p>
<p>Width = 637:
divide</p>
<p>Width = 519:
minus</p>
<p>Width = 487:
approxequal</p>
<p>Width = 664:
notequal</p>
 [code: width-outliers]



</div>
</details>

<details>
    <summary>⚠️ <b>WARN</b> Check font contains no unreachable glyphs <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/glyphset.html#"></a></summary>
    <div>







* ⚠️ **WARN** <p>The following glyphs could not be reached by codepoint or substitution rules:</p>
<pre><code>- indianrupee

- turkishlira
</code></pre>
 [code: unreachable-glyphs]



</div>
</details>

<details>
    <summary>⚠️ <b>WARN</b> Validate size, and resolution of article images, and ensure article page has minimum length and includes visual assets. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/vendorspecific.googlefonts.article.html#"></a></summary>
    <div>







* ⚠️ **WARN** <p>Family metadata at . does not have an article.</p>
 [code: lacks-article]



</div>
</details>

<details>
    <summary>⚠️ <b>WARN</b> Check for codepoints not covered by METADATA subsets. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/vendorspecific.googlefonts.subsets.html#"></a></summary>
    <div>







* ⚠️ **WARN** <p>The following codepoints supported by the font are not covered by
any subsets defined in the font's metadata file, and will never
be served. You can solve this by either manually adding additional
subset declarations to METADATA.pb, or by editing the glyphset
definitions.</p>
<ul>
<li>U+02C7 CARON: try adding one of: yi, canadian-aboriginal, tifinagh</li>
<li>U+02D8 BREVE: try adding one of: yi, canadian-aboriginal</li>
<li>U+02D9 DOT ABOVE: try adding one of: yi, canadian-aboriginal</li>
<li>U+02DB OGONEK: try adding one of: yi, canadian-aboriginal</li>
<li>U+02DD DOUBLE ACUTE ACCENT: not included in any glyphset definition</li>
<li>U+0302 COMBINING CIRCUMFLEX ACCENT: try adding one of: cherokee, tifinagh, coptic, math</li>
<li>U+0306 COMBINING BREVE: try adding one of: tifinagh, old-permic</li>
<li>U+0307 COMBINING DOT ABOVE: try adding one of: tifinagh, malayalam, tai-le, old-permic, canadian-aboriginal, coptic, syriac, math</li>
<li>U+030A COMBINING RING ABOVE: try adding syriac</li>
<li>U+030B COMBINING DOUBLE ACUTE ACCENT: try adding one of: cherokee, osage
25 more.</li>
</ul>
<p>Use -F or --full-lists to disable shortening of long lists.</p>
<p>Or you can add the above codepoints to one of the subsets supported by the font: <code>latin</code>, <code>latin-ext</code></p>
 [code: unreachable-subsetting]



</div>
</details>

<details>
    <summary>⚠️ <b>WARN</b> Ensure dotted circle glyph is present and can attach marks. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/shaping.html#"></a></summary>
    <div>







* ⚠️ **WARN** <p>No dotted circle glyph present</p>
 [code: missing-dotted-circle]



</div>
</details>

<details>
    <summary>⚠️ <b>WARN</b> Ensure soft_dotted characters lose their dot when combined with marks that replace the dot. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/shaping.html#"></a></summary>
    <div>







* ⚠️ **WARN** <p>The dot of soft dotted characters used in orthographies <em>must</em> disappear in the following strings: i̊ i̋ j̀ j́ j̃ j̄ j̈ į̀ į́ į̂ į̃ į̄ į̌</p>
<p>The dot of soft dotted characters <em>should</em> disappear in other cases, for example: i̇ ǐ i̦̇ i̦̊ i̦̋ ǐ̦ i̧̇ i̧̊ i̧̋ ǐ̧ ĵ j̆ j̇ j̊ j̋ ǰ j̦̀ j̦́ ĵ̦ j̦̃</p>
<p>Your font fully covers the following languages that require the soft-dotted feature: Lithuanian (Latn, 2,357,094 speakers), Dutch (Latn, 31,709,104 speakers).</p>
<p>Your font does <em>not</em> cover the following languages that require the soft-dotted feature: Ekpeye (Latn, 226,000 speakers), Mundani (Latn, 34,000 speakers), Mfumte (Latn, 79,000 speakers), Zapotec (Latn, 490,000 speakers), Gulay (Latn, 250,478 speakers), Dii (Latn, 71,000 speakers), Koonzime (Latn, 40,000 speakers), Vute (Latn, 21,000 speakers), Ma’di (Latn, 584,000 speakers), Dan (Latn, 1,099,244 speakers), Navajo (Latn, 166,319 speakers), Bete-Bendi (Latn, 100,000 speakers), Southern Kisi (Latn, 360,000 speakers), Ijo, Southeast (Latn, 2,471,000 speakers), Nateni (Latn, 100,000 speakers), Yala (Latn, 200,000 speakers), Belarusian (Cyrl, 10,064,517 speakers), Basaa (Latn, 332,940 speakers), Mango (Latn, 77,000 speakers), Nzakara (Latn, 50,000 speakers), South Central Banda (Latn, 244,000 speakers), Bafut (Latn, 158,146 speakers), Igbo (Latn, 27,823,640 speakers), Fur (Latn, 1,230,163 speakers), Ngbaka (Latn, 1,020,000 speakers), Cicipu (Latn, 44,000 speakers), Makaa (Latn, 221,000 speakers), Lugbara (Latn, 2,200,000 speakers), Aghem (Latn, 38,843 speakers), Kpelle, Guinea (Latn, 622,000 speakers), Ebira (Latn, 2,200,000 speakers), Ukrainian (Cyrl, 29,273,587 speakers), Kom (Latn, 360,685 speakers), Avokaya (Latn, 100,000 speakers), Sar (Latn, 500,000 speakers), Ejagham (Latn, 120,000 speakers).</p>
 [code: soft-dotted]



</div>
</details>

<details>
    <summary>⚠️ <b>WARN</b> Are there any misaligned on-curve points? <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/outline.html#"></a></summary>
    <div>







* ⚠️ **WARN** <p>The following glyphs have on-curve points which have potentially incorrect y coordinates:</p>
<pre><code>* Iogonek (U+012E): X=202.0,Y=1.0 (should be at baseline 0?)

* Lcaron (U+013D): X=273.5,Y=689.0 (should be at cap-height 690?)

* W (U+0057): X=220.0,Y=-1.0 (should be at baseline 0?)

* Wacute (U+1E82): X=220.0,Y=-1.0 (should be at baseline 0?)

* Wcircumflex (U+0174): X=220.0,Y=-1.0 (should be at baseline 0?)

* Wdieresis (U+1E84): X=220.0,Y=-1.0 (should be at baseline 0?)

* Wgrave (U+1E80): X=220.0,Y=-1.0 (should be at baseline 0?)

* acircumflex (U+00E2): X=338.0,Y=688.0 (should be at cap-height 690?)

* cdotaccent (U+010B): X=275.5,Y=691.5 (should be at cap-height 690?)

* cdotaccent (U+010B): X=340.5,Y=691.5 (should be at cap-height 690?)

* 30 more.
</code></pre>
<p>Use -F or --full-lists to disable shortening of long lists.</p>
 [code: found-misalignments]



</div>
</details>

<details>
    <summary>⚠️ <b>WARN</b> Check the direction of the outermost contour in each glyph <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/outline.html#"></a></summary>
    <div>







* ⚠️ **WARN** <p>The following glyphs have a counter-clockwise outer contour:</p>
<pre><code>* turkishlira has a counter-clockwise outer contour

* turkishlira has a counter-clockwise outer contour

* turkishlira has a counter-clockwise outer contour
</code></pre>
 [code: ccw-outer-contour]



</div>
</details>

<details>
    <summary>⚠️ <b>WARN</b> Ensure fonts have ScriptLangTags declared on the 'meta' table. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/vendorspecific.googlefonts.meta.html#"></a></summary>
    <div>







* ⚠️ **WARN** <p>This font file does not have a 'meta' table.</p>
 [code: lacks-meta-table]



</div>
</details>

<details>
    <summary>⚠️ <b>WARN</b> Checking OS/2 achVendID. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/vendorspecific.googlefonts.os2.html#"></a></summary>
    <div>







* ⚠️ **WARN** <p>OS/2 VendorID value 'NONE' is not yet recognized. If you registered it recently, then it's safe to ignore this warning message. Otherwise, you should set it to your own unique 4 character code, and register it with Microsoft at <a href="https://www.microsoft.com/typography/links/vendorlist.aspx">https://www.microsoft.com/typography/links/vendorlist.aspx</a></p>
 [code: unknown]



</div>
</details>

<details>
    <summary>ℹ️ <b>INFO</b> List all superfamily filepaths <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/superfamily.html#"></a></summary>
    <div>







* ℹ️ **INFO** <p>.</p>
 [code: family-path]



</div>
</details>

<details>
    <summary>ℹ️ <b>INFO</b> Show hinting filesize impact. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/hinting.html#"></a></summary>
    <div>







* ℹ️ **INFO** <p>Hinting filesize impact:</p>
<table>
<thead>
<tr>
<th align="left"></th>
<th align="right">Parkinsans_AW_Google[wght].ttf</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">Dehinted Size</td>
<td align="right">76.8kb</td>
</tr>
<tr>
<td align="left">Hinted Size</td>
<td align="right">76.8kb</td>
</tr>
<tr>
<td align="left">Increase</td>
<td align="right">24 bytes</td>
</tr>
<tr>
<td align="left">Change</td>
<td align="right">0.0 %</td>
</tr>
</tbody>
</table>
 [code: size-impact]



</div>
</details>

<details>
    <summary>ℹ️ <b>INFO</b> Font contains all required tables? <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/tables.html#"></a></summary>
    <div>







* ℹ️ **INFO** <p>This font contains the following optional tables:</p>
<pre><code>- loca

- prep

- GPOS

- GSUB

- gasp
</code></pre>
 [code: optional-tables]





</div>
</details>

<details>
    <summary>ℹ️ <b>INFO</b> Check for presence of an ARTICLE.en_us.html file <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/vendorspecific.googlefonts.description.html#"></a></summary>
    <div>







* ℹ️ **INFO** <p>This font doesn't have an ARTICLE.en_us.html file.</p>
 [code: missing-article]



</div>
</details>

<details>
    <summary>ℹ️ <b>INFO</b> EPAR table present in font? <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/vendorspecific.googlefonts.license.html#"></a></summary>
    <div>







* ℹ️ **INFO** <p>EPAR table not present in font. To learn more see <a href="https://github.com/fonttools/fontbakery/issues/818">https://github.com/fonttools/fontbakery/issues/818</a></p>
 [code: lacks-EPAR]



</div>
</details>

<details>
    <summary>ℹ️ <b>INFO</b> Is the Grid-fitting and Scan-conversion Procedure ('gasp') table set to optimize rendering? <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/vendorspecific.googlefonts.hinting.html#"></a></summary>
    <div>







* ℹ️ **INFO** <p>These are the ppm ranges declared on the gasp table:</p>
<p>PPM &lt;= 65535:
flag = 0x0F
- Use grid-fitting
- Use grayscale rendering
- Use gridfitting with ClearType symmetric smoothing
- Use smoothing along multiple axes with ClearType®</p>
 [code: ranges]



</div>
</details>

<details>
    <summary>ℹ️ <b>INFO</b> Font has old ttfautohint applied? <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/vendorspecific.googlefonts.hinting.html#"></a></summary>
    <div>







* ℹ️ **INFO** <p>Could not detect which version of ttfautohint was used in this font. It is typically specified as a comment in the font version entries of the 'name' table. Such font version strings are currently: ['Version 1.000']</p>
 [code: version-not-detected]



</div>
</details>
</div>
</details>

<details><summary>[1] Family checks</summary>
<div>
<details>
    <summary>ℹ️ <b>INFO</b> Check axis ordering on the STAT table. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/vendorspecific.googlefonts.stat.html#"></a></summary>
    <div>







* ℹ️ **INFO** <p>None of the fonts lack a STAT table.</p>
<pre><code>And these are the most common STAT axis orderings:
('wght', 1)
</code></pre>
 [code: summary]



</div>
</details>
</div>
</details>




### Summary

| 💥 ERROR | ☠ FATAL | 🔥 FAIL | ⚠️ WARN | ⏩ SKIP | ℹ️ INFO | ✅ PASS | 🔎 DEBUG | 
| ---|---|---|---|---|---|---|---|
| 0 | 0 | 1 | 14 | 100 | 8 | 129 | 0 | 
| 0% | 0% | 0% | 6% | 40% | 3% | 51% | 0% | 



**Note:** The following loglevels were omitted in this report:


* SKIP
* PASS
* DEBUG

**Comment by redstonedesign** [comment]
Thanks @m4rc1e, @davelab6  and @emmamarichal  for the kind feedback!

We appreciate the swift review, we’ll get started on fixing these issues today.

If there’s anything we can do to speed up the onboarding process to get the font live sooner it would be hugely appreciated!
Parkinson's UK (the UK's leading charity for the condition) are launching their new brand at the start of 2025. The charity largely relies on people with Parkinson's in local communities to create and share comms, anything we can do to get them set up in 2024, ahead of launch, would be super amazing. :pray:

**Comment by emmamarichal** [comment]
Hi @redstonedesign,
Here you can find some tools for checking at least the basic kerning :)
- https://idiotproofed.com/
- https://www.motaitalic.com/tools/font-tester/latin/ (in space/kern)

You can also find a lot of ressources here: https://typedesignresources.com/#proofing-tools

When we do the fonts QA, we use the gftools qa templates. You can also refer to these text strings:
[Spacing-kerning_checks.zip](https://github.com/user-attachments/files/17431086/Spacing-kerning_checks.zip)

**Comment by redstonedesign** [comment]
Hi @emmamarichal,
Thank you so much for your support so far with this. We’ve been working on the font over the last few days. We’ve now added kerning and have been tackling the Font Bakery errors.

The following errors still persist in our latest commit. Are you able to advise or take a look at how these could possibly be fixed?

Thanks again!

:fire: **FAIL** Check font names are correct  AND  :fire: **FAIL** Check the OS/2 usWeightClass is appropriate for the font’s best SubFamily name.
- We’ve tried everything to fix this and we’re not sure why we’re still getting the error.

:warning: **WARN** - Check if each glyph has the recommended amount of contours.
- We have checked these and we’re happy with the design.

:warning: **WARN** Validate size, and resolution of article images, and ensure article page has minimum length and includes visual assets.
- We’re struggling to fix this, the DESCRIPTION.en_us.html file is present and includes correct images.

:warning: **WARN** Check for codepoints not covered by METADATA subsets.
- We’re not sure how to fix. We’ve added the subsets to the meta table but aren’t sure how to access the metadata.pb file.

:warning: **WARN** Ensure soft_dotted characters lose their dot when combined with marks that replace the dot.
- We’re struggling to fix this, we tried adding CCMP Glyph compositon/decomposition rules which should have fixed it.

:warning: **WARN** Checking OS/2 achVendID.
- We’re not a registered font vender with Microsoft

:warning: **WARN** GPOS table lacks kerning info for non-ligated sequences.
- We have kerned these pairs, so not sure why we’re still getting this error.

:warning: **WARN** Are there any misaligned on-curve points?
:warning: **WARN** The following glyphs have segments which seem very short
:warning: **WARN** Do outlines contain any jaggy segments?
- We’ve fixed as much of this as we can.

**Comment by kenmcd** [comment]
> 🔥 **FAIL** Check font names are correct AND 🔥 **FAIL** Check the OS/2 usWeightClass is appropriate for the font’s best SubFamily name.
> 
>     * We’ve tried everything to fix this and we’re not sure why we’re still getting the error.

Probably this:

Change
`Semibold` to `SemiBold`

Change
`Extrabold` to `ExtraBold`

First it fails the style name check.
Then since the names are "wrong" it fails the OS/2 usWeightClass check.

The explanations for these are really bad.

GF folks - could somebody please make the explanations for these checks and the suggestions better.

**Comment by kenmcd** [comment]
> ⚠️ **WARN** Ensure soft_dotted characters lose their dot when combined with marks that replace the dot.
> 
>     * We’re struggling to fix this, we tried adding CCMP Glyph compositon/decomposition rules which should have fixed it.

`.notdef` should be glyph 0. Currently it is at # 369.
And it should be the "standard" format - e.g. a box. (see GF docs on this)

Odd results when testing this with `A` at GID#0.
But it looks like it is working.
Fix the `.notdef` and test again.

**Comment by emmamarichal** [comment]
Hi @redstonedesign,

> 🔥 FAIL Check font names are correct AND 🔥 FAIL Check the OS/2 usWeightClass is appropriate for the font’s best SubFamily name.
> We’ve tried everything to fix this and we’re not sure why we’re still getting the error.

Yes indeed, changing Semibold to SemiBold and Extrabold to ExtraBold should solve this. Don't forget to make the change on the masters names **and** instances. If the error is still here, no worries, I'll take a look and make more tests :)



> ⚠️ WARN Validate size, and resolution of article images, and ensure article page has minimum length and includes visual assets.
> We’re struggling to fix this, the DESCRIPTION.en_us.html file is present and includes correct images.

Yes, this warn should be updated I think, it concerns more the article, once we make a PR on the google fonts repo. We can ignore it for now!

For all the other ones, we can ignore it or I'll fix them when I'll review the font, no worries. Thanks a lot for all the work done!
The project is planned for the beginning of 2025, I'll come back to you if there are any other issue :)

**Comment by redstonedesign** [comment]
Thank you both for your help with these last issues!

@kenmcd  I’ve got back to you on the issues in https://github.com/redstonedesign/parkinsans/issues. Thanks for your detailed support and checking here.

@emmamarichal Thanks again for the info. As mentioned, we were hoping to get the font live before 2025. The charity will be launching their rebrand at the start of 2025 and the new typeface will be a central part of it. If there’s anything we can do to speed up the onboarding process it would be hugely appreciated!

**Comment by emmamarichal** [comment]
@redstonedesign I completely understand, and regarding the project, I think the onboarding can be done quickly. 

But I don't decide of how our milestones are planned. Since the Q4 is now done, I'm not sure we can add more projects to it.
Release schedules have been planned for weeks, if not months, and an issue opened two weeks ago won't necessarily have priority over others, unless it's commissioned or an exceptional case.
If I finish all my other projects before the end of Q4, I can work on this one.

Just in case, @chrissimpkins @davelab6 could you review this and tell me if a milestone change is possible?

**Comment by redstonedesign** [comment]
Thank you so much for your understanding @emmamarichal, and thank you for reaching out to see what's possible! Do let us know if there's anything else we can do on our side to make for as smooth an onboarding process as possible!

**Comment by redstonedesign** [comment]
Hi @chrissimpkins  @davelab6 ,
Just wondering if you’ve had chance to review this? I’m sure you have full schedules but if there’s anything we can do to get the font live before 2025 we’d be super grateful :pray:
Parkinson’s UK (the UK’s leading charity for the condition) are launching their new brand at the start of 2025. They largely rely on people with Parkinson’s in local communities to create and share comms.

**Comment by emmamarichal** [comment]
Hi @redstonedesign, we just moved the project to Q4. I'll start to look at it this week, before my other big projects start.
I'll send you a PR on your repo, with the fonts exported, and will let you know if I need any modifications from you!

**Comment by redstonedesign** [comment]
That's fantastic, thank you so much @emmamarichal! Not all heroes wear capes 🦸

**Comment by emmamarichal** [comment]
Hey @redstonedesign, fonts are live 🎉  https://fonts.google.com/specimen/Parkinsans

**Comment by redstonedesign** [comment]
We are thrilled Emma - thank you so much for pushing us through in 2024!!

It will be transformative for the charity, and those people affected by Parkinsons.

If you could reshare the link, that would be fab - I think I lost it in the excitement!

Huge thanks again - and if you’re ever in London EC1, drop by and we can have a coffee and bun to celebrate!
Hxxxxxx

Helen James
Head of projects and planning

…………………………

Red Stone
Technique
132-140 Goswell Road
London EC1V 7DY

T: 020 7336 0771
M: 07855 941851
www.red-stone.com <http://www.red-stone.com/>
http://twitter.com/RedStoneDesign

Registered in England: 3310761
..............................
