### ISSUE TITLE
Update EB Garamond to include italics

### ISSUE THREAD

**Issue by Keavon** [google/fonts#85]
EB Garamond now contains an italic typeface that is not included in [its Google Fonts page](https://www.google.com/fonts/specimen/EB+Garamond). The font's project page is at https://github.com/georgd/EB-Garamond

**Comment by danielklotz** [comment]
+1

**Comment by dannyyu92** [comment]
+ 1

Italicizing EB Garamond in Google Docs causes it to bug out and create indentation/formatting issues at the moment.

**Comment by blueset** [comment]
+1

**Comment by davelab6** [comment]
@m4rc1e please make a new PR for this :)

**Comment by davelab6** [comment]
However, probably we need to chat about it, because the family onboarded into the API no longer matches what the upstream has released....

**Comment by thlinard** [comment]
https://github.com/octaviopardo/EBGaramond12 is much more advanced than https://github.com/georgd/EB-Garamond
However, it isn't in a perfect finished state. But so much better…

**Comment by m4rc1e** [comment]
@thlinard thanks! I had a hunch this existed.

**Comment by davelab6** [comment]
> it isn't in a perfect finished state

What remains?

**Comment by thlinard** [comment]
Well, at least an export from the Glyphs source to ttf.

In January, Octavio Prado wrote:
"So! In the next month this is my planning to finish the font:

right now the italic is completely drawn in the heaviest weight, except for the ligatures. However, the original upright styles drawn by Georg had around 500 glyphs more (logically, since the italic styles were never completely finished) so I am adding all the ones that are missing in the italic like greek small caps for example. Also many of the existing glyphs were in the font but were not constructed in the right way, like the Celsius or the Farenheit glyphs, so I am almost reviewing every single exceptional glyph unicode and comparing it with other fonts (like Times or DejaVu serif) to make sure they are built properly. That is taking quite a lot of time. In this process I am also adjusting some glyphs that were already finished in both the upright and the italic.
Next step will be refining the design of many of the symbols optimized for the small caps like question marks, parenthesis and so on, right now they are merely a copy of the regular ones.
FInally I will create a Open Type Code to allow the user the access to the huge collection of glyphs and alternates. Georg did a great humongous job with this font but the only way to access many of the glyphs is via the glyph pallette in indesign. We should change that!!

Attached, an screenshot of Farenheit & Celsius glyphs properly constructed (previousy they didn t have the degree symbol) and the letter you see there is not eng, but modifier eng (U+1D51) that is suposed to be a superscript. EB is a great font but also very huge! I feel like it is a never ending project. There are always things to adjust…"
https://groups.google.com/d/msg/googlefonts-discuss/WeJ1hNceT-U/UTqlo1i9CgAJ

In March he wrote:
"The original design is from Georg Duffner and my intervention has been focused in expanding the fonts and trying to sync the upright with the italic but I might jump in the project again in the upcoming months so I will pay atention to all your notes! Keep posting them!"
https://github.com/octaviopardo/EBGaramond12/issues/2

**Comment by davelab6** [comment]
@thlinard I believe octavio has now done all that :)

**Comment by thlinard** [comment]
Oh yes, we've now nearly full charset coverage!
https://github.com/octaviopardo/EBGaramond12/issues/6

**Comment by davelab6** [comment]
The latest release has been focused on language support; @octaviopardo will continue working on the font after this month to the end of the year, and I am hopeful he can work on his idea quoted above to improve the OpenType feature code to allow users to access the huge collection of glyphs and alternates :)

**Comment by davelab6** [comment]
Italics are available
