### ISSUE TITLE
Noto Sans TC proportional single and double quotes not available

### ISSUE THREAD

**Issue by biancabberning** [google/fonts#8711]
I can’t seem to find Noto Sans TC in the list on https://notofonts.github.io/reporter.html, so I’ll report the issue here. Proportional width (pwid) alternates can’t be enabled, and are not working by default, for typographic single and double quotes (‘’“”, unicode code points: 2018 2019 201C 201D respectively).

**To Reproduce**

See my codepen -> https://codepen.io/bberning/pen/KwPdbPX

**Comment by emmamarichal** [comment]
@simoncozens?

**Comment by simoncozens** [comment]
The Google Fonts web API currently has extremely limited support for OpenType features, because we serve the fonts subset to as small a size as possible to reduce bandwidth. I'm afraid there isn't a way to do this through the Google Fonts, although of course it is possible for you to self-host them...

Cc @garretrieger - for information, another case for arbitrary OT features through the API.
