### ISSUE TITLE
AmaticSC-Bold is missing a glyph for the tilde character (Unicode U+007E)

### ISSUE THREAD

**Issue by Ziriax** [google/fonts#96]
~ is missing in the bold font face, but is present in the regular one.

Also, bold is at version 1.001 and regular at 1.003?

**Comment by graphicore** [comment]
Fixed in:  https://github.com/graphicore/MaticFonts

![screen shot 2016-09-05 at 03 04 02](https://cloud.githubusercontent.com/assets/393132/18244544/6f0e155c-7315-11e6-859d-7c7fa09ae92d.png)

Though some other glyphs are missing in the Bold that are present in the Regular (see also the README of the MaticFonts repo): Delta, Omega, mu, micro, onesuperior, twosuperior, threesuperior, foursuperior, bulletoperator, divisionslash, softhyphen;

**Comment by laerm0** [comment]
Amatic is now tildeified.

![screen region 2017-09-11 at 16 07 28](https://user-images.githubusercontent.com/10780161/30294526-62d19708-970b-11e7-8100-08635eaa1229.png)
